# $Id: Makefile,v 1.1 1997/03/11 14:32:24 carr Exp $

HERE = libs/graphicInterface/cmdProcs/paraScopeEditor/stubs

SRCS = \
	   pedStubs.C

ARCHIVE	= stubs-$(DSYSTEM_OS)-g.a

include ../../../../../make.config

include $(DEPENDS)

# DO NOT DELETE THIS LINE -- make depend depends on it.