# $Id: Makefile,v 1.3 1997/03/27 21:01:59 carr Exp $

HERE = libs/fortD/localInfo

SRCS = \
	   CommBlock.C \
	   FortDExpr.C \
	   FortDHash.C \
	   FortDMisc.C \
	   LocalOverlap.C \
	   LocalRDecomp.C \
	   fd_symtable.ansi.c

ARCHIVE	= ../FortD-$(DSYSTEM_OS)-g.a

include ../../../make.config

include $(DEPENDS)

# DO NOT DELETE THIS LINE -- make depend depends on it.