# $Id: Makefile,v 1.1 1997/03/11 14:28:43 carr Exp $

HERE = libs/fortD/localInfo

SRCS = \
	   CommBlock.C \
	   FortDExpr.C \
	   FortDHash.C \
	   FortDMisc.C \
	   LocalOverlap.C \
	   LocalRDecomp.C \
	   fd_symtable.ansi.c

ARCHIVE	= FortD-$(DSYSTEM_OS)-g.a

include Makeinclude

