# $Id: Makefile,v 1.2 1997/03/27 20:33:11 carr Exp $

HERE = libs/fortD/localInfo

#	   CommBlock.C 
SRCS = \
	   FortDExpr.C \
	   FortDHash.C \
	   FortDMisc.C \
	   LocalOverlap.C \
	   LocalRDecomp.C \
	   fd_symtable.ansi.c

ARCHIVE	= FortD-$(DSYSTEM_OS)-g.a

include Makeinclude

