/* $Id: forttypes.C,v 1.1 1997/06/24 17:41:50 carr Exp $ */
/******************************************************************************/
/*        Copyright (c) 1990, 1991, 1992, 1993, 1994 Rice University          */
/*                           All Rights Reserved                              */
/******************************************************************************/
#include <libs/frontEnd/ast/forttypes.h>


int type_to_size_in_bytes[TYPE_LAST] = {
	/* TYPE_UNKNOWN          */  -1,
	/* TYPE_INTEGER          */  SIZE_PER_INTEGER,
	/* TYPE_REAL             */  SIZE_PER_REAL,
	/* TYPE_DOUBLE_PRECISION */  SIZE_PER_DB_PREC,
	/* TYPE_COMPLEX          */  SIZE_PER_COMPLEX,
    /* TYPE_LOGICAL          */  SIZE_PER_LOGICAL,
    /* TYPE_LABEL            */  SIZE_PER_LABEL,
    /* TYPE_CHARACTER        */  SIZE_PER_CHAR,
    /* TYPE_ERROR            */  -2, 
    /* TYPE_EXACT            */  SIZE_PER_EXACT,
    /* TYPE_NONE             */  -3,
    /* TYPE_EVENT            */  SIZE_PER_EVENT,
    /* TYPE_SEMAPHORE        */  SIZE_PER_SEMAPHORE,
    /* TYPE_BARRIER          */  SIZE_PER_BARRIER
};


#define UNK	TYPE_UNKNOWN
#define INT	TYPE_INTEGER
#define REL	TYPE_REAL
#define DBP	TYPE_DOUBLE_PRECISION
#define CPX	TYPE_COMPLEX
#define LOG	TYPE_LOGICAL
#define LAB	TYPE_LABEL
#define CHR	TYPE_CHARACTER
#define ERR	TYPE_ERROR
#define EXA	TYPE_EXACT
#define NON	TYPE_NONE
#define EVT	TYPE_EVENT
#define SEM	TYPE_SEMAPHORE
#define BAR	TYPE_BARRIER

/* ------------------- type tables for the type checker -------------------*/

/* unary minus*/
MAP_TYPE minus_type_map[TYPE_LAST] =      {
      /*UNK INT REL DBP CPX LOG LAB CHR ERR EXA NON EVT SEM BAR*/
        UNK,INT,REL,DBP,CPX,ERR,ERR,ERR,UNK,EXA,ERR,ERR,ERR,ERR
};

/* unary minus*/
MAP_TYPE not_type_map[TYPE_LAST] =      {
      /*UNK INT REL DBP CPX LOG LAB CHR ERR EXA NON EVT SEM BAR*/
        UNK,ERR,ERR,ERR,ERR,LOG,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR
};

/* times, divide, plus, minus*/
MAP_TYPE mult_type_map[TYPE_LAST][TYPE_LAST] = {
      /*UNK INT REL DBP CPX LOG LAB CHR ERR EXA NON EVT SEM BAR*/
/*UNK*/ UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,ERR,ERR,ERR,ERR,
/*INT*/ UNK,INT,REL,DBP,CPX,ERR,ERR,ERR,UNK,EXA,ERR,ERR,ERR,ERR,
/*REL*/ UNK,REL,REL,DBP,CPX,ERR,ERR,ERR,UNK,EXA,ERR,ERR,ERR,ERR,
/*DBP*/ UNK,DBP,DBP,DBP,CPX,ERR,ERR,ERR,UNK,EXA,ERR,ERR,ERR,ERR,
/*CPX*/ UNK,CPX,CPX,CPX,CPX,ERR,ERR,ERR,UNK,ERR,ERR,ERR,ERR,ERR,
/*LOG*/ UNK,ERR,ERR,ERR,ERR,ERR,ERR,ERR,UNK,ERR,ERR,ERR,ERR,ERR,
/*LAB*/ UNK,ERR,ERR,ERR,ERR,ERR,ERR,ERR,UNK,ERR,ERR,ERR,ERR,ERR,
/*CHR*/ UNK,ERR,ERR,ERR,ERR,ERR,ERR,CHR,UNK,ERR,ERR,ERR,ERR,ERR,
/*ERR*/ UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,ERR,ERR,ERR,ERR,
/*EXA*/ UNK,EXA,EXA,EXA,ERR,ERR,ERR,ERR,UNK,EXA,ERR,ERR,ERR,ERR,
/*NON*/ ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,
/*EVT*/ ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,
/*SEM*/ ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,
/*BAR*/ ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR
};

/* ge gt le lt*/
MAP_TYPE ge_type_map[TYPE_LAST][TYPE_LAST] = {
      /*UNK INT REL DBP CPX LOG LAB CHR ERR EXA NON EVT SEM BAR*/
/*UNK*/ UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,ERR,ERR,ERR,ERR,
/*INT*/ UNK,LOG,LOG,LOG,LOG,ERR,ERR,ERR,UNK,LOG,ERR,ERR,ERR,ERR,
/*REL*/ UNK,LOG,LOG,LOG,LOG,ERR,ERR,ERR,UNK,LOG,ERR,ERR,ERR,ERR,
/*DBP*/ UNK,LOG,LOG,LOG,ERR,ERR,ERR,ERR,UNK,LOG,ERR,ERR,ERR,ERR,
/*CPX*/ UNK,LOG,LOG,ERR,LOG,ERR,ERR,ERR,UNK,ERR,ERR,ERR,ERR,ERR,
/*LOG*/ UNK,ERR,ERR,ERR,ERR,ERR,ERR,ERR,UNK,ERR,ERR,ERR,ERR,ERR,
/*LAB*/ UNK,ERR,ERR,ERR,ERR,ERR,ERR,ERR,UNK,ERR,ERR,ERR,ERR,ERR,
/*CHR*/ UNK,ERR,ERR,ERR,ERR,ERR,ERR,LOG,UNK,ERR,ERR,ERR,ERR,ERR,
/*ERR*/ UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,ERR,ERR,ERR,ERR,
/*EXA*/ UNK,LOG,LOG,LOG,ERR,ERR,ERR,ERR,UNK,LOG,ERR,ERR,ERR,ERR,
/*NON*/ ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,
/*EVT*/ ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,
/*SEM*/ ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,
/*BAR*/ ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR
};

/* ge gt le lt*/
MAP_TYPE ge_arg_type_map[TYPE_LAST][TYPE_LAST] = {	
      /*UNK INT REL DBP CPX LOG LAB CHR ERR EXA NON EVT SEM BAR*/
/*UNK*/ UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,ERR,ERR,ERR,ERR,
/*INT*/ UNK,INT,REL,DBP,ERR,ERR,ERR,ERR,UNK,DBP,ERR,ERR,ERR,ERR,
/*REL*/ UNK,REL,REL,DBP,ERR,ERR,ERR,ERR,UNK,DBP,ERR,ERR,ERR,ERR,
/*DBP*/ UNK,DBP,DBP,DBP,ERR,ERR,ERR,ERR,UNK,DBP,ERR,ERR,ERR,ERR,
/*CPX*/ UNK,ERR,ERR,ERR,ERR,ERR,ERR,ERR,UNK,ERR,ERR,ERR,ERR,ERR,
/*LOG*/ UNK,ERR,ERR,ERR,ERR,ERR,ERR,ERR,UNK,ERR,ERR,ERR,ERR,ERR,
/*LAB*/ UNK,ERR,ERR,ERR,ERR,ERR,ERR,ERR,UNK,ERR,ERR,ERR,ERR,ERR,
/*CHR*/ UNK,ERR,ERR,ERR,ERR,ERR,ERR,CHR,UNK,ERR,ERR,ERR,ERR,ERR,
/*ERR*/ UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,ERR,ERR,ERR,ERR,
/*EXA*/ UNK,DBP,DBP,DBP,ERR,ERR,ERR,ERR,UNK,DBP,ERR,ERR,ERR,ERR,
/*NON*/ ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,
/*EVT*/ ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,
/*SEM*/ ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,
/*BAR*/ ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR
};

/* eq ne*/
MAP_TYPE eq_type_map[TYPE_LAST][TYPE_LAST] = {
      /*UNK INT REL DBP CPX LOG LAB CHR ERR EXA NON EVT SEM BAR*/
/*UNK*/ UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,ERR,UNK,UNK,UNK,
/*INT*/ UNK,LOG,LOG,LOG,LOG,ERR,ERR,ERR,UNK,LOG,ERR,ERR,ERR,ERR,
/*REL*/ UNK,LOG,LOG,LOG,LOG,ERR,ERR,ERR,UNK,LOG,ERR,ERR,ERR,ERR,
/*DBP*/ UNK,LOG,LOG,LOG,ERR,ERR,ERR,ERR,UNK,LOG,ERR,ERR,ERR,ERR,
/*CPX*/ UNK,LOG,LOG,ERR,LOG,ERR,ERR,ERR,UNK,ERR,ERR,ERR,ERR,ERR,
/*LOG*/ UNK,ERR,ERR,ERR,ERR,LOG,ERR,ERR,UNK,ERR,ERR,ERR,ERR,ERR,
/*LAB*/ UNK,ERR,ERR,ERR,ERR,ERR,ERR,ERR,UNK,ERR,ERR,ERR,ERR,ERR,
/*CHR*/ UNK,ERR,ERR,ERR,ERR,ERR,ERR,LOG,UNK,ERR,ERR,ERR,ERR,ERR,
/*ERR*/ UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,ERR,ERR,ERR,ERR,
/*EXA*/ UNK,LOG,LOG,LOG,ERR,ERR,ERR,ERR,UNK,LOG,ERR,ERR,ERR,ERR,
/*NON*/ ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,
/*EVT*/ UNK,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,LOG,ERR,ERR,
/*SEM*/ UNK,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,LOG,ERR,
/*BAR*/ UNK,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,LOG
};

/* eq ne*/
MAP_TYPE eq_arg_type_map[TYPE_LAST][TYPE_LAST] = {
      /*UNK INT REL DBP CPX LOG LAB CHR ERR EXA NON EVT SEM BAR*/
/*UNK*/ UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,ERR,UNK,UNK,UNK,
/*INT*/ UNK,INT,REL,DBP,CPX,ERR,ERR,ERR,UNK,DBP,ERR,ERR,ERR,ERR,
/*REL*/ UNK,REL,REL,DBP,CPX,ERR,ERR,ERR,UNK,DBP,ERR,ERR,ERR,ERR,
/*DBP*/ UNK,DBP,DBP,DBP,CPX,ERR,ERR,ERR,UNK,DBP,ERR,ERR,ERR,ERR,
/*CPX*/ UNK,CPX,CPX,CPX,CPX,ERR,ERR,ERR,UNK,CPX,ERR,ERR,ERR,ERR,
/*LOG*/ UNK,ERR,ERR,ERR,ERR,LOG,ERR,ERR,UNK,ERR,ERR,ERR,ERR,ERR,
/*LAB*/ UNK,ERR,ERR,ERR,ERR,ERR,ERR,ERR,UNK,ERR,ERR,ERR,ERR,ERR,
/*CHR*/ UNK,ERR,ERR,ERR,ERR,ERR,ERR,CHR,UNK,ERR,ERR,ERR,ERR,ERR,
/*ERR*/ UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,ERR,ERR,ERR,ERR,
/*EXA*/ UNK,DBP,DBP,DBP,CPX,ERR,ERR,ERR,UNK,DBP,ERR,ERR,ERR,ERR,
/*NON*/ ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,
/*EVT*/ UNK,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,EVT,ERR,ERR,
/*SEM*/ UNK,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,SEM,ERR,
/*BAR*/ UNK,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,BAR
};

/* and or eqv neqv*/
MAP_TYPE and_type_map[TYPE_LAST][TYPE_LAST] = {
      /*UNK INT REL DBP CPX LOG LAB CHR ERR EXA NON EVT SEM BAR*/
/*UNK*/ UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,ERR,ERR,ERR,ERR,
/*INT*/ UNK,ERR,ERR,ERR,ERR,ERR,ERR,ERR,UNK,ERR,ERR,ERR,ERR,ERR,
/*REL*/ UNK,ERR,ERR,ERR,ERR,ERR,ERR,ERR,UNK,ERR,ERR,ERR,ERR,ERR,
/*DBP*/ UNK,ERR,ERR,ERR,ERR,ERR,ERR,ERR,UNK,ERR,ERR,ERR,ERR,ERR,
/*CPX*/ UNK,ERR,ERR,ERR,ERR,ERR,ERR,ERR,UNK,ERR,ERR,ERR,ERR,ERR,
/*LOG*/ UNK,ERR,ERR,ERR,ERR,LOG,ERR,ERR,UNK,ERR,ERR,ERR,ERR,ERR,
/*LAB*/ UNK,ERR,ERR,ERR,ERR,ERR,ERR,ERR,UNK,ERR,ERR,ERR,ERR,ERR,
/*CHR*/ UNK,ERR,ERR,ERR,ERR,ERR,ERR,ERR,UNK,ERR,ERR,ERR,ERR,ERR,
/*ERR*/ UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,ERR,ERR,ERR,ERR,
/*EXA*/ UNK,ERR,ERR,ERR,ERR,ERR,ERR,ERR,UNK,ERR,ERR,ERR,ERR,ERR,
/*NON*/ ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,
/*EVT*/ ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,
/*SEM*/ ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,
/*BAR*/ ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR
};

/* and or eqv neqv*/
MAP_TYPE concat_type_map[TYPE_LAST][TYPE_LAST] = {
      /*UNK INT REL DBP CPX LOG LAB CHR ERR EXA NON EVT SEM BAR*/
/*UNK*/ UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,ERR,ERR,ERR,ERR,
/*INT*/ UNK,ERR,ERR,ERR,ERR,ERR,ERR,ERR,UNK,ERR,ERR,ERR,ERR,ERR,
/*REL*/ UNK,ERR,ERR,ERR,ERR,ERR,ERR,ERR,UNK,ERR,ERR,ERR,ERR,ERR,
/*DBP*/ UNK,ERR,ERR,ERR,ERR,ERR,ERR,ERR,UNK,ERR,ERR,ERR,ERR,ERR,
/*CPX*/ UNK,ERR,ERR,ERR,ERR,ERR,ERR,ERR,UNK,ERR,ERR,ERR,ERR,ERR,
/*LOG*/ UNK,ERR,ERR,ERR,ERR,ERR,ERR,ERR,UNK,ERR,ERR,ERR,ERR,ERR,
/*LAB*/ UNK,ERR,ERR,ERR,ERR,ERR,ERR,ERR,UNK,ERR,ERR,ERR,ERR,ERR,
/*CHR*/ UNK,ERR,ERR,ERR,ERR,ERR,ERR,CHR,UNK,ERR,ERR,ERR,ERR,ERR,
/*ERR*/ UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,ERR,ERR,ERR,ERR,
/*EXA*/ UNK,ERR,ERR,ERR,ERR,ERR,ERR,ERR,UNK,ERR,ERR,ERR,ERR,ERR,
/*NON*/ ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,
/*EVT*/ ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,
/*SEM*/ ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,
/*BAR*/ ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR
};

/* ASSIGNMENT*/
MAP_TYPE assign_type_map[TYPE_LAST][TYPE_LAST] = {
      /*UNK INT REL DBP CPX LOG LAB CHR ERR EXA NON EVT SEM BAR*/
/*UNK*/ UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,ERR,UNK,UNK,UNK,
/*INT*/ UNK,INT,INT,INT,INT,ERR,ERR,ERR,UNK,INT,ERR,ERR,ERR,ERR,
/*REL*/ UNK,REL,REL,REL,REL,ERR,ERR,ERR,UNK,REL,ERR,ERR,ERR,ERR,
/*DBP*/ UNK,DBP,DBP,DBP,DBP,ERR,ERR,ERR,UNK,DBP,ERR,ERR,ERR,ERR,
/*CPX*/ UNK,CPX,CPX,CPX,CPX,ERR,ERR,ERR,UNK,CPX,ERR,ERR,ERR,ERR,
/*LOG*/ UNK,ERR,ERR,ERR,ERR,LOG,ERR,ERR,UNK,ERR,ERR,ERR,ERR,ERR,
/*LAB*/ UNK,ERR,ERR,ERR,ERR,ERR,LAB,ERR,UNK,ERR,ERR,ERR,ERR,ERR,
/*CHR*/ UNK,ERR,ERR,ERR,ERR,ERR,ERR,CHR,UNK,ERR,ERR,ERR,ERR,ERR,
/*ERR*/ UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,ERR,ERR,ERR,ERR,
/*EXA*/ UNK,EXA,EXA,EXA,EXA,ERR,ERR,ERR,UNK,EXA,ERR,ERR,ERR,ERR,
/*NON*/ ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,
/*EVT*/ ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,EVT,ERR,ERR,
/*SEM*/ ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,SEM,ERR,
/*BAR*/ ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,BAR
};

MAP_TYPE rhs_assign_type_map[TYPE_LAST][TYPE_LAST] = {
      /*UNK INT REL DBP CPX LOG LAB CHR ERR EXA NON EVT SEM BAR*/
/*UNK*/ UNK,INT,REL,DBP,CPX,LOG,LAB,CHR,UNK,EXA,ERR,EVT,SEM,BAR,
/*INT*/ UNK,INT,INT,INT,INT,LOG,LAB,CHR,UNK,INT,ERR,ERR,ERR,ERR,
/*REL*/ UNK,REL,REL,REL,REL,LOG,LAB,CHR,UNK,REL,ERR,ERR,ERR,ERR,
/*DBP*/ UNK,DBP,DBP,DBP,DBP,LOG,LAB,CHR,UNK,DBP,ERR,ERR,ERR,ERR,
/*CPX*/ UNK,CPX,CPX,CPX,CPX,LOG,LAB,CHR,UNK,CPX,ERR,ERR,ERR,ERR,
/*LOG*/ UNK,INT,REL,DBP,CPX,LOG,LAB,CHR,UNK,EXA,ERR,ERR,ERR,ERR,
/*LAB*/ UNK,INT,REL,DBP,CPX,LOG,LAB,CHR,UNK,EXA,ERR,ERR,ERR,ERR,
/*CHR*/ UNK,INT,REL,DBP,CPX,LOG,LAB,CHR,UNK,EXA,ERR,ERR,ERR,ERR,
/*ERR*/ UNK,INT,REL,DBP,CPX,LOG,LAB,CHR,UNK,EXA,ERR,ERR,ERR,ERR,
/*EXA*/ UNK,EXA,EXA,EXA,ERR,LOG,LAB,CHR,UNK,EXA,ERR,ERR,ERR,ERR,
/*NON*/ ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,
/*EVT*/ EVT,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,EVT,ERR,ERR,
/*SEM*/ SEM,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,SEM,ERR,
/*BAR*/ BAR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,BAR
};

/* EXPONENTIAL*/
MAP_TYPE exp_type_map[TYPE_LAST][TYPE_LAST] = {
      /*UNK INT REL DBP CPX LOG LAB CHR ERR EXA NON EVT SEM BAR*/
/*UNK*/ UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,ERR,ERR,ERR,ERR,
/*INT*/ UNK,INT,REL,DBP,CPX,ERR,ERR,ERR,UNK,EXA,ERR,ERR,ERR,ERR,
/*REL*/ UNK,REL,REL,DBP,CPX,ERR,ERR,ERR,UNK,EXA,ERR,ERR,ERR,ERR,
/*DBP*/ UNK,DBP,DBP,DBP,CPX,ERR,ERR,ERR,UNK,DBP,ERR,ERR,ERR,ERR,
/*CPX*/ UNK,CPX,CPX,CPX,CPX,ERR,ERR,ERR,UNK,ERR,ERR,ERR,ERR,ERR,
/*LOG*/ UNK,ERR,ERR,ERR,ERR,ERR,ERR,ERR,UNK,ERR,ERR,ERR,ERR,ERR,
/*LAB*/ UNK,ERR,ERR,ERR,ERR,ERR,ERR,ERR,UNK,ERR,ERR,ERR,ERR,ERR,
/*CHR*/ UNK,ERR,ERR,ERR,ERR,ERR,ERR,ERR,UNK,ERR,ERR,ERR,ERR,ERR,
/*ERR*/ UNK,ERR,ERR,ERR,ERR,ERR,ERR,ERR,UNK,ERR,ERR,ERR,ERR,ERR,
/*EXA*/ UNK,EXA,EXA,EXA,ERR,ERR,ERR,ERR,ERR,EXA,ERR,ERR,ERR,ERR,
/*NON*/ ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,
/*EVT*/ ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,
/*SEM*/ ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,
/*BAR*/ ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR
};

MAP_TYPE lhs_exp_type_map[TYPE_LAST][TYPE_LAST] = {
      /*UNK INT REL DBP CPX LOG LAB CHR ERR EXA NON EVT SEM BAR*/
/*UNK*/ UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,ERR,ERR,ERR,ERR,
/*INT*/ INT,INT,REL,DBP,CPX,INT,INT,INT,INT,INT,ERR,ERR,ERR,ERR,
/*REL*/ REL,REL,REL,DBP,CPX,REL,REL,REL,REL,REL,ERR,ERR,ERR,ERR,
/*DBP*/ DBP,DBP,DBP,DBP,DBP,DBP,DBP,DBP,DBP,DBP,ERR,ERR,ERR,ERR,
/*CPX*/ CPX,CPX,CPX,CPX,CPX,CPX,CPX,CPX,CPX,CPX,ERR,ERR,ERR,ERR,
/*LOG*/ LOG,LOG,LOG,LOG,LOG,LOG,LOG,LOG,LOG,LOG,ERR,ERR,ERR,ERR,
/*LAB*/ LAB,LAB,LAB,LAB,LAB,LAB,LAB,LAB,LAB,LAB,ERR,ERR,ERR,ERR,
/*CHR*/ CHR,CHR,CHR,CHR,CHR,CHR,CHR,CHR,CHR,CHR,ERR,ERR,ERR,ERR,
/*ERR*/ UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,ERR,ERR,ERR,ERR,
/*EXA*/ EXA,EXA,EXA,EXA,ERR,EXA,EXA,EXA,EXA,EXA,ERR,ERR,ERR,ERR,
/*NON*/ ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,
/*EVT*/ ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,
/*SEM*/ ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,
/*BAR*/ ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR
};

MAP_TYPE rhs_exp_type_map[TYPE_LAST][TYPE_LAST] = {
      /*UNK INT REL DBP CPX LOG LAB CHR ERR EXA NON EVT SEM BAR*/
/*UNK*/ UNK,INT,REL,DBP,CPX,LOG,LAB,CHR,UNK,EXA,ERR,ERR,ERR,ERR,
/*INT*/ UNK,INT,REL,DBP,CPX,LOG,LAB,CHR,UNK,EXA,ERR,ERR,ERR,ERR,
/*REL*/ UNK,INT,REL,DBP,CPX,LOG,LAB,CHR,UNK,EXA,ERR,ERR,ERR,ERR,
/*DBP*/ UNK,INT,DBP,DBP,CPX,LOG,LAB,CHR,UNK,EXA,ERR,ERR,ERR,ERR,
/*CPX*/ UNK,INT,CPX,DBP,CPX,LOG,LAB,CHR,UNK,EXA,ERR,ERR,ERR,ERR,
/*LOG*/ UNK,INT,REL,DBP,CPX,LOG,LAB,CHR,UNK,EXA,ERR,ERR,ERR,ERR,
/*LAB*/ UNK,INT,REL,DBP,CPX,LOG,LAB,CHR,UNK,EXA,ERR,ERR,ERR,ERR,
/*CHR*/ UNK,INT,REL,DBP,CPX,LOG,LAB,CHR,UNK,EXA,ERR,ERR,ERR,ERR,
/*ERR*/ UNK,INT,REL,DBP,CPX,LOG,LAB,CHR,UNK,EXA,ERR,ERR,ERR,ERR,
/*EXA*/ UNK,EXA,EXA,EXA,CPX,LOG,LAB,CHR,UNK,EXA,ERR,ERR,ERR,ERR,
/*NON*/ ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,
/*EVT*/ ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,
/*SEM*/ ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,
/*BAR*/ ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR,ERR
};

MAP_TYPE is_arith_type[TYPE_LAST] =
/*UNK INT REL DBP CPX LOG LAB CHR ERR EXA NON EVT SEM BAR*/
{ 1,  1,  1,  1,  1,  0,  0,  0,  1,  1,  0,  0,  0,  0};

MAP_TYPE is_char_type[TYPE_LAST] =
/*UNK INT REL DBP CPX LOG LAB CHR ERR EXA NON EVT SEM BAR*/
{ 1,  0,  0,  0,  0,  0,  0,  1,  1,  0,  0,  0,  0,  0};

MAP_TYPE is_log_type[TYPE_LAST] =
/*UNK INT REL DBP CPX LOG LAB CHR ERR EXA NON EVT SEM BAR*/
{ 1,  0,  0,  0,  0,  1,  0,  0,  1,  0,  0,  0,  0,  0};

MAP_TYPE is_integer_type[TYPE_LAST] =
/*UNK INT REL DBP CPX LOG LAB CHR ERR EXA NON EVT SEM BAR*/
{ 1,  1,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0};

MAP_TYPE is_label_type[TYPE_LAST] =
/*UNK INT REL DBP CPX LOG LAB CHR ERR EXA NON EVT SEM BAR*/
{ 1,  0,  0,  0,  0,  0,  1,  0,  1,  0,  0,  0,  0,  0};


/* ------------------- type table for the composition editor ---------------*/


#undef TOK
#define TOK TYPE_MATCH_OK

#undef TWN 
#define TWN TYPE_MATCH_WARNING

#undef TER 
#define TER TYPE_MATCH_ERROR

CompTypeMatch composition_type_match_table[TYPE_LAST][TYPE_LAST] = {
      /*UNK INT REL DBP CPX LOG LAB CHR ERR EXA NON EVT SEM BAR*/
/*UNK*/ TOK,TOK,TOK,TOK,TOK,TOK,TOK,TOK,TOK,TOK,TOK,TOK,TOK,TOK,
/*INT*/ TOK,TOK,TWN,TWN,TWN,TWN,TWN,TWN,TER,TWN,TER,TER,TER,TER,
/*REL*/ TOK,TWN,TOK,TWN,TWN,TWN,TER,TER,TER,TWN,TER,TER,TER,TER,
/*DBP*/ TOK,TWN,TWN,TOK,TWN,TWN,TER,TER,TER,TWN,TER,TER,TER,TER,
/*CPX*/ TOK,TWN,TWN,TWN,TOK,TWN,TER,TER,TER,TWN,TER,TER,TER,TER,
/*LOG*/ TOK,TWN,TWN,TWN,TWN,TOK,TER,TER,TER,TWN,TER,TER,TER,TER,
/*LAB*/ TOK,TWN,TER,TER,TER,TER,TOK,TER,TER,TER,TER,TER,TER,TER,
/*CHR*/ TOK,TWN,TER,TER,TER,TER,TER,TOK,TER,TER,TER,TER,TER,TER,
/*ERR*/ TER,TER,TER,TER,TER,TER,TER,TER,TER,TER,TER,TER,TER,TER,
/*EXA*/ TOK,TWN,TWN,TWN,TWN,TWN,TER,TER,TER,TOK,TER,TER,TER,TER,
/*NON*/ TOK,TER,TER,TER,TER,TER,TER,TER,TER,TER,TOK,TER,TER,TER,
/*EVT*/ TOK,TER,TER,TER,TER,TER,TER,TER,TER,TER,TER,TER,TER,TER,
/*SEM*/ TOK,TER,TER,TER,TER,TER,TER,TER,TER,TER,TER,TER,TER,TER,
/*BAR*/ TOK,TER,TER,TER,TER,TER,TER,TER,TER,TER,TER,TER,TER,TER
};
