# $Id: Makefile,v 1.3 1997/03/27 21:05:56 carr Exp $

HERE = libs/frontEnd/ast

SRCS = \
	   aphelper.ansi.c \
	   astlist.ansi.c \
	   asttree.ansi.c \
	   builtins.ansi.c \
	   cd_branch.ansi.c \
	   forttypes.c \
	   ftxform.ansi.c \
	   gensupport.ansi.c \
	   groups.ansi.c \
	   seminterface.ansi.c \
	   strutil.ansi.c \
	   treeutil.ansi.c \
	   AstIterators.C \
	   NeedProvSet.C \
	   astutil.C \
	   ftExportSimple.C \
	   AST_ht.C \
	   AST_Set_ht.C \
	   AstIter.C \
	   map.C

ARCHIVE	= ../FrontEnd-$(DSYSTEM_OS)-g.a

include Makeinclude
