# $Id: Makefile,v 1.1 1997/03/11 14:29:19 carr Exp $

HERE = libs/frontEnd/ast

SRCS = \
	   aphelper.ansi.c \
	   astlist.ansi.c \
	   asttree.ansi.c \
	   builtins.ansi.c \
	   cd_branch.ansi.c \
	   forttypes.c \
	   ftxform.ansi.c \
	   gensupport.ansi.c \
	   groups.ansi.c \
	   seminterface.ansi.c \
	   strutil.ansi.c \
	   treeutil.ansi.c \
	   AST_Set_ht.C \
	   AST_ht.C \
	   AstIter.C \
	   AstIterators.C \
	   NeedProvSet.C \
	   astutil.C \
	   ftExportSimple.C \
	   map.C

ARCHIVE	= ../FrontEnd-$(DSYSTEM_OS)-g.a

include Makeinclude
