# $Id: Makefile,v 1.4 1997/06/24 17:41:50 carr Exp $

HERE = libs/frontEnd/ast

SRCS = \
	   aphelper.C \
	   astlist.C \
	   asttree.C \
	   builtins.C \
	   cd_branch.C \
	   forttypes.C \
	   ftxform.C \
	   gensupport.C \
	   groups.C \
	   seminterface.C \
	   strutil.C \
	   treeutil.C \
	   AstIterators.C \
	   NeedProvSet.C \
	   astutil.C \
	   ftExportSimple.C \
	   AST_ht.C \
	   AST_Set_ht.C \
	   AstIter.C \
	   map.C

ARCHIVE	= ../FrontEnd-$(DSYSTEM_OS)-g.a

include ../../../make.config

include $(DEPENDS)

# DO NOT DELETE THIS LINE -- make depend depends on it.