# $Id: Makefile,v 1.2 1997/06/25 14:40:06 carr Exp $

HERE = libs/graphicInterface/cmdProcs/paraScopeEditor/dg

SRCS = \
	   ped_cd.C \
	   ped_dg.C \
	   ped_util_dg.C

ARCHIVE	= ped-$(DSYSTEM_OS)-g.a

include Makeinclude
