# $Id: Makefile,v 1.1 1997/03/11 14:31:00 carr Exp $

HERE = libs/graphicInterface/cmdProcs/paraScopeEditor/dg

SRCS = \
	   ped_cd.ansi.c \
	   ped_dg.ansi.c \
	   ped_util_dg.ansi.c

ARCHIVE	= ped-$(DSYSTEM_OS)-g.a

include Makeinclude
