# $Id: Makefile,v 1.1 1997/03/11 14:31:11 carr Exp $

HERE = libs/graphicInterface/cmdProcs/paraScopeEditor/dt

SRCS = \
	   ped_dt.ansi.c \
	   ped_dt_build.c \
	   ped_rsd.ansi.c

ARCHIVE	= ped-$(DSYSTEM_OS)-g.a

include Makeinclude
