# $Id: Makefile,v 1.2 1997/06/25 14:41:17 carr Exp $

HERE = libs/graphicInterface/cmdProcs/paraScopeEditor/dt

SRCS = \
	   ped_dt.C \
	   ped_dt_build.C \
	   ped_rsd.C

ARCHIVE	= ped-$(DSYSTEM_OS)-g.a

include Makeinclude
