# $Id: Makefile,v 1.2 1997/06/25 15:09:47 carr Exp $

HERE = libs/moduleAnalysis/dependence/loopInfo

SRCS = \
	   li.C \
	   li_read.C \
	   li_save.C

ARCHIVE	= ../ModuleAnalysis-$(DSYSTEM_OS)-g.a

include ../../../../make.config

include $(DEPENDS)

# DO NOT DELETE THIS LINE -- make depend depends on it.
