# $Id: Makefile,v 1.1 1997/03/11 14:36:00 carr Exp $

HERE = libs/moduleAnalysis/dependence/loopInfo

SRCS = \
	   li.ansi.c \
	   li_read.ansi.c \
	   li_save.ansi.c

ARCHIVE	= ../ModuleAnalysis-$(DSYSTEM_OS)-g.a

include Makeinclude
