#line 2 "lexDirectives.c"

#line 4 "lexDirectives.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define a2i__create_buffer a2i__create_buffer
#define a2i__delete_buffer a2i__delete_buffer
#define a2i__scan_buffer a2i__scan_buffer
#define a2i__scan_string a2i__scan_string
#define a2i__scan_bytes a2i__scan_bytes
#define a2i__init_buffer a2i__init_buffer
#define a2i__flush_buffer a2i__flush_buffer
#define a2i__load_buffer_state a2i__load_buffer_state
#define a2i__switch_to_buffer a2i__switch_to_buffer
#define a2i_push_buffer_state a2i_push_buffer_state
#define a2i_pop_buffer_state a2i_pop_buffer_state
#define a2i_ensure_buffer_stack a2i_ensure_buffer_stack
#define a2i__flex_debug a2i__flex_debug
#define a2i_in a2i_in
#define a2i_leng a2i_leng
#define a2i_lex a2i_lex
#define a2i_lineno a2i_lineno
#define a2i_out a2i_out
#define a2i_restart a2i_restart
#define a2i_text a2i_text
#define a2i_wrap a2i_wrap
#define a2i_alloc a2i_alloc
#define a2i_realloc a2i_realloc
#define a2i_free a2i_free

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef a2i__create_buffer
#define a2i__create_buffer_ALREADY_DEFINED
#else
#define a2i__create_buffer a2i__create_buffer
#endif

#ifdef a2i__delete_buffer
#define a2i__delete_buffer_ALREADY_DEFINED
#else
#define a2i__delete_buffer a2i__delete_buffer
#endif

#ifdef a2i__scan_buffer
#define a2i__scan_buffer_ALREADY_DEFINED
#else
#define a2i__scan_buffer a2i__scan_buffer
#endif

#ifdef a2i__scan_string
#define a2i__scan_string_ALREADY_DEFINED
#else
#define a2i__scan_string a2i__scan_string
#endif

#ifdef a2i__scan_bytes
#define a2i__scan_bytes_ALREADY_DEFINED
#else
#define a2i__scan_bytes a2i__scan_bytes
#endif

#ifdef a2i__init_buffer
#define a2i__init_buffer_ALREADY_DEFINED
#else
#define a2i__init_buffer a2i__init_buffer
#endif

#ifdef a2i__flush_buffer
#define a2i__flush_buffer_ALREADY_DEFINED
#else
#define a2i__flush_buffer a2i__flush_buffer
#endif

#ifdef a2i__load_buffer_state
#define a2i__load_buffer_state_ALREADY_DEFINED
#else
#define a2i__load_buffer_state a2i__load_buffer_state
#endif

#ifdef a2i__switch_to_buffer
#define a2i__switch_to_buffer_ALREADY_DEFINED
#else
#define a2i__switch_to_buffer a2i__switch_to_buffer
#endif

#ifdef a2i_push_buffer_state
#define a2i_push_buffer_state_ALREADY_DEFINED
#else
#define a2i_push_buffer_state a2i_push_buffer_state
#endif

#ifdef a2i_pop_buffer_state
#define a2i_pop_buffer_state_ALREADY_DEFINED
#else
#define a2i_pop_buffer_state a2i_pop_buffer_state
#endif

#ifdef a2i_ensure_buffer_stack
#define a2i_ensure_buffer_stack_ALREADY_DEFINED
#else
#define a2i_ensure_buffer_stack a2i_ensure_buffer_stack
#endif

#ifdef a2i_lex
#define a2i_lex_ALREADY_DEFINED
#else
#define a2i_lex a2i_lex
#endif

#ifdef a2i_restart
#define a2i_restart_ALREADY_DEFINED
#else
#define a2i_restart a2i_restart
#endif

#ifdef a2i_lex_init
#define a2i_lex_init_ALREADY_DEFINED
#else
#define a2i_lex_init a2i_lex_init
#endif

#ifdef a2i_lex_init_extra
#define a2i_lex_init_extra_ALREADY_DEFINED
#else
#define a2i_lex_init_extra a2i_lex_init_extra
#endif

#ifdef a2i_lex_destroy
#define a2i_lex_destroy_ALREADY_DEFINED
#else
#define a2i_lex_destroy a2i_lex_destroy
#endif

#ifdef a2i_get_debug
#define a2i_get_debug_ALREADY_DEFINED
#else
#define a2i_get_debug a2i_get_debug
#endif

#ifdef a2i_set_debug
#define a2i_set_debug_ALREADY_DEFINED
#else
#define a2i_set_debug a2i_set_debug
#endif

#ifdef a2i_get_extra
#define a2i_get_extra_ALREADY_DEFINED
#else
#define a2i_get_extra a2i_get_extra
#endif

#ifdef a2i_set_extra
#define a2i_set_extra_ALREADY_DEFINED
#else
#define a2i_set_extra a2i_set_extra
#endif

#ifdef a2i_get_in
#define a2i_get_in_ALREADY_DEFINED
#else
#define a2i_get_in a2i_get_in
#endif

#ifdef a2i_set_in
#define a2i_set_in_ALREADY_DEFINED
#else
#define a2i_set_in a2i_set_in
#endif

#ifdef a2i_get_out
#define a2i_get_out_ALREADY_DEFINED
#else
#define a2i_get_out a2i_get_out
#endif

#ifdef a2i_set_out
#define a2i_set_out_ALREADY_DEFINED
#else
#define a2i_set_out a2i_set_out
#endif

#ifdef a2i_get_leng
#define a2i_get_leng_ALREADY_DEFINED
#else
#define a2i_get_leng a2i_get_leng
#endif

#ifdef a2i_get_text
#define a2i_get_text_ALREADY_DEFINED
#else
#define a2i_get_text a2i_get_text
#endif

#ifdef a2i_get_lineno
#define a2i_get_lineno_ALREADY_DEFINED
#else
#define a2i_get_lineno a2i_get_lineno
#endif

#ifdef a2i_set_lineno
#define a2i_set_lineno_ALREADY_DEFINED
#else
#define a2i_set_lineno a2i_set_lineno
#endif

#ifdef a2i_wrap
#define a2i_wrap_ALREADY_DEFINED
#else
#define a2i_wrap a2i_wrap
#endif

#ifdef a2i_get_lval
#define a2i_get_lval_ALREADY_DEFINED
#else
#define a2i_get_lval a2i_get_lval
#endif

#ifdef a2i_set_lval
#define a2i_set_lval_ALREADY_DEFINED
#else
#define a2i_set_lval a2i_set_lval
#endif

#ifdef a2i_alloc
#define a2i_alloc_ALREADY_DEFINED
#else
#define a2i_alloc a2i_alloc
#endif

#ifdef a2i_realloc
#define a2i_realloc_ALREADY_DEFINED
#else
#define a2i_realloc a2i_realloc
#endif

#ifdef a2i_free
#define a2i_free_ALREADY_DEFINED
#else
#define a2i_free a2i_free
#endif

#ifdef a2i_text
#define a2i_text_ALREADY_DEFINED
#else
#define a2i_text a2i_text
#endif

#ifdef a2i_leng
#define a2i_leng_ALREADY_DEFINED
#else
#define a2i_leng a2i_leng
#endif

#ifdef a2i_in
#define a2i_in_ALREADY_DEFINED
#else
#define a2i_in a2i_in
#endif

#ifdef a2i_out
#define a2i_out_ALREADY_DEFINED
#else
#define a2i_out a2i_out
#endif

#ifdef a2i__flex_debug
#define a2i__flex_debug_ALREADY_DEFINED
#else
#define a2i__flex_debug a2i__flex_debug
#endif

#ifdef a2i_lineno
#define a2i_lineno_ALREADY_DEFINED
#else
#define a2i_lineno a2i_lineno
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define a2i_const const

#if defined(__GNUC__) && __GNUC__ >= 3
#define a2i_noreturn __attribute__((__noreturn__))
#else
#define a2i_noreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (a2i__start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((a2i__start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE a2i_restart( a2i_in  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(a2i__state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct a2i__buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t a2i__size_t;
#endif

extern int a2i_leng;

extern FILE *a2i_in, *a2i_out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define a2i_less(n) \
	do \
		{ \
		/* Undo effects of setting up a2i_text. */ \
        int a2i_less_macro_arg = (n); \
        YY_LESS_LINENO(a2i_less_macro_arg);\
		*a2i__cp = (a2i__hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(a2i__c_buf_p) = a2i__cp = a2i__bp + a2i_less_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up a2i_text again */ \
		} \
	while ( 0 )
#define unput(c) a2i_unput( c, (a2i_text_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct a2i__buffer_state
	{
	FILE *a2i__input_file;

	char *a2i__ch_buf;		/* input buffer */
	char *a2i__buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int a2i__buf_size;

	/* Number of characters read into a2i__ch_buf, not including EOB
	 * characters.
	 */
	int a2i__n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int a2i__is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int a2i__is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int a2i__at_bol;

    int a2i__bs_lineno; /**< The line count. */
    int a2i__bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int a2i__fill_buffer;

	int a2i__buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via a2i_restart()), so that the user can continue scanning by
	 * just pointing a2i_in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t a2i__buffer_stack_top = 0; /**< index of top of stack. */
static size_t a2i__buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * a2i__buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (a2i__buffer_stack) \
                          ? (a2i__buffer_stack)[(a2i__buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (a2i__buffer_stack)[(a2i__buffer_stack_top)]

/* a2i__hold_char holds the character lost when a2i_text is formed. */
static char a2i__hold_char;
static int a2i__n_chars;		/* number of characters read into a2i__ch_buf */
int a2i_leng;

/* Points to current character in buffer. */
static char *a2i__c_buf_p = NULL;
static int a2i__init = 0;		/* whether we need to initialize */
static int a2i__start = 0;	/* start state number */

/* Flag which is used to allow a2i_wrap()'s to do buffer switches
 * instead of setting up a fresh a2i_in.  A bit of a hack ...
 */
static int a2i__did_buffer_switch_on_eof;

void a2i_restart ( FILE *input_file  );
void a2i__switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE a2i__create_buffer ( FILE *file, int size  );
void a2i__delete_buffer ( YY_BUFFER_STATE b  );
void a2i__flush_buffer ( YY_BUFFER_STATE b  );
void a2i_push_buffer_state ( YY_BUFFER_STATE new_buffer  );
void a2i_pop_buffer_state ( void );

static void a2i_ensure_buffer_stack ( void );
static void a2i__load_buffer_state ( void );
static void a2i__init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER a2i__flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE a2i__scan_buffer ( char *base, a2i__size_t size  );
YY_BUFFER_STATE a2i__scan_string ( const char *a2i__str  );
YY_BUFFER_STATE a2i__scan_bytes ( const char *bytes, int len  );

void *a2i_alloc ( a2i__size_t  );
void *a2i_realloc ( void *, a2i__size_t  );
void a2i_free ( void *  );

#define a2i__new_buffer a2i__create_buffer
#define a2i__set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        a2i_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            a2i__create_buffer( a2i_in, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->a2i__is_interactive = is_interactive; \
	}
#define a2i__set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        a2i_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            a2i__create_buffer( a2i_in, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->a2i__at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->a2i__at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *a2i_in = NULL, *a2i_out = NULL;

typedef int a2i__state_type;

extern int a2i_lineno;
int a2i_lineno = 1;

extern char *a2i_text;
#ifdef a2i_text_ptr
#undef a2i_text_ptr
#endif
#define a2i_text_ptr a2i_text

static a2i__state_type a2i__get_previous_state ( void );
static a2i__state_type a2i__try_NUL_trans ( a2i__state_type current_state  );
static int a2i__get_next_buffer ( void );
static void a2i_noreturn a2i__fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up a2i_text.
 */
#define YY_DO_BEFORE_ACTION \
	(a2i_text_ptr) = a2i__bp; \
	a2i_leng = (int) (a2i__cp - a2i__bp); \
	(a2i__hold_char) = *a2i__cp; \
	*a2i__cp = '\0'; \
	(a2i__c_buf_p) = a2i__cp;
#define YY_NUM_RULES 17
#define YY_END_OF_BUFFER 18
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct a2i__trans_info
	{
	flex_int32_t a2i__verify;
	flex_int32_t a2i__nxt;
	};
static const flex_int16_t a2i__accept[51] =
    {   0,
        0,    0,   18,   16,   15,   16,    8,    9,   12,   10,
       14,   11,    7,    6,   13,    6,    6,    6,    6,    0,
        7,    6,    6,    6,    6,    6,    0,    6,    2,    6,
        6,    0,    6,    6,    6,    0,    6,    4,    6,    0,
        6,    6,    0,    5,    6,    0,    3,    0,    1,    0
    } ;

static const YY_CHAR a2i__ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    1,    1,    1,    4,
        5,    6,    7,    8,    9,    1,    1,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,    1,    1,    1,
        1,    1,    1,    1,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
        1,   12,    1,    1,   13,    1,   11,   11,   14,   15,

       16,   17,   11,   18,   19,   11,   11,   20,   11,   11,
       11,   21,   11,   22,   23,   24,   25,   26,   11,   11,
       11,   11,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR a2i__meta[27] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    2,
        2,    1,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2
    } ;

static const flex_int16_t a2i__base[52] =
    {   0,
        0,    0,   58,   59,   59,   42,   59,   59,   59,   59,
       59,   59,   46,    0,   59,   35,   38,   33,   30,   32,
       40,    0,   24,   27,   22,   30,   23,   21,    0,   20,
       25,   25,   16,   21,   22,   23,   20,    0,   11,   10,
       11,   18,   12,    0,   12,    3,    0,   12,   59,   59,
       25
    } ;

static const flex_int16_t a2i__def[52] =
    {   0,
       50,    1,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   51,   50,   51,   51,   51,   51,   50,
       50,   51,   51,   51,   51,   51,   50,   51,   51,   51,
       51,   50,   51,   51,   51,   50,   51,   51,   51,   50,
       51,   51,   50,   51,   51,   50,   51,   50,   50,    0,
       50
    } ;

static const flex_int16_t a2i__nxt[86] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,    4,   16,   17,   14,   18,   14,   14,   14,
       19,   14,   14,   14,   14,   14,   22,   49,   48,   47,
       46,   45,   44,   43,   42,   41,   40,   39,   38,   37,
       36,   35,   34,   33,   32,   31,   30,   29,   28,   21,
       27,   26,   25,   24,   23,   21,   20,   50,    3,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50
    } ;

static const flex_int16_t a2i__chk[86] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,   51,   48,   46,   45,
       43,   42,   41,   40,   39,   37,   36,   35,   34,   33,
       32,   31,   30,   28,   27,   26,   25,   24,   23,   21,
       20,   19,   18,   17,   16,   13,    6,    3,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50
    } ;

static a2i__state_type a2i__last_accepting_state;
static char *a2i__last_accepting_cpos;

extern int a2i__flex_debug;
int a2i__flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define a2i_more() a2i_more_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *a2i_text;
#line 1 "lexDirectives.l"
#line 2 "lexDirectives.l"
#include <string.h>
#include <DirectivesInclude.h>
#include <yaccDirectives.h>

#define EOS     '\0'

extern char *a2i_DirectiveString;
#line 753 "lexDirectives.c"
#line 754 "lexDirectives.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int a2i__init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int a2i_lex_destroy ( void );

int a2i_get_debug ( void );

void a2i_set_debug ( int debug_flag  );

YY_EXTRA_TYPE a2i_get_extra ( void );

void a2i_set_extra ( YY_EXTRA_TYPE user_defined  );

FILE *a2i_get_in ( void );

void a2i_set_in  ( FILE * _in_str  );

FILE *a2i_get_out ( void );

void a2i_set_out  ( FILE * _out_str  );

			int a2i_get_leng ( void );

char *a2i_get_text ( void );

int a2i_get_lineno ( void );

void a2i_set_lineno ( int _line_number  );

YYSTYPE * a2i_get_lval ( void );

void a2i_set_lval ( YYSTYPE * a2i_lval_param  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int a2i_wrap ( void );
#else
extern int a2i_wrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void a2i_unput ( int c, char *buf_ptr  );
    
#endif

#ifndef a2i_text_ptr
static void a2i__flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int a2i__flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int a2i_input ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( a2i_text, (size_t) a2i_leng, 1, a2i_out )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->a2i__is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( a2i_in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( a2i_in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (a2i__size_t) max_size, a2i_in)) == 0 && ferror(a2i_in)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(a2i_in); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "a2i_terminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef a2i_terminate
#define a2i_terminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) a2i__fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int a2i_lex \
               (YYSTYPE * a2i_lval_param );

#define YY_DECL int a2i_lex \
               (YYSTYPE * a2i_lval_param )
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after a2i_text and a2i_leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	a2i__state_type a2i__current_state;
	char *a2i__cp, *a2i__bp;
	int a2i__act;
    
        YYSTYPE * a2i_lval;
    
    a2i_lval = a2i_lval_param;

	if ( !(a2i__init) )
		{
		(a2i__init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (a2i__start) )
			(a2i__start) = 1;	/* first start state */

		if ( ! a2i_in )
			a2i_in = stdin;

		if ( ! a2i_out )
			a2i_out = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			a2i_ensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				a2i__create_buffer( a2i_in, YY_BUF_SIZE );
		}

		a2i__load_buffer_state(  );
		}

	{
#line 11 "lexDirectives.l"


#line 984 "lexDirectives.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		a2i__cp = (a2i__c_buf_p);

		/* Support of a2i_text. */
		*a2i__cp = (a2i__hold_char);

		/* a2i__bp points to the position in a2i__ch_buf of the start of
		 * the current run.
		 */
		a2i__bp = a2i__cp;

		a2i__current_state = (a2i__start);
a2i__match:
		do
			{
			YY_CHAR a2i__c = a2i__ec[YY_SC_TO_UI(*a2i__cp)] ;
			if ( a2i__accept[a2i__current_state] )
				{
				(a2i__last_accepting_state) = a2i__current_state;
				(a2i__last_accepting_cpos) = a2i__cp;
				}
			while ( a2i__chk[a2i__base[a2i__current_state] + a2i__c] != a2i__current_state )
				{
				a2i__current_state = (int) a2i__def[a2i__current_state];
				if ( a2i__current_state >= 51 )
					a2i__c = a2i__meta[a2i__c];
				}
			a2i__current_state = a2i__nxt[a2i__base[a2i__current_state] + a2i__c];
			++a2i__cp;
			}
		while ( a2i__base[a2i__current_state] != 59 );

a2i__find_action:
		a2i__act = a2i__accept[a2i__current_state];
		if ( a2i__act == 0 )
			{ /* have to back up */
			a2i__cp = (a2i__last_accepting_cpos);
			a2i__current_state = (a2i__last_accepting_state);
			a2i__act = a2i__accept[a2i__current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( a2i__act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*a2i__cp = (a2i__hold_char);
			a2i__cp = (a2i__last_accepting_cpos);
			a2i__current_state = (a2i__last_accepting_state);
			goto a2i__find_action;

case 1:
YY_RULE_SETUP
#line 13 "lexDirectives.l"
return CDIR;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 15 "lexDirectives.l"
return DEP;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 17 "lexDirectives.l"
return PREFETCH;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 19 "lexDirectives.l"
return FLUSH;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 21 "lexDirectives.l"
return CLUSTER;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 23 "lexDirectives.l"
{
                              a2i_lval->cval = (char *)malloc(strlen((const char *)a2i_text) *
                                                           sizeof(char));
                              strcpy(a2i_lval->cval,(const char *)a2i_text);
                              return NAME;
                             }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 30 "lexDirectives.l"
{
                              a2i_lval->cval = (char *)malloc(strlen((const char *)a2i_text) *
                                                           sizeof(char));
                              strcpy(a2i_lval->cval,(const char *)a2i_text);
                              return ICONST;
                             }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 37 "lexDirectives.l"
return LPAR;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 39 "lexDirectives.l"
return RPAR;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 41 "lexDirectives.l"
return PLUS;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 43 "lexDirectives.l"
return MINUS;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 45 "lexDirectives.l"
return TIMES;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 47 "lexDirectives.l"
return DIVIDE;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 49 "lexDirectives.l"
return COMMA;
	YY_BREAK
case 15:
/* rule 15 can match eol */
#line 52 "lexDirectives.l"
case 16:
/* rule 16 can match eol */
YY_RULE_SETUP
#line 52 "lexDirectives.l"
;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 53 "lexDirectives.l"
ECHO;
	YY_BREAK
#line 1135 "lexDirectives.c"
case YY_STATE_EOF(INITIAL):
	a2i_terminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int a2i__amount_of_matched_text = (int) (a2i__cp - (a2i_text_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*a2i__cp = (a2i__hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->a2i__buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed a2i_in at a new source and called
			 * a2i_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(a2i__n_chars) = YY_CURRENT_BUFFER_LVALUE->a2i__n_chars;
			YY_CURRENT_BUFFER_LVALUE->a2i__input_file = a2i_in;
			YY_CURRENT_BUFFER_LVALUE->a2i__buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for a2i__c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since a2i__c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (a2i__c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->a2i__ch_buf[(a2i__n_chars)] )
			{ /* This was really a NUL. */
			a2i__state_type a2i__next_state;

			(a2i__c_buf_p) = (a2i_text_ptr) + a2i__amount_of_matched_text;

			a2i__current_state = a2i__get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * a2i__get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			a2i__next_state = a2i__try_NUL_trans( a2i__current_state );

			a2i__bp = (a2i_text_ptr) + YY_MORE_ADJ;

			if ( a2i__next_state )
				{
				/* Consume the NUL. */
				a2i__cp = ++(a2i__c_buf_p);
				a2i__current_state = a2i__next_state;
				goto a2i__match;
				}

			else
				{
				a2i__cp = (a2i__c_buf_p);
				goto a2i__find_action;
				}
			}

		else switch ( a2i__get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(a2i__did_buffer_switch_on_eof) = 0;

				if ( a2i_wrap(  ) )
					{
					/* Note: because we've taken care in
					 * a2i__get_next_buffer() to have set up
					 * a2i_text, we can now set up
					 * a2i__c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(a2i__c_buf_p) = (a2i_text_ptr) + YY_MORE_ADJ;

					a2i__act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (a2i__did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(a2i__c_buf_p) =
					(a2i_text_ptr) + a2i__amount_of_matched_text;

				a2i__current_state = a2i__get_previous_state(  );

				a2i__cp = (a2i__c_buf_p);
				a2i__bp = (a2i_text_ptr) + YY_MORE_ADJ;
				goto a2i__match;

			case EOB_ACT_LAST_MATCH:
				(a2i__c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->a2i__ch_buf[(a2i__n_chars)];

				a2i__current_state = a2i__get_previous_state(  );

				a2i__cp = (a2i__c_buf_p);
				a2i__bp = (a2i_text_ptr) + YY_MORE_ADJ;
				goto a2i__find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of a2i_lex */

/* a2i__get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int a2i__get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->a2i__ch_buf;
	char *source = (a2i_text_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (a2i__c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->a2i__ch_buf[(a2i__n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->a2i__fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (a2i__c_buf_p) - (a2i_text_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((a2i__c_buf_p) - (a2i_text_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->a2i__buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->a2i__n_chars = (a2i__n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->a2i__buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int a2i__c_buf_p_offset =
				(int) ((a2i__c_buf_p) - b->a2i__ch_buf);

			if ( b->a2i__is_our_buffer )
				{
				int new_size = b->a2i__buf_size * 2;

				if ( new_size <= 0 )
					b->a2i__buf_size += b->a2i__buf_size / 8;
				else
					b->a2i__buf_size *= 2;

				b->a2i__ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					a2i_realloc( (void *) b->a2i__ch_buf,
							 (a2i__size_t) (b->a2i__buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->a2i__ch_buf = NULL;

			if ( ! b->a2i__ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(a2i__c_buf_p) = &b->a2i__ch_buf[a2i__c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->a2i__buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->a2i__ch_buf[number_to_move]),
			(a2i__n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->a2i__n_chars = (a2i__n_chars);
		}

	if ( (a2i__n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			a2i_restart( a2i_in  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->a2i__buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((a2i__n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->a2i__buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (a2i__n_chars) + number_to_move + ((a2i__n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->a2i__ch_buf = (char *) a2i_realloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->a2i__ch_buf, (a2i__size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->a2i__ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in a2i__get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->a2i__buf_size = (int) (new_size - 2);
	}

	(a2i__n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->a2i__ch_buf[(a2i__n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->a2i__ch_buf[(a2i__n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(a2i_text_ptr) = &YY_CURRENT_BUFFER_LVALUE->a2i__ch_buf[0];

	return ret_val;
}

/* a2i__get_previous_state - get the state just before the EOB char was reached */

    static a2i__state_type a2i__get_previous_state (void)
{
	a2i__state_type a2i__current_state;
	char *a2i__cp;
    
	a2i__current_state = (a2i__start);

	for ( a2i__cp = (a2i_text_ptr) + YY_MORE_ADJ; a2i__cp < (a2i__c_buf_p); ++a2i__cp )
		{
		YY_CHAR a2i__c = (*a2i__cp ? a2i__ec[YY_SC_TO_UI(*a2i__cp)] : 1);
		if ( a2i__accept[a2i__current_state] )
			{
			(a2i__last_accepting_state) = a2i__current_state;
			(a2i__last_accepting_cpos) = a2i__cp;
			}
		while ( a2i__chk[a2i__base[a2i__current_state] + a2i__c] != a2i__current_state )
			{
			a2i__current_state = (int) a2i__def[a2i__current_state];
			if ( a2i__current_state >= 51 )
				a2i__c = a2i__meta[a2i__c];
			}
		a2i__current_state = a2i__nxt[a2i__base[a2i__current_state] + a2i__c];
		}

	return a2i__current_state;
}

/* a2i__try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = a2i__try_NUL_trans( current_state );
 */
    static a2i__state_type a2i__try_NUL_trans  (a2i__state_type a2i__current_state )
{
	int a2i__is_jam;
    	char *a2i__cp = (a2i__c_buf_p);

	YY_CHAR a2i__c = 1;
	if ( a2i__accept[a2i__current_state] )
		{
		(a2i__last_accepting_state) = a2i__current_state;
		(a2i__last_accepting_cpos) = a2i__cp;
		}
	while ( a2i__chk[a2i__base[a2i__current_state] + a2i__c] != a2i__current_state )
		{
		a2i__current_state = (int) a2i__def[a2i__current_state];
		if ( a2i__current_state >= 51 )
			a2i__c = a2i__meta[a2i__c];
		}
	a2i__current_state = a2i__nxt[a2i__base[a2i__current_state] + a2i__c];
	a2i__is_jam = (a2i__current_state == 50);

		return a2i__is_jam ? 0 : a2i__current_state;
}

#ifndef YY_NO_UNPUT

    static void a2i_unput (int c, char * a2i__bp )
{
	char *a2i__cp;
    
    a2i__cp = (a2i__c_buf_p);

	/* undo effects of setting up a2i_text */
	*a2i__cp = (a2i__hold_char);

	if ( a2i__cp < YY_CURRENT_BUFFER_LVALUE->a2i__ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (a2i__n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->a2i__ch_buf[
					YY_CURRENT_BUFFER_LVALUE->a2i__buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->a2i__ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->a2i__ch_buf )
			*--dest = *--source;

		a2i__cp += (int) (dest - source);
		a2i__bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->a2i__n_chars =
			(a2i__n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->a2i__buf_size;

		if ( a2i__cp < YY_CURRENT_BUFFER_LVALUE->a2i__ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--a2i__cp = (char) c;

	(a2i_text_ptr) = a2i__bp;
	(a2i__hold_char) = *a2i__cp;
	(a2i__c_buf_p) = a2i__cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int a2i_input (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(a2i__c_buf_p) = (a2i__hold_char);

	if ( *(a2i__c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* a2i__c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (a2i__c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->a2i__ch_buf[(a2i__n_chars)] )
			/* This was really a NUL. */
			*(a2i__c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((a2i__c_buf_p) - (a2i_text_ptr));
			++(a2i__c_buf_p);

			switch ( a2i__get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because a2i__g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					a2i_restart( a2i_in );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( a2i_wrap(  ) )
						return 0;

					if ( ! (a2i__did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return a2i_input();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(a2i__c_buf_p) = (a2i_text_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (a2i__c_buf_p);	/* cast for 8-bit char's */
	*(a2i__c_buf_p) = '\0';	/* preserve a2i_text */
	(a2i__hold_char) = *++(a2i__c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void a2i_restart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        a2i_ensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            a2i__create_buffer( a2i_in, YY_BUF_SIZE );
	}

	a2i__init_buffer( YY_CURRENT_BUFFER, input_file );
	a2i__load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void a2i__switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		a2i_pop_buffer_state();
	 *		a2i_push_buffer_state(new_buffer);
     */
	a2i_ensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(a2i__c_buf_p) = (a2i__hold_char);
		YY_CURRENT_BUFFER_LVALUE->a2i__buf_pos = (a2i__c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->a2i__n_chars = (a2i__n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	a2i__load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (a2i_wrap()) processing, but the only time this flag
	 * is looked at is after a2i_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(a2i__did_buffer_switch_on_eof) = 1;
}

static void a2i__load_buffer_state  (void)
{
    	(a2i__n_chars) = YY_CURRENT_BUFFER_LVALUE->a2i__n_chars;
	(a2i_text_ptr) = (a2i__c_buf_p) = YY_CURRENT_BUFFER_LVALUE->a2i__buf_pos;
	a2i_in = YY_CURRENT_BUFFER_LVALUE->a2i__input_file;
	(a2i__hold_char) = *(a2i__c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE a2i__create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) a2i_alloc( sizeof( struct a2i__buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in a2i__create_buffer()" );

	b->a2i__buf_size = size;

	/* a2i__ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->a2i__ch_buf = (char *) a2i_alloc( (a2i__size_t) (b->a2i__buf_size + 2)  );
	if ( ! b->a2i__ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in a2i__create_buffer()" );

	b->a2i__is_our_buffer = 1;

	a2i__init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with a2i__create_buffer()
 * 
 */
    void a2i__delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->a2i__is_our_buffer )
		a2i_free( (void *) b->a2i__ch_buf  );

	a2i_free( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a a2i_restart() or at EOF.
 */
    static void a2i__init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	a2i__flush_buffer( b );

	b->a2i__input_file = file;
	b->a2i__fill_buffer = 1;

    /* If b is the current buffer, then a2i__init_buffer was _probably_
     * called from a2i_restart() or through a2i__get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->a2i__bs_lineno = 1;
        b->a2i__bs_column = 0;
    }

        b->a2i__is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void a2i__flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->a2i__n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->a2i__ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->a2i__ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->a2i__buf_pos = &b->a2i__ch_buf[0];

	b->a2i__at_bol = 1;
	b->a2i__buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		a2i__load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void a2i_push_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	a2i_ensure_buffer_stack();

	/* This block is copied from a2i__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(a2i__c_buf_p) = (a2i__hold_char);
		YY_CURRENT_BUFFER_LVALUE->a2i__buf_pos = (a2i__c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->a2i__n_chars = (a2i__n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(a2i__buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from a2i__switch_to_buffer. */
	a2i__load_buffer_state(  );
	(a2i__did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void a2i_pop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	a2i__delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((a2i__buffer_stack_top) > 0)
		--(a2i__buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		a2i__load_buffer_state(  );
		(a2i__did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void a2i_ensure_buffer_stack (void)
{
	a2i__size_t num_to_alloc;
    
	if (!(a2i__buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(a2i__buffer_stack) = (struct a2i__buffer_state**)a2i_alloc
								(num_to_alloc * sizeof(struct a2i__buffer_state*)
								);
		if ( ! (a2i__buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in a2i_ensure_buffer_stack()" );

		memset((a2i__buffer_stack), 0, num_to_alloc * sizeof(struct a2i__buffer_state*));

		(a2i__buffer_stack_max) = num_to_alloc;
		(a2i__buffer_stack_top) = 0;
		return;
	}

	if ((a2i__buffer_stack_top) >= ((a2i__buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		a2i__size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (a2i__buffer_stack_max) + grow_size;
		(a2i__buffer_stack) = (struct a2i__buffer_state**)a2i_realloc
								((a2i__buffer_stack),
								num_to_alloc * sizeof(struct a2i__buffer_state*)
								);
		if ( ! (a2i__buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in a2i_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((a2i__buffer_stack) + (a2i__buffer_stack_max), 0, grow_size * sizeof(struct a2i__buffer_state*));
		(a2i__buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE a2i__scan_buffer  (char * base, a2i__size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) a2i_alloc( sizeof( struct a2i__buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in a2i__scan_buffer()" );

	b->a2i__buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->a2i__buf_pos = b->a2i__ch_buf = base;
	b->a2i__is_our_buffer = 0;
	b->a2i__input_file = NULL;
	b->a2i__n_chars = b->a2i__buf_size;
	b->a2i__is_interactive = 0;
	b->a2i__at_bol = 1;
	b->a2i__fill_buffer = 0;
	b->a2i__buffer_status = YY_BUFFER_NEW;

	a2i__switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to a2i_lex() will
 * scan from a @e copy of @a str.
 * @param a2i_str a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       a2i__scan_bytes() instead.
 */
YY_BUFFER_STATE a2i__scan_string (const char * a2i_str )
{
    
	return a2i__scan_bytes( a2i_str, (int) strlen(a2i_str) );
}

/** Setup the input buffer state to scan the given bytes. The next call to a2i_lex() will
 * scan from a @e copy of @a bytes.
 * @param a2i_bytes the byte buffer to scan
 * @param _a2i_bytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE a2i__scan_bytes  (const char * a2i_bytes, int  _a2i_bytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	a2i__size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (a2i__size_t) (_a2i_bytes_len + 2);
	buf = (char *) a2i_alloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in a2i__scan_bytes()" );

	for ( i = 0; i < _a2i_bytes_len; ++i )
		buf[i] = a2i_bytes[i];

	buf[_a2i_bytes_len] = buf[_a2i_bytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = a2i__scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in a2i__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->a2i__is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void a2i_noreturn a2i__fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine a2i_less() so it works in section 3 code. */

#undef a2i_less
#define a2i_less(n) \
	do \
		{ \
		/* Undo effects of setting up a2i_text. */ \
        int a2i_less_macro_arg = (n); \
        YY_LESS_LINENO(a2i_less_macro_arg);\
		a2i_text[a2i_leng] = (a2i__hold_char); \
		(a2i__c_buf_p) = a2i_text + a2i_less_macro_arg; \
		(a2i__hold_char) = *(a2i__c_buf_p); \
		*(a2i__c_buf_p) = '\0'; \
		a2i_leng = a2i_less_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int a2i_get_lineno  (void)
{
    
    return a2i_lineno;
}

/** Get the input stream.
 * 
 */
FILE *a2i_get_in  (void)
{
        return a2i_in;
}

/** Get the output stream.
 * 
 */
FILE *a2i_get_out  (void)
{
        return a2i_out;
}

/** Get the length of the current token.
 * 
 */
int a2i_get_leng  (void)
{
        return a2i_leng;
}

/** Get the current token.
 * 
 */

char *a2i_get_text  (void)
{
        return a2i_text;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void a2i_set_lineno (int  _line_number )
{
    
    a2i_lineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see a2i__switch_to_buffer
 */
void a2i_set_in (FILE *  _in_str )
{
        a2i_in = _in_str ;
}

void a2i_set_out (FILE *  _out_str )
{
        a2i_out = _out_str ;
}

int a2i_get_debug  (void)
{
        return a2i__flex_debug;
}

void a2i_set_debug (int  _bdebug )
{
        a2i__flex_debug = _bdebug ;
}

static int a2i__init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from a2i_lex_destroy(), so don't allocate here.
     */

    (a2i__buffer_stack) = NULL;
    (a2i__buffer_stack_top) = 0;
    (a2i__buffer_stack_max) = 0;
    (a2i__c_buf_p) = NULL;
    (a2i__init) = 0;
    (a2i__start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    a2i_in = stdin;
    a2i_out = stdout;
#else
    a2i_in = NULL;
    a2i_out = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * a2i_lex_init()
     */
    return 0;
}

/* a2i_lex_destroy is for both reentrant and non-reentrant scanners. */
int a2i_lex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		a2i__delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		a2i_pop_buffer_state();
	}

	/* Destroy the stack itself. */
	a2i_free((a2i__buffer_stack) );
	(a2i__buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * a2i_lex() is called, initialization will occur. */
    a2i__init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef a2i_text_ptr
static void a2i__flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int a2i__flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *a2i_alloc (a2i__size_t  size )
{
			return malloc(size);
}

void *a2i_realloc  (void * ptr, a2i__size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void a2i_free (void * ptr )
{
			free( (char *) ptr );	/* see a2i_realloc() for (char *) cast */
}

#define YYTABLES_NAME "a2i_tables"

#line 53 "lexDirectives.l"


int a2i_wrap() {
    return 1;
}

