# $Id: Makefile,v 1.1 1997/03/11 14:34:07 carr Exp $

HERE = libs/graphicInterface/oldMonitor/monitor/sms/scroll_sm
VERSIONS = monX
SRCS	= scroll_sm.ansi.c
ARCHIVE_monX = ../../monX-$(DSYSTEM_OS)-g.a

include Makeinclude
