# $Id: Makefile,v 1.2 1997/06/25 14:59:20 carr Exp $

HERE = libs/graphicInterface/oldMonitor/monitor/sms/scroll_sm
VERSIONS = monX
SRCS	= scroll_sm.C
ARCHIVE_monX = ../../monX-$(DSYSTEM_OS)-g.a

include Makeinclude
