# $Id: Makefile,v 1.1 1997/03/11 14:29:50 carr Exp $

HERE = libs/frontEnd/fortTree

SRCS = \
	   ConstExprEval.ansi.c \
	   TypeChecker.ansi.c \
	   fortsym.ansi.c \
	   FortDProblem.C \
	   FortTree.C \
	   FortTreeNeedProv.C \
	   InitInfo.C \
	   LocalModRef.C \
	   StmtFunc.C \
	   fortsymEq.C 

ARCHIVE	= ../FrontEnd-$(DSYSTEM_OS)-g.a

include Makeinclude
