# $Id: Makefile,v 1.2 1997/06/24 17:53:08 carr Exp $

HERE = libs/frontEnd/fortTree

SRCS = \
	   ConstExprEval.C \
	   TypeChecker.C \
	   fortsym.C \
	   FortDProblem.C \
	   FortTree.C \
	   FortTreeNeedProv.C \
	   InitInfo.C \
	   LocalModRef.C \
	   StmtFunc.C \
	   fortsymEq.C 

ARCHIVE	= ../FrontEnd-$(DSYSTEM_OS)-g.a

include ../../../make.config

include $(DEPENDS)

# DO NOT DELETE THIS LINE -- make depend depends on it.