# $Id: Makefile,v 1.2 1997/06/25 14:57:52 carr Exp $

HERE = libs/graphicInterface/oldMonitor/monitor/sms/list_sm
VERSIONS = monX
SRCS	= list.C
ARCHIVE_monX = ../../monX-$(DSYSTEM_OS)-g.a

include Makeinclude
