# $Id: Makefile,v 1.1 1997/03/11 14:34:01 carr Exp $

HERE = libs/graphicInterface/oldMonitor/monitor/sms/list_sm
VERSIONS = monX
SRCS	= list.ansi.c
ARCHIVE_monX = ../../monX-$(DSYSTEM_OS)-g.a

include Makeinclude
