# $Id: Makefile,v 1.2 1997/03/27 20:47:09 carr Exp $

HERE = libs/moduleAnalysis/valNum

	   #val_ht.C 
	   #val_simplify.C
SRCS = \
	   valentry.C \
	   val_arith.C \
	   val_dep.C \
	   val_iter.C \
	   val_pass.C \
	   val_range.C \
	   val_ip.C \
	   values.C \
	   val_lookup.C

ARCHIVE	= ModuleAnalysis-$(DSYSTEM_OS)-g.a

include Makeinclude
