# $Id: Makefile,v 1.1 1997/03/11 14:36:16 carr Exp $

HERE = libs/moduleAnalysis/valNum

SRCS = \
	   valentry.C \
	   val_arith.C \
	   val_dep.C \
	   val_ht.C \
	   val_iter.C \
	   val_pass.C \
       val_simplify.C \
	   val_range.C \
	   val_ip.C \
	   values.C \
	   val_lookup.C

ARCHIVE	= ModuleAnalysis-$(DSYSTEM_OS)-g.a

include Makeinclude
