# $Id: Makefile,v 1.1 1997/03/11 14:30:15 carr Exp $

HERE = libs/graphicInterface/cmdProcs/dEditor/dep

SRCS = \
	   DepEditor.C \
	   DepFilterDef.C

ARCHIVE = ../DEditorCP-$(DSYSTEM_OS)-g.a

include Makeinclude