# $Id: Makefile,v 1.1 1997/03/11 14:36:24 carr Exp $

HERE = libs/support

DIRS = \
	   annotation \
	   arrays \
	   database \
	   file \
	   graphs \
	   iterators \
	   lists \
	   memMgmt \
	   misc \
	   msgHandlers \
	   numerical \
	   optParsing \
	   patternMatch \
	   queues \
	   registry \
	   sets \
	   sorts \
	   stacks \
	   strings \
	   tables \
	   time \
	   trees \
	   vectors

ARCHIVE = Support-$(DSYSTEM_OS)-g.a

include Makeinclude
