# $Id: Makefile,v 1.2 1997/06/25 14:38:24 carr Exp $

HERE = libs/graphicInterface/cmdProcs/paraScopeEditor/dp


SRCS = \
	   ali_d.C \
	   align_d.C \
	   distrib_d.C \
	   dtype_d.C \
	   edge_d.C \
	   fusion_d.C \
	   loop_d.C \
	   peel_d.C \
	   perf_d.C \
	   rename_d.C \
	   sexpand_d.C \
	   shared_d.C \
	   skew_d.C \
	   split_d.C \
	   sreplace_d.C \
	   statement_d.C \
	   strip_d.C \
	   trans_menu.C \
	   unroll_d.C

ARCHIVE	= ped-$(DSYSTEM_OS)-g.a

include Makeinclude
