# $Id: Makefile,v 1.1 1997/03/11 14:31:02 carr Exp $

HERE = libs/graphicInterface/cmdProcs/paraScopeEditor/dp


SRCS = \
	   ali_d.ansi.c \
	   align_d.ansi.c \
	   distrib_d.ansi.c \
	   dtype_d.ansi.c \
	   edge_d.ansi.c \
	   fusion_d.ansi.c \
	   loop_d.ansi.c \
	   peel_d.ansi.c \
	   perf_d.ansi.c \
	   rename_d.ansi.c \
	   sexpand_d.ansi.c \
	   shared_d.ansi.c \
	   skew_d.ansi.c \
	   split_d.ansi.c \
	   sreplace_d.ansi.c \
	   statement_d.ansi.c \
	   strip_d.ansi.c \
	   trans_menu.ansi.c \
	   unroll_d.ansi.c

ARCHIVE	= ped-$(DSYSTEM_OS)-g.a

include Makeinclude
