# $Id: Makefile,v 1.1 1997/06/02 19:41:26 carr Exp $

HERE = libs/graphicInterface/support/graphics

SRCS = \
	   point.ansi.c \
	   rect.ansi.c \
	   rect_list.ansi.c

ARCHIVE = ../Support-$(DSYSTEM_OS)-g.a

include Makeinclude
