# $Id: Makefile,v 1.2 1997/06/25 15:02:25 carr Exp $

HERE = libs/graphicInterface/support/graphics

SRCS = \
	   point.C \
	   rect.C \
	   rect_list.C

ARCHIVE = ../Support-$(DSYSTEM_OS)-g.a

include Makeinclude
