# $Id: Makefile,v 1.2 1997/03/27 20:41:14 carr Exp $

HERE = libs/ipAnalysis/problems/fortD

	   #FortDProcInterface.C 
	   #ReachAnnot.C 
	   #ReachAnnotMgrs.C
	   #ReachAnnotString.C 
	   #ReachDFProblem.C 
	   #ReadReachAnnot.C 
	   #OverlapAnnot.C 
	   #OverlapAnnotMgrs.C 
	   #OverlapBackwardDFProblem.C 
	   #OverlapForwardDFProblem.C 
	   #WriteReachAnnot.C
SRCS = \
	   CommonBlockAnnot.C \
	   CommonBlockMgrsAnnot.C \
	   FortDLocalAnnot.C \
	   FortDNumProcsAnnot.C 

ARCHIVE = IPAnalysis-$(DSYSTEM_OS)-g.a

include Makeinclude
