# $Id: Makefile,v 1.1 1997/03/11 14:34:59 carr Exp $

HERE = libs/ipAnalysis/problems/fortD

SRCS = \
	   CommonBlockAnnot.C \
	   CommonBlockMgrsAnnot.C \
	   FortDLocalAnnot.C \
	   FortDNumProcsAnnot.C \
	   FortDProcInterface.C \
	   ReachAnnot.C \
	   ReachAnnotMgrs.C \
	   ReachAnnotString.C \
	   ReachDFProblem.C \
	   ReadReachAnnot.C \
	   OverlapAnnot.C \
	   OverlapAnnotMgrs.C \
	   OverlapBackwardDFProblem.C \
	   OverlapForwardDFProblem.C \
	   WriteReachAnnot.C

ARCHIVE = IPAnalysis-$(DSYSTEM_OS)-g.a

include Makeinclude
