# $Id: Makefile,v 1.3 1997/03/27 21:10:30 carr Exp $

HERE = libs/ipAnalysis/problems/fortD

SRCS = \
	   FortDProcInterface.C \
	   ReachAnnot.C \
	   ReachAnnotMgrs.C\
	   ReachAnnotString.C \
	   ReachDFProblem.C \
	   ReadReachAnnot.C \
	   OverlapAnnot.C \
	   OverlapAnnotMgrs.C \
	   OverlapBackwardDFProblem.C \
	   OverlapForwardDFProblem.C \
	   WriteReachAnnot.C\
	   CommonBlockAnnot.C \
	   CommonBlockMgrsAnnot.C \
	   FortDLocalAnnot.C \
	   FortDNumProcsAnnot.C 

ARCHIVE = IPAnalysis-$(DSYSTEM_OS)-g.a

include ../../../../make.config

include $(DEPENDS)

# DO NOT DELETE THIS LINE -- make depend depends on it.