# $Id: Makefile,v 1.1 1997/03/11 14:35:59 carr Exp $

HERE = libs/moduleAnalysis/dependence/interface

SRCS = DependenceInfo.C

ARCHIVE	= ../ModuleAnalysis-$(DSYSTEM_OS)-g.a

include ../../../../make.config

include $(DEPENDS)

# DO NOT DELETE THIS LINE -- make depend depends on it.
