# $Id: Makefile,v 1.3 1997/03/27 21:03:08 carr Exp $

HERE = libs/fortD/irregAnalysis

SRCS = \
	  AST_Graph.C \
	  AST_SSA_Graph.C \
	  CommDFProblem.C \
	  CommDFUniv.C \
	  Exec.C \
	  Inspec.C \
	  IntervDFProb.C \
	  IrrGlobals.C \
	  IrrSymTab.C \
	  Mall.C \
	  OnHomeTable.C \
	  S_desc.C \
	  Slice.C \
	  Slice2.C \
	  ValDecomp.C \
	  analyse.C \
	  code_gen.C \
	  fd_ssa.C \
	  irr_msgs.C

ARCHIVE	= ../FortD-$(DSYSTEM_OS)-g.a


include ../../../make.config

include $(DEPENDS)

# DO NOT DELETE THIS LINE -- make depend depends on it.
