# $Id: Makefile,v 1.1 1997/03/11 14:28:05 carr Exp $

HERE = libs/fileAttrMgmt/module

SRCS = \
	   Module.C \
	   ModuleProcsIterator.C \
	   NeedProvModAttr.C \
	   ProcSummariesModAttr.C

ARCHIVE = FileAttrMgmt-$(DSYSTEM_OS)-g.a

include ../../../make.config

include $(DEPENDS)

# DO NOT DELETE THIS LINE -- make depend depends on it.
