# $Id: Makefile,v 1.1 1997/03/11 14:34:42 carr Exp $

HERE = libs/ipAnalysis/ipInfo

SRCS = \
	   CallSite.C \
	   CallSiteLocalInfo.C \
	   CallSitesLocalInfo.C \
	   EntryPoints.C \
	   EqClassPairs.C \
	   FormalParameters.C \
	   ModuleLocalInfo.C \
	   OffsetLength.C \
	   ParameterList.C \
	   ProcFortDInfo.C \
	   ProcLocalInfo.C \
	   ProcScalarModRefInfo.C \
	   ProcSummary.C \
	   VariableSet.C \
	   ionudtree.C \
	   iptree.C

ARCHIVE	= IPAnalysis-$(DSYSTEM_OS)-g.a

include ../../../make.config

include $(DEPENDS)

# DO NOT DELETE THIS LINE -- make depend depends on it.
