# $Id: Makefile,v 1.1 1997/03/11 14:33:26 carr Exp $

HERE = libs/graphicInterface/oldMonitor/monitor

VERSIONS = monX monN

# X windows version
DIRS_monX = \
	        dialogs \
	        items \
			keyboard \
	        mon \
	        sms

ARCHIVE_monX = monX-$(DSYSTEM_OS)-g.a


# command line version
DIRS_monN = \
			keyboard \
	        mon

ARCHIVE_monN = monN-$(DSYSTEM_OS)-g.a


include Makeinclude
