# $Id: Makefile,v 1.1 1997/03/11 14:30:47 carr Exp $

HERE = libs/graphicInterface/cmdProcs/newEditor/fortAnnot

SRCS = \
	   AnnotLink.C \
	   Contents.C \
	   Declarations.C \
	   FortAnnot.C \
	   FortAnnotMgr.C \
	   FortAnnotSrc.C \
	   InterProc.C \
	   Loops.C

ARCHIVE = ../NewEditorCP-$(DSYSTEM_OS)-g.a

include Makeinclude