# $Id: Makefile,v 1.1 1997/03/11 14:36:31 carr Exp $

HERE = libs/support/arrays

SRCS = \
	   ExtendingArray.ansi.c \
	   ExtensibleArray.ansi.c \
	   FlexibleArray.ansi.c \
	   ResizableArray.C

ARCHIVE = ../Support-$(DSYSTEM_OS)-g.a

include Makeinclude
