# $Id: Makefile,v 1.2 1997/06/25 15:13:37 carr Exp $

HERE = libs/support/arrays

SRCS = \
	   ExtendingArray.C \
	   ExtensibleArray.C \
	   FlexibleArray.C \
	   ResizableArray.C

ARCHIVE = ../Support-$(DSYSTEM_OS)-g.a

include ../../../make.config

include $(DEPENDS)

# DO NOT DELETE THIS LINE -- make depend depends on it.