# $Id: Makefile,v 1.1 1997/03/11 14:33:57 carr Exp $

HERE = libs/graphicInterface/oldMonitor/monitor/sms/function_sm
VERSIONS = monX
SRCS	= function_sm.ansi.c
ARCHIVE_monX = ../../monX-$(DSYSTEM_OS)-g.a

include Makeinclude
