# $Id: Makefile,v 1.2 1997/03/27 20:50:40 carr Exp $

HERE = libs/support/misc

	   #dict.C 
SRCS = \
	   IdGenerator.C \
	   general.ansi.c \
	   port.C \
	   putenv2.ansi.c

ARCHIVE = ../Support-$(DSYSTEM_OS)-g.a

include Makeinclude
