# $Id: Makefile,v 1.3 1997/03/27 21:08:33 carr Exp $

HERE = libs/support/misc

SRCS = \
	   dict.C \
	   IdGenerator.C \
	   general.ansi.c \
	   port.C \
	   putenv2.ansi.c

ARCHIVE = ../Support-$(DSYSTEM_OS)-g.a

include Makeinclude
