# $Id: Makefile,v 1.1 1997/03/11 14:36:55 carr Exp $

HERE = libs/support/misc

SRCS = \
	   IdGenerator.C \
	   dict.C \
	   general.ansi.c \
	   port.C \
	   putenv2.ansi.c

ARCHIVE = ../Support-$(DSYSTEM_OS)-g.a

include Makeinclude
