# $Id: Makefile,v 1.3 1997/04/09 17:06:20 carr Exp $

HERE = execs/f2i

SRCS = f2i.C f2i_options.C 

ARCHIVE	= F2i-$(DSYSTEM_OS)-g.a

EXEC	= f2i-$(DSYSTEM_OS)-g

DSYSTEM_LIBS = $(NLIBS)

LOCAL_LIBS = -lm  -ll

include Makeinclude
