# $Id: Makefile,v 1.2 1997/03/27 20:15:16 carr Exp $

HERE = execs/f2i

SRCS = f2i.C f2i_options.C 

ARCHIVE	= F2i-$(DSYSTEM_OS)-g.a

EXEC	= f2i-$(DSYSTEM_OS)

DSYSTEM_LIBS = $(NLIBS)

LOCAL_LIBS = -lm  -ll

include Makeinclude
