# $Id: Makefile,v 1.1 1997/03/11 14:33:30 carr Exp $

HERE = libs/graphicInterface/oldMonitor/monitor/items

VERSIONS = monX

SRCS = \
	   button.ansi.c \
	   check_box.ansi.c \
	   integer.ansi.c \
	   lazy_table_sm.ansi.c \
	   list_item.ansi.c \
	   radio_btns.ansi.c \
	   regex.ansi.c \
	   table2.ansi.c \
	   text_item.ansi.c \
	   title.ansi.c

ARCHIVE_monX = ../monX-$(DSYSTEM_OS)-g.a

include Makeinclude
