# $Id: Makefile,v 1.2 1997/06/25 14:48:15 carr Exp $

HERE = libs/graphicInterface/oldMonitor/monitor/items

VERSIONS = monX

SRCS = \
	   button.C \
	   check_box.C \
	   integer.C \
	   lazy_table_sm.C \
	   list_item.C \
	   radio_btns.C \
	   regex.C \
	   table2.C \
	   text_item.C \
	   title.C

ARCHIVE_monX = ../monX-$(DSYSTEM_OS)-g.a

include Makeinclude
