# $Id: Makefile,v 1.1 1997/03/11 14:35:07 carr Exp $

HERE = libs/ipAnalysis/problems/modRef

SRCS =	\
	    ScalarModRefAnnot.C \
	    ScalarModRefMgrsAnnot.C \
	    ScalarModRefDFProblem.C \
        ScalarModRefQuery.C 

ARCHIVE = ../IPAnalysis-$(DSYSTEM_OS)-g.a

include ../../../../make.config

include $(DEPENDS)

# DO NOT DELETE THIS LINE -- make depend depends on it.