# $Id: Makefile,v 1.1 1997/03/11 14:30:13 carr Exp $

HERE = libs/graphicInterface/cmdProcs/dEditor/comm

SRCS = \
	   CommEditor.C \
	   CommFilterDef.C

ARCHIVE = ../DEditorCP-$(DSYSTEM_OS)-g.a

include Makeinclude