BEGIN {
	print "/* This include file is generated by a bogus awk script... */"
	print "/* Try regenerating it with 'awk -f astcons.awk nodedef.def' */"
	print ""
	print "#ifndef astcons_h"
	print "#define astcons_h"
	print ""
      }
/struct/{
	next
	}
/"/{
        name = substr($1,2,length($1)-2)
	prefix = name
        printf ("#define gen_%s(", prefix)
        if ($5 == 0) printf (")   \\\n\tgen_node(GEN_%s)\n",prefix)
        if ($5 == 1) printf ("a)   \\\n\tgen_node(GEN_%s,a)\n",prefix)
        if ($5 == 2) printf ("a,b)   \\\n\tgen_node(GEN_%s,a,b)\n",prefix)
        if ($5 == 3) printf ("a,b,c)   \\\n\tgen_node(GEN_%s,a,b,c)\n",prefix)
        if ($5 == 4) printf ("a,b,c,d)   \\\n\tgen_node(GEN_%s,a,b,c,d)\n",prefix)
        if ($5 == 5) printf ("a,b,c,d,e)   \\\n\tgen_node(GEN_%s,a,b,c,d,e)\n",prefix)
        if ($5 == 6) printf ("a,b,c,d,e,f)   \\\n\tgen_node(GEN_%s,a,b,c,d,e,f)\n",prefix)

	count++
	next
      }
/\/\*/{
	next
      }
/{/{
       next
      }
/}/{
       next
      }
END   {
	print ""
	print "#endif"
      }
