/* This include file is generated by a bogus awk script... */
/* Try regenerating it with 'awk -f astmeta.awk nodedef.def' */

#ifndef astmeta_h
#define astmeta_h

#define GEN_arg 0
#define GEN_any 1
#define GEN_array_decl_len 2
#define GEN_bound 3
#define GEN_len 4
#define GEN_common_elt 5
#define GEN_common_vars 6
#define GEN_constant 7
#define GEN_loop_control 8
#define GEN_data_init 9
#define GEN_data 10
#define GEN_dim 11
#define GEN_equiv 12
#define GEN_formal 13
#define GEN_format 14
#define GEN_guard 15
#define GEN_implicit_def 16
#define GEN_letters 17
#define GEN_init 18
#define GEN_invocation 19
#define GEN_kwd 20
#define GEN_specify_kwd 21
#define GEN_query_kwd 22
#define GEN_lbl_def 23
#define GEN_lbl_ref 24
#define GEN_letter 25
#define GEN_var 26
#define GEN_name 27
#define GEN_option 28
#define GEN_parallel_case 29
#define GEN_param_def 30
#define GEN_posting 31
#define GEN_post_expr 32
#define GEN_expr 33
#define GEN_arith_expr 34
#define GEN_string_expr 35
#define GEN_relational_expr 36
#define GEN_logical_expr 37
#define GEN_stmt 38
#define GEN_specification_stmt 39
#define GEN_control_stmt 40
#define GEN_io_stmt 41
#define GEN_parascope_stmt 42
#define GEN_debug_stmt 43
#define GEN_fort90_stmt 44
#define GEN_subprogram 45
#define GEN_string_var 46
#define GEN_text 47
#define GEN_type_name 48
#define GEN_type 49
#define GEN_unit 50
#define GEN_alloc_object 51
#define GEN_META_LAST 52

#endif
