/* This include file is generated by a bogus awk script... */
/* Try regenerating it with 'awk -f astsel.awk nodedef.def' */

#ifndef astsel_h
#define astsel_h

#define ERROR_complaint 1
#define gen_ERROR_get_complaint(n) ast_get_son_n(n,1)
#define gen_ERROR_put_complaint(n,v) ast_put_son_n(n,1,v)

#define ERROR_tree 2
#define gen_ERROR_get_tree(n) ast_get_son_n(n,2)
#define gen_ERROR_put_tree(n,v) ast_put_son_n(n,2,v)

#define ERROR_part0 3
#define gen_ERROR_get_part0(n) ast_get_son_n(n,3)
#define gen_ERROR_put_part0(n,v) ast_put_son_n(n,3,v)

#define ERROR_part1 4
#define gen_ERROR_get_part1(n) ast_get_son_n(n,4)
#define gen_ERROR_put_part1(n,v) ast_put_son_n(n,4,v)

#define ERROR_part2 5
#define gen_ERROR_get_part2(n) ast_get_son_n(n,5)
#define gen_ERROR_put_part2(n,v) ast_put_son_n(n,5,v)

#define ERROR_part3 6
#define gen_ERROR_get_part3(n) ast_get_son_n(n,6)
#define gen_ERROR_put_part3(n,v) ast_put_son_n(n,6,v)

#define GLOBAL_subprogram_scope_LIST 1
#define gen_GLOBAL_get_subprogram_scope_LIST(n) ast_get_son_n(n,1)
#define gen_GLOBAL_put_subprogram_scope_LIST(n,v) ast_put_son_n(n,1,v)

#define FUNCTION_lbl_def 1
#define gen_FUNCTION_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_FUNCTION_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define FUNCTION_close_lbl_def 2
#define gen_FUNCTION_get_close_lbl_def(n) ast_get_son_n(n,2)
#define gen_FUNCTION_put_close_lbl_def(n,v) ast_put_son_n(n,2,v)

#define FUNCTION_type_len 3
#define gen_FUNCTION_get_type_len(n) ast_get_son_n(n,3)
#define gen_FUNCTION_put_type_len(n,v) ast_put_son_n(n,3,v)

#define FUNCTION_name 4
#define gen_FUNCTION_get_name(n) ast_get_son_n(n,4)
#define gen_FUNCTION_put_name(n,v) ast_put_son_n(n,4,v)

#define FUNCTION_formal_arg_LIST 5
#define gen_FUNCTION_get_formal_arg_LIST(n) ast_get_son_n(n,5)
#define gen_FUNCTION_put_formal_arg_LIST(n,v) ast_put_son_n(n,5,v)

#define FUNCTION_stmt_LIST 6
#define gen_FUNCTION_get_stmt_LIST(n) ast_get_son_n(n,6)
#define gen_FUNCTION_put_stmt_LIST(n,v) ast_put_son_n(n,6,v)

#define PROGRAM_lbl_def 1
#define gen_PROGRAM_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_PROGRAM_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define PROGRAM_close_lbl_def 2
#define gen_PROGRAM_get_close_lbl_def(n) ast_get_son_n(n,2)
#define gen_PROGRAM_put_close_lbl_def(n,v) ast_put_son_n(n,2,v)

#define PROGRAM_name 3
#define gen_PROGRAM_get_name(n) ast_get_son_n(n,3)
#define gen_PROGRAM_put_name(n,v) ast_put_son_n(n,3,v)

#define PROGRAM_stmt_LIST 4
#define gen_PROGRAM_get_stmt_LIST(n) ast_get_son_n(n,4)
#define gen_PROGRAM_put_stmt_LIST(n,v) ast_put_son_n(n,4,v)

#define SUBROUTINE_lbl_def 1
#define gen_SUBROUTINE_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_SUBROUTINE_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define SUBROUTINE_close_lbl_def 2
#define gen_SUBROUTINE_get_close_lbl_def(n) ast_get_son_n(n,2)
#define gen_SUBROUTINE_put_close_lbl_def(n,v) ast_put_son_n(n,2,v)

#define SUBROUTINE_name 3
#define gen_SUBROUTINE_get_name(n) ast_get_son_n(n,3)
#define gen_SUBROUTINE_put_name(n,v) ast_put_son_n(n,3,v)

#define SUBROUTINE_formal_arg_LIST 4
#define gen_SUBROUTINE_get_formal_arg_LIST(n) ast_get_son_n(n,4)
#define gen_SUBROUTINE_put_formal_arg_LIST(n,v) ast_put_son_n(n,4,v)

#define SUBROUTINE_stmt_LIST 5
#define gen_SUBROUTINE_get_stmt_LIST(n) ast_get_son_n(n,5)
#define gen_SUBROUTINE_put_stmt_LIST(n,v) ast_put_son_n(n,5,v)

#define BLOCK_DATA_lbl_def 1
#define gen_BLOCK_DATA_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_BLOCK_DATA_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define BLOCK_DATA_close_lbl_def 2
#define gen_BLOCK_DATA_get_close_lbl_def(n) ast_get_son_n(n,2)
#define gen_BLOCK_DATA_put_close_lbl_def(n,v) ast_put_son_n(n,2,v)

#define BLOCK_DATA_name 3
#define gen_BLOCK_DATA_get_name(n) ast_get_son_n(n,3)
#define gen_BLOCK_DATA_put_name(n,v) ast_put_son_n(n,3,v)

#define BLOCK_DATA_stmt_LIST 4
#define gen_BLOCK_DATA_get_stmt_LIST(n) ast_get_son_n(n,4)
#define gen_BLOCK_DATA_put_stmt_LIST(n,v) ast_put_son_n(n,4,v)

#define COMMON_lbl_def 1
#define gen_COMMON_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_COMMON_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define COMMON_common_elt_LIST 2
#define gen_COMMON_get_common_elt_LIST(n) ast_get_son_n(n,2)
#define gen_COMMON_put_common_elt_LIST(n,v) ast_put_son_n(n,2,v)

#define COMMON_ELT_name 1
#define gen_COMMON_ELT_get_name(n) ast_get_son_n(n,1)
#define gen_COMMON_ELT_put_name(n,v) ast_put_son_n(n,1,v)

#define COMMON_ELT_common_vars_LIST 2
#define gen_COMMON_ELT_get_common_vars_LIST(n) ast_get_son_n(n,2)
#define gen_COMMON_ELT_put_common_vars_LIST(n,v) ast_put_son_n(n,2,v)

#define DIMENSION_lbl_def 1
#define gen_DIMENSION_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_DIMENSION_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define DIMENSION_array_decl_len_LIST 2
#define gen_DIMENSION_get_array_decl_len_LIST(n) ast_get_son_n(n,2)
#define gen_DIMENSION_put_array_decl_len_LIST(n,v) ast_put_son_n(n,2,v)

#define EQUIVALENCE_lbl_def 1
#define gen_EQUIVALENCE_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_EQUIVALENCE_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define EQUIVALENCE_equiv_elt_LIST 2
#define gen_EQUIVALENCE_get_equiv_elt_LIST(n) ast_get_son_n(n,2)
#define gen_EQUIVALENCE_put_equiv_elt_LIST(n,v) ast_put_son_n(n,2,v)

#define EQUIV_ELT_lvalue_LIST 1
#define gen_EQUIV_ELT_get_lvalue_LIST(n) ast_get_son_n(n,1)
#define gen_EQUIV_ELT_put_lvalue_LIST(n,v) ast_put_son_n(n,1,v)

#define TYPE_STATEMENT_lbl_def 1
#define gen_TYPE_STATEMENT_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_TYPE_STATEMENT_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define TYPE_STATEMENT_type_len 2
#define gen_TYPE_STATEMENT_get_type_len(n) ast_get_son_n(n,2)
#define gen_TYPE_STATEMENT_put_type_len(n,v) ast_put_son_n(n,2,v)

#define TYPE_STATEMENT_array_decl_len_LIST 3
#define gen_TYPE_STATEMENT_get_array_decl_len_LIST(n) ast_get_son_n(n,3)
#define gen_TYPE_STATEMENT_put_array_decl_len_LIST(n,v) ast_put_son_n(n,3,v)

#define ARRAY_DECL_LEN_name 1
#define gen_ARRAY_DECL_LEN_get_name(n) ast_get_son_n(n,1)
#define gen_ARRAY_DECL_LEN_put_name(n,v) ast_put_son_n(n,1,v)

#define ARRAY_DECL_LEN_len 2
#define gen_ARRAY_DECL_LEN_get_len(n) ast_get_son_n(n,2)
#define gen_ARRAY_DECL_LEN_put_len(n,v) ast_put_son_n(n,2,v)

#define ARRAY_DECL_LEN_dim_LIST 3
#define gen_ARRAY_DECL_LEN_get_dim_LIST(n) ast_get_son_n(n,3)
#define gen_ARRAY_DECL_LEN_put_dim_LIST(n,v) ast_put_son_n(n,3,v)

#define ARRAY_DECL_LEN_init_LIST 4
#define gen_ARRAY_DECL_LEN_get_init_LIST(n) ast_get_son_n(n,4)
#define gen_ARRAY_DECL_LEN_put_init_LIST(n,v) ast_put_son_n(n,4,v)

#define EXTERNAL_lbl_def 1
#define gen_EXTERNAL_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_EXTERNAL_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define EXTERNAL_name_LIST 2
#define gen_EXTERNAL_get_name_LIST(n) ast_get_son_n(n,2)
#define gen_EXTERNAL_put_name_LIST(n,v) ast_put_son_n(n,2,v)

#define IMPLICIT_lbl_def 1
#define gen_IMPLICIT_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_IMPLICIT_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define IMPLICIT_implicit_elt_LIST 2
#define gen_IMPLICIT_get_implicit_elt_LIST(n) ast_get_son_n(n,2)
#define gen_IMPLICIT_put_implicit_elt_LIST(n,v) ast_put_son_n(n,2,v)

#define IMPLICIT_ELT_type_len 1
#define gen_IMPLICIT_ELT_get_type_len(n) ast_get_son_n(n,1)
#define gen_IMPLICIT_ELT_put_type_len(n,v) ast_put_son_n(n,1,v)

#define IMPLICIT_ELT_implicit_refs_LIST 2
#define gen_IMPLICIT_ELT_get_implicit_refs_LIST(n) ast_get_son_n(n,2)
#define gen_IMPLICIT_ELT_put_implicit_refs_LIST(n,v) ast_put_son_n(n,2,v)

#define IMPLICIT_PAIR_start 1
#define gen_IMPLICIT_PAIR_get_start(n) ast_get_son_n(n,1)
#define gen_IMPLICIT_PAIR_put_start(n,v) ast_put_son_n(n,1,v)

#define IMPLICIT_PAIR_end 2
#define gen_IMPLICIT_PAIR_get_end(n) ast_get_son_n(n,2)
#define gen_IMPLICIT_PAIR_put_end(n,v) ast_put_son_n(n,2,v)

#define INTRINSIC_lbl_def 1
#define gen_INTRINSIC_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_INTRINSIC_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define INTRINSIC_name_LIST 2
#define gen_INTRINSIC_get_name_LIST(n) ast_get_son_n(n,2)
#define gen_INTRINSIC_put_name_LIST(n,v) ast_put_son_n(n,2,v)

#define PARAMETER_lbl_def 1
#define gen_PARAMETER_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_PARAMETER_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define PARAMETER_param_elt_LIST 2
#define gen_PARAMETER_get_param_elt_LIST(n) ast_get_son_n(n,2)
#define gen_PARAMETER_put_param_elt_LIST(n,v) ast_put_son_n(n,2,v)

#define PARAM_ELT_name 1
#define gen_PARAM_ELT_get_name(n) ast_get_son_n(n,1)
#define gen_PARAM_ELT_put_name(n,v) ast_put_son_n(n,1,v)

#define PARAM_ELT_rvalue 2
#define gen_PARAM_ELT_get_rvalue(n) ast_get_son_n(n,2)
#define gen_PARAM_ELT_put_rvalue(n,v) ast_put_son_n(n,2,v)

#define SAVE_lbl_def 1
#define gen_SAVE_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_SAVE_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define SAVE_name_LIST 2
#define gen_SAVE_get_name_LIST(n) ast_get_son_n(n,2)
#define gen_SAVE_put_name_LIST(n,v) ast_put_son_n(n,2,v)

#define COMMENT_text 1
#define gen_COMMENT_get_text(n) ast_get_son_n(n,1)
#define gen_COMMENT_put_text(n,v) ast_put_son_n(n,1,v)

#define ENTRY_lbl_def 1
#define gen_ENTRY_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_ENTRY_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define ENTRY_name 2
#define gen_ENTRY_get_name(n) ast_get_son_n(n,2)
#define gen_ENTRY_put_name(n,v) ast_put_son_n(n,2,v)

#define ENTRY_formal_arg_LIST 3
#define gen_ENTRY_get_formal_arg_LIST(n) ast_get_son_n(n,3)
#define gen_ENTRY_put_formal_arg_LIST(n,v) ast_put_son_n(n,3,v)

#define DATA_lbl_def 1
#define gen_DATA_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_DATA_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define DATA_data_elt_LIST 2
#define gen_DATA_get_data_elt_LIST(n) ast_get_son_n(n,2)
#define gen_DATA_put_data_elt_LIST(n,v) ast_put_son_n(n,2,v)

#define IMPLIED_DO_imp_elt_LIST 1
#define gen_IMPLIED_DO_get_imp_elt_LIST(n) ast_get_son_n(n,1)
#define gen_IMPLIED_DO_put_imp_elt_LIST(n,v) ast_put_son_n(n,1,v)

#define IMPLIED_DO_name 2
#define gen_IMPLIED_DO_get_name(n) ast_get_son_n(n,2)
#define gen_IMPLIED_DO_put_name(n,v) ast_put_son_n(n,2,v)

#define IMPLIED_DO_rvalue1 3
#define gen_IMPLIED_DO_get_rvalue1(n) ast_get_son_n(n,3)
#define gen_IMPLIED_DO_put_rvalue1(n,v) ast_put_son_n(n,3,v)

#define IMPLIED_DO_rvalue2 4
#define gen_IMPLIED_DO_get_rvalue2(n) ast_get_son_n(n,4)
#define gen_IMPLIED_DO_put_rvalue2(n,v) ast_put_son_n(n,4,v)

#define IMPLIED_DO_rvalue3 5
#define gen_IMPLIED_DO_get_rvalue3(n) ast_get_son_n(n,5)
#define gen_IMPLIED_DO_put_rvalue3(n,v) ast_put_son_n(n,5,v)

#define DATA_ELT_data_vars_LIST 1
#define gen_DATA_ELT_get_data_vars_LIST(n) ast_get_son_n(n,1)
#define gen_DATA_ELT_put_data_vars_LIST(n,v) ast_put_son_n(n,1,v)

#define DATA_ELT_init_LIST 2
#define gen_DATA_ELT_get_init_LIST(n) ast_get_son_n(n,2)
#define gen_DATA_ELT_put_init_LIST(n,v) ast_put_son_n(n,2,v)

#define STMT_FUNCTION_lbl_def 1
#define gen_STMT_FUNCTION_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_STMT_FUNCTION_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define STMT_FUNCTION_name 2
#define gen_STMT_FUNCTION_get_name(n) ast_get_son_n(n,2)
#define gen_STMT_FUNCTION_put_name(n,v) ast_put_son_n(n,2,v)

#define STMT_FUNCTION_formal_arg_LIST 3
#define gen_STMT_FUNCTION_get_formal_arg_LIST(n) ast_get_son_n(n,3)
#define gen_STMT_FUNCTION_put_formal_arg_LIST(n,v) ast_put_son_n(n,3,v)

#define STMT_FUNCTION_rvalue 4
#define gen_STMT_FUNCTION_get_rvalue(n) ast_get_son_n(n,4)
#define gen_STMT_FUNCTION_put_rvalue(n,v) ast_put_son_n(n,4,v)

#define FORMAT_lbl_def 1
#define gen_FORMAT_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_FORMAT_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define FORMAT_text 2
#define gen_FORMAT_get_text(n) ast_get_son_n(n,2)
#define gen_FORMAT_put_text(n,v) ast_put_son_n(n,2,v)

#define ASSIGN_lbl_def 1
#define gen_ASSIGN_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_ASSIGN_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define ASSIGN_lbl_ref 2
#define gen_ASSIGN_get_lbl_ref(n) ast_get_son_n(n,2)
#define gen_ASSIGN_put_lbl_ref(n,v) ast_put_son_n(n,2,v)

#define ASSIGN_name 3
#define gen_ASSIGN_get_name(n) ast_get_son_n(n,3)
#define gen_ASSIGN_put_name(n,v) ast_put_son_n(n,3,v)

#define ASSIGNMENT_lbl_def 1
#define gen_ASSIGNMENT_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_ASSIGNMENT_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define ASSIGNMENT_lvalue 2
#define gen_ASSIGNMENT_get_lvalue(n) ast_get_son_n(n,2)
#define gen_ASSIGNMENT_put_lvalue(n,v) ast_put_son_n(n,2,v)

#define ASSIGNMENT_rvalue 3
#define gen_ASSIGNMENT_get_rvalue(n) ast_get_son_n(n,3)
#define gen_ASSIGNMENT_put_rvalue(n,v) ast_put_son_n(n,3,v)

#define BACKSPACE_SHORT_lbl_def 1
#define gen_BACKSPACE_SHORT_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_BACKSPACE_SHORT_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define BACKSPACE_SHORT_unit_identifier 2
#define gen_BACKSPACE_SHORT_get_unit_identifier(n) ast_get_son_n(n,2)
#define gen_BACKSPACE_SHORT_put_unit_identifier(n,v) ast_put_son_n(n,2,v)

#define BACKSPACE_LONG_lbl_def 1
#define gen_BACKSPACE_LONG_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_BACKSPACE_LONG_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define BACKSPACE_LONG_kwd_LIST 2
#define gen_BACKSPACE_LONG_get_kwd_LIST(n) ast_get_son_n(n,2)
#define gen_BACKSPACE_LONG_put_kwd_LIST(n,v) ast_put_son_n(n,2,v)

#define CALL_lbl_def 1
#define gen_CALL_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_CALL_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define CALL_invocation 2
#define gen_CALL_get_invocation(n) ast_get_son_n(n,2)
#define gen_CALL_put_invocation(n,v) ast_put_son_n(n,2,v)

#define CLOSE_lbl_def 1
#define gen_CLOSE_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_CLOSE_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define CLOSE_kwd_LIST 2
#define gen_CLOSE_get_kwd_LIST(n) ast_get_son_n(n,2)
#define gen_CLOSE_put_kwd_LIST(n,v) ast_put_son_n(n,2,v)

#define CONTINUE_lbl_def 1
#define gen_CONTINUE_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_CONTINUE_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define DO_lbl_def 1
#define gen_DO_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_DO_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define DO_close_lbl_def 2
#define gen_DO_get_close_lbl_def(n) ast_get_son_n(n,2)
#define gen_DO_put_close_lbl_def(n,v) ast_put_son_n(n,2,v)

#define DO_lbl_ref 3
#define gen_DO_get_lbl_ref(n) ast_get_son_n(n,3)
#define gen_DO_put_lbl_ref(n,v) ast_put_son_n(n,3,v)

#define DO_control 4
#define gen_DO_get_control(n) ast_get_son_n(n,4)
#define gen_DO_put_control(n,v) ast_put_son_n(n,4,v)

#define DO_stmt_LIST 5
#define gen_DO_get_stmt_LIST(n) ast_get_son_n(n,5)
#define gen_DO_put_stmt_LIST(n,v) ast_put_son_n(n,5,v)

#define ENDFILE_SHORT_lbl_def 1
#define gen_ENDFILE_SHORT_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_ENDFILE_SHORT_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define ENDFILE_SHORT_unit_identifier 2
#define gen_ENDFILE_SHORT_get_unit_identifier(n) ast_get_son_n(n,2)
#define gen_ENDFILE_SHORT_put_unit_identifier(n,v) ast_put_son_n(n,2,v)

#define ENDFILE_LONG_lbl_def 1
#define gen_ENDFILE_LONG_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_ENDFILE_LONG_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define ENDFILE_LONG_kwd_LIST 2
#define gen_ENDFILE_LONG_get_kwd_LIST(n) ast_get_son_n(n,2)
#define gen_ENDFILE_LONG_put_kwd_LIST(n,v) ast_put_son_n(n,2,v)

#define ASSIGNED_GOTO_lbl_def 1
#define gen_ASSIGNED_GOTO_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_ASSIGNED_GOTO_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define ASSIGNED_GOTO_name 2
#define gen_ASSIGNED_GOTO_get_name(n) ast_get_son_n(n,2)
#define gen_ASSIGNED_GOTO_put_name(n,v) ast_put_son_n(n,2,v)

#define ASSIGNED_GOTO_lbl_ref_LIST 3
#define gen_ASSIGNED_GOTO_get_lbl_ref_LIST(n) ast_get_son_n(n,3)
#define gen_ASSIGNED_GOTO_put_lbl_ref_LIST(n,v) ast_put_son_n(n,3,v)

#define COMPUTED_GOTO_lbl_def 1
#define gen_COMPUTED_GOTO_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_COMPUTED_GOTO_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define COMPUTED_GOTO_lbl_ref_LIST 2
#define gen_COMPUTED_GOTO_get_lbl_ref_LIST(n) ast_get_son_n(n,2)
#define gen_COMPUTED_GOTO_put_lbl_ref_LIST(n,v) ast_put_son_n(n,2,v)

#define COMPUTED_GOTO_rvalue 3
#define gen_COMPUTED_GOTO_get_rvalue(n) ast_get_son_n(n,3)
#define gen_COMPUTED_GOTO_put_rvalue(n,v) ast_put_son_n(n,3,v)

#define GOTO_lbl_def 1
#define gen_GOTO_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_GOTO_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define GOTO_lbl_ref 2
#define gen_GOTO_get_lbl_ref(n) ast_get_son_n(n,2)
#define gen_GOTO_put_lbl_ref(n,v) ast_put_son_n(n,2,v)

#define ARITHMETIC_IF_lbl_def 1
#define gen_ARITHMETIC_IF_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_ARITHMETIC_IF_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define ARITHMETIC_IF_rvalue 2
#define gen_ARITHMETIC_IF_get_rvalue(n) ast_get_son_n(n,2)
#define gen_ARITHMETIC_IF_put_rvalue(n,v) ast_put_son_n(n,2,v)

#define ARITHMETIC_IF_lbl_ref1 3
#define gen_ARITHMETIC_IF_get_lbl_ref1(n) ast_get_son_n(n,3)
#define gen_ARITHMETIC_IF_put_lbl_ref1(n,v) ast_put_son_n(n,3,v)

#define ARITHMETIC_IF_lbl_ref2 4
#define gen_ARITHMETIC_IF_get_lbl_ref2(n) ast_get_son_n(n,4)
#define gen_ARITHMETIC_IF_put_lbl_ref2(n,v) ast_put_son_n(n,4,v)

#define ARITHMETIC_IF_lbl_ref3 5
#define gen_ARITHMETIC_IF_get_lbl_ref3(n) ast_get_son_n(n,5)
#define gen_ARITHMETIC_IF_put_lbl_ref3(n,v) ast_put_son_n(n,5,v)

#define IF_lbl_def 1
#define gen_IF_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_IF_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define IF_close_lbl_def 2
#define gen_IF_get_close_lbl_def(n) ast_get_son_n(n,2)
#define gen_IF_put_close_lbl_def(n,v) ast_put_son_n(n,2,v)

#define IF_guard_LIST 3
#define gen_IF_get_guard_LIST(n) ast_get_son_n(n,3)
#define gen_IF_put_guard_LIST(n,v) ast_put_son_n(n,3,v)

#define LOGICAL_IF_lbl_def 1
#define gen_LOGICAL_IF_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_LOGICAL_IF_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define LOGICAL_IF_rvalue 2
#define gen_LOGICAL_IF_get_rvalue(n) ast_get_son_n(n,2)
#define gen_LOGICAL_IF_put_rvalue(n,v) ast_put_son_n(n,2,v)

#define LOGICAL_IF_stmt_LIST 3
#define gen_LOGICAL_IF_get_stmt_LIST(n) ast_get_son_n(n,3)
#define gen_LOGICAL_IF_put_stmt_LIST(n,v) ast_put_son_n(n,3,v)

#define GUARD_lbl_def 1
#define gen_GUARD_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_GUARD_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define GUARD_rvalue 2
#define gen_GUARD_get_rvalue(n) ast_get_son_n(n,2)
#define gen_GUARD_put_rvalue(n,v) ast_put_son_n(n,2,v)

#define GUARD_stmt_LIST 3
#define gen_GUARD_get_stmt_LIST(n) ast_get_son_n(n,3)
#define gen_GUARD_put_stmt_LIST(n,v) ast_put_son_n(n,3,v)

#define INQUIRE_lbl_def 1
#define gen_INQUIRE_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_INQUIRE_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define INQUIRE_kwd_LIST 2
#define gen_INQUIRE_get_kwd_LIST(n) ast_get_son_n(n,2)
#define gen_INQUIRE_put_kwd_LIST(n,v) ast_put_son_n(n,2,v)

#define OPEN_lbl_def 1
#define gen_OPEN_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_OPEN_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define OPEN_kwd_LIST 2
#define gen_OPEN_get_kwd_LIST(n) ast_get_son_n(n,2)
#define gen_OPEN_put_kwd_LIST(n,v) ast_put_son_n(n,2,v)

#define PAUSE_lbl_def 1
#define gen_PAUSE_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_PAUSE_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define PAUSE_constant 2
#define gen_PAUSE_get_constant(n) ast_get_son_n(n,2)
#define gen_PAUSE_put_constant(n,v) ast_put_son_n(n,2,v)

#define PRINT_lbl_def 1
#define gen_PRINT_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_PRINT_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define PRINT_format_identifier 2
#define gen_PRINT_get_format_identifier(n) ast_get_son_n(n,2)
#define gen_PRINT_put_format_identifier(n,v) ast_put_son_n(n,2,v)

#define PRINT_data_vars_LIST 3
#define gen_PRINT_get_data_vars_LIST(n) ast_get_son_n(n,3)
#define gen_PRINT_put_data_vars_LIST(n,v) ast_put_son_n(n,3,v)

#define READ_SHORT_lbl_def 1
#define gen_READ_SHORT_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_READ_SHORT_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define READ_SHORT_format_identifier 2
#define gen_READ_SHORT_get_format_identifier(n) ast_get_son_n(n,2)
#define gen_READ_SHORT_put_format_identifier(n,v) ast_put_son_n(n,2,v)

#define READ_SHORT_data_vars_LIST 3
#define gen_READ_SHORT_get_data_vars_LIST(n) ast_get_son_n(n,3)
#define gen_READ_SHORT_put_data_vars_LIST(n,v) ast_put_son_n(n,3,v)

#define READ_LONG_lbl_def 1
#define gen_READ_LONG_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_READ_LONG_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define READ_LONG_kwd_LIST 2
#define gen_READ_LONG_get_kwd_LIST(n) ast_get_son_n(n,2)
#define gen_READ_LONG_put_kwd_LIST(n,v) ast_put_son_n(n,2,v)

#define READ_LONG_io_LIST 3
#define gen_READ_LONG_get_io_LIST(n) ast_get_son_n(n,3)
#define gen_READ_LONG_put_io_LIST(n,v) ast_put_son_n(n,3,v)

#define RETURN_lbl_def 1
#define gen_RETURN_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_RETURN_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define RETURN_rvalue 2
#define gen_RETURN_get_rvalue(n) ast_get_son_n(n,2)
#define gen_RETURN_put_rvalue(n,v) ast_put_son_n(n,2,v)

#define REWIND_SHORT_lbl_def 1
#define gen_REWIND_SHORT_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_REWIND_SHORT_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define REWIND_SHORT_unit_identifier 2
#define gen_REWIND_SHORT_get_unit_identifier(n) ast_get_son_n(n,2)
#define gen_REWIND_SHORT_put_unit_identifier(n,v) ast_put_son_n(n,2,v)

#define REWIND_LONG_lbl_def 1
#define gen_REWIND_LONG_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_REWIND_LONG_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define REWIND_LONG_kwd_LIST 2
#define gen_REWIND_LONG_get_kwd_LIST(n) ast_get_son_n(n,2)
#define gen_REWIND_LONG_put_kwd_LIST(n,v) ast_put_son_n(n,2,v)

#define STOP_lbl_def 1
#define gen_STOP_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_STOP_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define STOP_constant 2
#define gen_STOP_get_constant(n) ast_get_son_n(n,2)
#define gen_STOP_put_constant(n,v) ast_put_son_n(n,2,v)

#define WRITE_lbl_def 1
#define gen_WRITE_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_WRITE_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define WRITE_kwd_LIST 2
#define gen_WRITE_get_kwd_LIST(n) ast_get_son_n(n,2)
#define gen_WRITE_put_kwd_LIST(n,v) ast_put_son_n(n,2,v)

#define WRITE_data_vars_LIST 3
#define gen_WRITE_get_data_vars_LIST(n) ast_get_son_n(n,3)
#define gen_WRITE_put_data_vars_LIST(n,v) ast_put_son_n(n,3,v)

#define AT_lbl_def 1
#define gen_AT_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_AT_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define AT_lbl_ref 2
#define gen_AT_get_lbl_ref(n) ast_get_son_n(n,2)
#define gen_AT_put_lbl_ref(n,v) ast_put_son_n(n,2,v)

#define DEBUG_lbl_def 1
#define gen_DEBUG_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_DEBUG_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define DEBUG_close_lbl_def 2
#define gen_DEBUG_get_close_lbl_def(n) ast_get_son_n(n,2)
#define gen_DEBUG_put_close_lbl_def(n,v) ast_put_son_n(n,2,v)

#define DEBUG_option_LIST 3
#define gen_DEBUG_get_option_LIST(n) ast_get_son_n(n,3)
#define gen_DEBUG_put_option_LIST(n,v) ast_put_son_n(n,3,v)

#define DEBUG_stmt_LIST 4
#define gen_DEBUG_get_stmt_LIST(n) ast_get_son_n(n,4)
#define gen_DEBUG_put_stmt_LIST(n,v) ast_put_son_n(n,4,v)

#define TRACEON_lbl_def 1
#define gen_TRACEON_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_TRACEON_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define TRACEOFF_lbl_def 1
#define gen_TRACEOFF_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_TRACEOFF_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define UNIT_unit_num 1
#define gen_UNIT_get_unit_num(n) ast_get_son_n(n,1)
#define gen_UNIT_put_unit_num(n,v) ast_put_son_n(n,1,v)

#define SUBCHK_array_LIST 1
#define gen_SUBCHK_get_array_LIST(n) ast_get_son_n(n,1)
#define gen_SUBCHK_put_array_LIST(n,v) ast_put_son_n(n,1,v)

#define INIT_var_LIST 1
#define gen_INIT_get_var_LIST(n) ast_get_son_n(n,1)
#define gen_INIT_put_var_LIST(n,v) ast_put_son_n(n,1,v)

#define TASK_lbl_def 1
#define gen_TASK_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_TASK_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define TASK_invocation 2
#define gen_TASK_get_invocation(n) ast_get_son_n(n,2)
#define gen_TASK_put_invocation(n,v) ast_put_son_n(n,2,v)

#define TASK_lvalue 3
#define gen_TASK_get_lvalue(n) ast_get_son_n(n,3)
#define gen_TASK_put_lvalue(n,v) ast_put_son_n(n,3,v)

#define VALUE_PARAMETER_rvalue 1
#define gen_VALUE_PARAMETER_get_rvalue(n) ast_get_son_n(n,1)
#define gen_VALUE_PARAMETER_put_rvalue(n,v) ast_put_son_n(n,1,v)

#define PARALLEL_lbl_def 1
#define gen_PARALLEL_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_PARALLEL_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define PARALLEL_close_lbl_def 2
#define gen_PARALLEL_get_close_lbl_def(n) ast_get_son_n(n,2)
#define gen_PARALLEL_put_close_lbl_def(n,v) ast_put_son_n(n,2,v)

#define PARALLEL_lvalue 3
#define gen_PARALLEL_get_lvalue(n) ast_get_son_n(n,3)
#define gen_PARALLEL_put_lvalue(n,v) ast_put_son_n(n,3,v)

#define PARALLEL_rvalue 4
#define gen_PARALLEL_get_rvalue(n) ast_get_son_n(n,4)
#define gen_PARALLEL_put_rvalue(n,v) ast_put_son_n(n,4,v)

#define PARALLEL_stmt_LIST 5
#define gen_PARALLEL_get_stmt_LIST(n) ast_get_son_n(n,5)
#define gen_PARALLEL_put_stmt_LIST(n,v) ast_put_son_n(n,5,v)

#define PARALLEL_parallel_case_LIST 6
#define gen_PARALLEL_get_parallel_case_LIST(n) ast_get_son_n(n,6)
#define gen_PARALLEL_put_parallel_case_LIST(n,v) ast_put_son_n(n,6,v)

#define PARALLEL_CASE_lbl_def 1
#define gen_PARALLEL_CASE_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_PARALLEL_CASE_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define PARALLEL_CASE_rvalue_LIST 2
#define gen_PARALLEL_CASE_get_rvalue_LIST(n) ast_get_son_n(n,2)
#define gen_PARALLEL_CASE_put_rvalue_LIST(n,v) ast_put_son_n(n,2,v)

#define PARALLEL_CASE_stmt_LIST 3
#define gen_PARALLEL_CASE_get_stmt_LIST(n) ast_get_son_n(n,3)
#define gen_PARALLEL_CASE_put_stmt_LIST(n,v) ast_put_son_n(n,3,v)

#define DO_ALL_lbl_def 1
#define gen_DO_ALL_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_DO_ALL_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define DO_ALL_close_lbl_def 2
#define gen_DO_ALL_get_close_lbl_def(n) ast_get_son_n(n,2)
#define gen_DO_ALL_put_close_lbl_def(n,v) ast_put_son_n(n,2,v)

#define DO_ALL_lbl_ref 3
#define gen_DO_ALL_get_lbl_ref(n) ast_get_son_n(n,3)
#define gen_DO_ALL_put_lbl_ref(n,v) ast_put_son_n(n,3,v)

#define DO_ALL_control 4
#define gen_DO_ALL_get_control(n) ast_get_son_n(n,4)
#define gen_DO_ALL_put_control(n,v) ast_put_son_n(n,4,v)

#define DO_ALL_stmt_LIST 5
#define gen_DO_ALL_get_stmt_LIST(n) ast_get_son_n(n,5)
#define gen_DO_ALL_put_stmt_LIST(n,v) ast_put_son_n(n,5,v)

#define TASK_COMMON_lbl_def 1
#define gen_TASK_COMMON_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_TASK_COMMON_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define TASK_COMMON_common_elt_LIST 2
#define gen_TASK_COMMON_get_common_elt_LIST(n) ast_get_son_n(n,2)
#define gen_TASK_COMMON_put_common_elt_LIST(n,v) ast_put_son_n(n,2,v)

#define LOCK_lbl_def 1
#define gen_LOCK_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_LOCK_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define LOCK_lvalue 2
#define gen_LOCK_get_lvalue(n) ast_get_son_n(n,2)
#define gen_LOCK_put_lvalue(n,v) ast_put_son_n(n,2,v)

#define UNLOCK_lbl_def 1
#define gen_UNLOCK_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_UNLOCK_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define UNLOCK_lvalue 2
#define gen_UNLOCK_get_lvalue(n) ast_get_son_n(n,2)
#define gen_UNLOCK_put_lvalue(n,v) ast_put_son_n(n,2,v)

#define WAIT_lbl_def 1
#define gen_WAIT_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_WAIT_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define WAIT_lvalue 2
#define gen_WAIT_get_lvalue(n) ast_get_son_n(n,2)
#define gen_WAIT_put_lvalue(n,v) ast_put_son_n(n,2,v)

#define WAIT_rvalue 3
#define gen_WAIT_get_rvalue(n) ast_get_son_n(n,3)
#define gen_WAIT_put_rvalue(n,v) ast_put_son_n(n,3,v)

#define POST_lbl_def 1
#define gen_POST_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_POST_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define POST_postvalue 2
#define gen_POST_get_postvalue(n) ast_get_son_n(n,2)
#define gen_POST_put_postvalue(n,v) ast_put_son_n(n,2,v)

#define POSTING_lvalue 1
#define gen_POSTING_get_lvalue(n) ast_get_son_n(n,1)
#define gen_POSTING_put_lvalue(n,v) ast_put_son_n(n,1,v)

#define POSTING_postvalue 2
#define gen_POSTING_get_postvalue(n) ast_get_son_n(n,2)
#define gen_POSTING_put_postvalue(n,v) ast_put_son_n(n,2,v)

#define POST_TO_rvalue 1
#define gen_POST_TO_get_rvalue(n) ast_get_son_n(n,1)
#define gen_POST_TO_put_rvalue(n,v) ast_put_son_n(n,1,v)

#define POST_INC_rvalue 1
#define gen_POST_INC_get_rvalue(n) ast_get_son_n(n,1)
#define gen_POST_INC_put_rvalue(n,v) ast_put_son_n(n,1,v)

#define CLEAR_lbl_def 1
#define gen_CLEAR_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_CLEAR_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define CLEAR_lvalue 2
#define gen_CLEAR_get_lvalue(n) ast_get_son_n(n,2)
#define gen_CLEAR_put_lvalue(n,v) ast_put_son_n(n,2,v)

#define SET_BARRIER_lbl_def 1
#define gen_SET_BARRIER_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_SET_BARRIER_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define SET_BARRIER_lvalue 2
#define gen_SET_BARRIER_get_lvalue(n) ast_get_son_n(n,2)
#define gen_SET_BARRIER_put_lvalue(n,v) ast_put_son_n(n,2,v)

#define SET_BARRIER_rvalue 3
#define gen_SET_BARRIER_get_rvalue(n) ast_get_son_n(n,3)
#define gen_SET_BARRIER_put_rvalue(n,v) ast_put_son_n(n,3,v)

#define BLOCK_lbl_def 1
#define gen_BLOCK_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_BLOCK_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define BLOCK_lvalue 2
#define gen_BLOCK_get_lvalue(n) ast_get_son_n(n,2)
#define gen_BLOCK_put_lvalue(n,v) ast_put_son_n(n,2,v)

#define SUBSCRIPT_name 1
#define gen_SUBSCRIPT_get_name(n) ast_get_son_n(n,1)
#define gen_SUBSCRIPT_put_name(n,v) ast_put_son_n(n,1,v)

#define SUBSCRIPT_rvalue_LIST 2
#define gen_SUBSCRIPT_get_rvalue_LIST(n) ast_get_son_n(n,2)
#define gen_SUBSCRIPT_put_rvalue_LIST(n,v) ast_put_son_n(n,2,v)

#define SUBSTRING_substring_name 1
#define gen_SUBSTRING_get_substring_name(n) ast_get_son_n(n,1)
#define gen_SUBSTRING_put_substring_name(n,v) ast_put_son_n(n,1,v)

#define SUBSTRING_rvalue1 2
#define gen_SUBSTRING_get_rvalue1(n) ast_get_son_n(n,2)
#define gen_SUBSTRING_put_rvalue1(n,v) ast_put_son_n(n,2,v)

#define SUBSTRING_rvalue2 3
#define gen_SUBSTRING_get_rvalue2(n) ast_get_son_n(n,3)
#define gen_SUBSTRING_put_rvalue2(n,v) ast_put_son_n(n,3,v)

#define INVOCATION_name 1
#define gen_INVOCATION_get_name(n) ast_get_son_n(n,1)
#define gen_INVOCATION_put_name(n,v) ast_put_son_n(n,1,v)

#define INVOCATION_actual_arg_LIST 2
#define gen_INVOCATION_get_actual_arg_LIST(n) ast_get_son_n(n,2)
#define gen_INVOCATION_put_actual_arg_LIST(n,v) ast_put_son_n(n,2,v)

#define BINARY_EXPONENT_rvalue1 1
#define gen_BINARY_EXPONENT_get_rvalue1(n) ast_get_son_n(n,1)
#define gen_BINARY_EXPONENT_put_rvalue1(n,v) ast_put_son_n(n,1,v)

#define BINARY_EXPONENT_rvalue2 2
#define gen_BINARY_EXPONENT_get_rvalue2(n) ast_get_son_n(n,2)
#define gen_BINARY_EXPONENT_put_rvalue2(n,v) ast_put_son_n(n,2,v)

#define BINARY_TIMES_rvalue1 1
#define gen_BINARY_TIMES_get_rvalue1(n) ast_get_son_n(n,1)
#define gen_BINARY_TIMES_put_rvalue1(n,v) ast_put_son_n(n,1,v)

#define BINARY_TIMES_rvalue2 2
#define gen_BINARY_TIMES_get_rvalue2(n) ast_get_son_n(n,2)
#define gen_BINARY_TIMES_put_rvalue2(n,v) ast_put_son_n(n,2,v)

#define BINARY_DIVIDE_rvalue1 1
#define gen_BINARY_DIVIDE_get_rvalue1(n) ast_get_son_n(n,1)
#define gen_BINARY_DIVIDE_put_rvalue1(n,v) ast_put_son_n(n,1,v)

#define BINARY_DIVIDE_rvalue2 2
#define gen_BINARY_DIVIDE_get_rvalue2(n) ast_get_son_n(n,2)
#define gen_BINARY_DIVIDE_put_rvalue2(n,v) ast_put_son_n(n,2,v)

#define BINARY_PLUS_rvalue1 1
#define gen_BINARY_PLUS_get_rvalue1(n) ast_get_son_n(n,1)
#define gen_BINARY_PLUS_put_rvalue1(n,v) ast_put_son_n(n,1,v)

#define BINARY_PLUS_rvalue2 2
#define gen_BINARY_PLUS_get_rvalue2(n) ast_get_son_n(n,2)
#define gen_BINARY_PLUS_put_rvalue2(n,v) ast_put_son_n(n,2,v)

#define BINARY_MINUS_rvalue1 1
#define gen_BINARY_MINUS_get_rvalue1(n) ast_get_son_n(n,1)
#define gen_BINARY_MINUS_put_rvalue1(n,v) ast_put_son_n(n,1,v)

#define BINARY_MINUS_rvalue2 2
#define gen_BINARY_MINUS_get_rvalue2(n) ast_get_son_n(n,2)
#define gen_BINARY_MINUS_put_rvalue2(n,v) ast_put_son_n(n,2,v)

#define BINARY_CONCAT_rvalue1 1
#define gen_BINARY_CONCAT_get_rvalue1(n) ast_get_son_n(n,1)
#define gen_BINARY_CONCAT_put_rvalue1(n,v) ast_put_son_n(n,1,v)

#define BINARY_CONCAT_rvalue2 2
#define gen_BINARY_CONCAT_get_rvalue2(n) ast_get_son_n(n,2)
#define gen_BINARY_CONCAT_put_rvalue2(n,v) ast_put_son_n(n,2,v)

#define BINARY_AND_rvalue1 1
#define gen_BINARY_AND_get_rvalue1(n) ast_get_son_n(n,1)
#define gen_BINARY_AND_put_rvalue1(n,v) ast_put_son_n(n,1,v)

#define BINARY_AND_rvalue2 2
#define gen_BINARY_AND_get_rvalue2(n) ast_get_son_n(n,2)
#define gen_BINARY_AND_put_rvalue2(n,v) ast_put_son_n(n,2,v)

#define BINARY_OR_rvalue1 1
#define gen_BINARY_OR_get_rvalue1(n) ast_get_son_n(n,1)
#define gen_BINARY_OR_put_rvalue1(n,v) ast_put_son_n(n,1,v)

#define BINARY_OR_rvalue2 2
#define gen_BINARY_OR_get_rvalue2(n) ast_get_son_n(n,2)
#define gen_BINARY_OR_put_rvalue2(n,v) ast_put_son_n(n,2,v)

#define BINARY_EQ_rvalue1 1
#define gen_BINARY_EQ_get_rvalue1(n) ast_get_son_n(n,1)
#define gen_BINARY_EQ_put_rvalue1(n,v) ast_put_son_n(n,1,v)

#define BINARY_EQ_rvalue2 2
#define gen_BINARY_EQ_get_rvalue2(n) ast_get_son_n(n,2)
#define gen_BINARY_EQ_put_rvalue2(n,v) ast_put_son_n(n,2,v)

#define BINARY_NE_rvalue1 1
#define gen_BINARY_NE_get_rvalue1(n) ast_get_son_n(n,1)
#define gen_BINARY_NE_put_rvalue1(n,v) ast_put_son_n(n,1,v)

#define BINARY_NE_rvalue2 2
#define gen_BINARY_NE_get_rvalue2(n) ast_get_son_n(n,2)
#define gen_BINARY_NE_put_rvalue2(n,v) ast_put_son_n(n,2,v)

#define BINARY_GE_rvalue1 1
#define gen_BINARY_GE_get_rvalue1(n) ast_get_son_n(n,1)
#define gen_BINARY_GE_put_rvalue1(n,v) ast_put_son_n(n,1,v)

#define BINARY_GE_rvalue2 2
#define gen_BINARY_GE_get_rvalue2(n) ast_get_son_n(n,2)
#define gen_BINARY_GE_put_rvalue2(n,v) ast_put_son_n(n,2,v)

#define BINARY_GT_rvalue1 1
#define gen_BINARY_GT_get_rvalue1(n) ast_get_son_n(n,1)
#define gen_BINARY_GT_put_rvalue1(n,v) ast_put_son_n(n,1,v)

#define BINARY_GT_rvalue2 2
#define gen_BINARY_GT_get_rvalue2(n) ast_get_son_n(n,2)
#define gen_BINARY_GT_put_rvalue2(n,v) ast_put_son_n(n,2,v)

#define BINARY_LE_rvalue1 1
#define gen_BINARY_LE_get_rvalue1(n) ast_get_son_n(n,1)
#define gen_BINARY_LE_put_rvalue1(n,v) ast_put_son_n(n,1,v)

#define BINARY_LE_rvalue2 2
#define gen_BINARY_LE_get_rvalue2(n) ast_get_son_n(n,2)
#define gen_BINARY_LE_put_rvalue2(n,v) ast_put_son_n(n,2,v)

#define BINARY_LT_rvalue1 1
#define gen_BINARY_LT_get_rvalue1(n) ast_get_son_n(n,1)
#define gen_BINARY_LT_put_rvalue1(n,v) ast_put_son_n(n,1,v)

#define BINARY_LT_rvalue2 2
#define gen_BINARY_LT_get_rvalue2(n) ast_get_son_n(n,2)
#define gen_BINARY_LT_put_rvalue2(n,v) ast_put_son_n(n,2,v)

#define BINARY_EQV_rvalue1 1
#define gen_BINARY_EQV_get_rvalue1(n) ast_get_son_n(n,1)
#define gen_BINARY_EQV_put_rvalue1(n,v) ast_put_son_n(n,1,v)

#define BINARY_EQV_rvalue2 2
#define gen_BINARY_EQV_get_rvalue2(n) ast_get_son_n(n,2)
#define gen_BINARY_EQV_put_rvalue2(n,v) ast_put_son_n(n,2,v)

#define BINARY_NEQV_rvalue1 1
#define gen_BINARY_NEQV_get_rvalue1(n) ast_get_son_n(n,1)
#define gen_BINARY_NEQV_put_rvalue1(n,v) ast_put_son_n(n,1,v)

#define BINARY_NEQV_rvalue2 2
#define gen_BINARY_NEQV_get_rvalue2(n) ast_get_son_n(n,2)
#define gen_BINARY_NEQV_put_rvalue2(n,v) ast_put_son_n(n,2,v)

#define UNARY_MINUS_rvalue 1
#define gen_UNARY_MINUS_get_rvalue(n) ast_get_son_n(n,1)
#define gen_UNARY_MINUS_put_rvalue(n,v) ast_put_son_n(n,1,v)

#define UNARY_NOT_rvalue 1
#define gen_UNARY_NOT_get_rvalue(n) ast_get_son_n(n,1)
#define gen_UNARY_NOT_put_rvalue(n,v) ast_put_son_n(n,1,v)

#define CONDITIONAL_rvalue 1
#define gen_CONDITIONAL_get_rvalue(n) ast_get_son_n(n,1)
#define gen_CONDITIONAL_put_rvalue(n,v) ast_put_son_n(n,1,v)

#define INDUCTIVE_name 1
#define gen_INDUCTIVE_get_name(n) ast_get_son_n(n,1)
#define gen_INDUCTIVE_put_name(n,v) ast_put_son_n(n,1,v)

#define INDUCTIVE_rvalue1 2
#define gen_INDUCTIVE_get_rvalue1(n) ast_get_son_n(n,2)
#define gen_INDUCTIVE_put_rvalue1(n,v) ast_put_son_n(n,2,v)

#define INDUCTIVE_rvalue2 3
#define gen_INDUCTIVE_get_rvalue2(n) ast_get_son_n(n,3)
#define gen_INDUCTIVE_put_rvalue2(n,v) ast_put_son_n(n,3,v)

#define INDUCTIVE_rvalue3 4
#define gen_INDUCTIVE_get_rvalue3(n) ast_get_son_n(n,4)
#define gen_INDUCTIVE_put_rvalue3(n,v) ast_put_son_n(n,4,v)

#define REPETITIVE_rvalue 1
#define gen_REPETITIVE_get_rvalue(n) ast_get_son_n(n,1)
#define gen_REPETITIVE_put_rvalue(n,v) ast_put_son_n(n,1,v)

#define EXIST_QUERY_lvalue 1
#define gen_EXIST_QUERY_get_lvalue(n) ast_get_son_n(n,1)
#define gen_EXIST_QUERY_put_lvalue(n,v) ast_put_son_n(n,1,v)

#define OPENED_QUERY_lvalue 1
#define gen_OPENED_QUERY_get_lvalue(n) ast_get_son_n(n,1)
#define gen_OPENED_QUERY_put_lvalue(n,v) ast_put_son_n(n,1,v)

#define NUMBER_QUERY_lvalue 1
#define gen_NUMBER_QUERY_get_lvalue(n) ast_get_son_n(n,1)
#define gen_NUMBER_QUERY_put_lvalue(n,v) ast_put_son_n(n,1,v)

#define NAMED_QUERY_lvalue 1
#define gen_NAMED_QUERY_get_lvalue(n) ast_get_son_n(n,1)
#define gen_NAMED_QUERY_put_lvalue(n,v) ast_put_son_n(n,1,v)

#define NAME_QUERY_lvalue 1
#define gen_NAME_QUERY_get_lvalue(n) ast_get_son_n(n,1)
#define gen_NAME_QUERY_put_lvalue(n,v) ast_put_son_n(n,1,v)

#define ACCESS_QUERY_lvalue 1
#define gen_ACCESS_QUERY_get_lvalue(n) ast_get_son_n(n,1)
#define gen_ACCESS_QUERY_put_lvalue(n,v) ast_put_son_n(n,1,v)

#define SEQUENTIAL_QUERY_lvalue 1
#define gen_SEQUENTIAL_QUERY_get_lvalue(n) ast_get_son_n(n,1)
#define gen_SEQUENTIAL_QUERY_put_lvalue(n,v) ast_put_son_n(n,1,v)

#define DIRECT_QUERY_lvalue 1
#define gen_DIRECT_QUERY_get_lvalue(n) ast_get_son_n(n,1)
#define gen_DIRECT_QUERY_put_lvalue(n,v) ast_put_son_n(n,1,v)

#define FORM_QUERY_lvalue 1
#define gen_FORM_QUERY_get_lvalue(n) ast_get_son_n(n,1)
#define gen_FORM_QUERY_put_lvalue(n,v) ast_put_son_n(n,1,v)

#define FORMATTED_QUERY_lvalue 1
#define gen_FORMATTED_QUERY_get_lvalue(n) ast_get_son_n(n,1)
#define gen_FORMATTED_QUERY_put_lvalue(n,v) ast_put_son_n(n,1,v)

#define UNFORMATTED_QUERY_lvalue 1
#define gen_UNFORMATTED_QUERY_get_lvalue(n) ast_get_son_n(n,1)
#define gen_UNFORMATTED_QUERY_put_lvalue(n,v) ast_put_son_n(n,1,v)

#define RECL_QUERY_lvalue 1
#define gen_RECL_QUERY_get_lvalue(n) ast_get_son_n(n,1)
#define gen_RECL_QUERY_put_lvalue(n,v) ast_put_son_n(n,1,v)

#define BLANK_QUERY_lvalue 1
#define gen_BLANK_QUERY_get_lvalue(n) ast_get_son_n(n,1)
#define gen_BLANK_QUERY_put_lvalue(n,v) ast_put_son_n(n,1,v)

#define NEXTREC_QUERY_lvalue 1
#define gen_NEXTREC_QUERY_get_lvalue(n) ast_get_son_n(n,1)
#define gen_NEXTREC_QUERY_put_lvalue(n,v) ast_put_son_n(n,1,v)

#define IOSTAT_QUERY_lvalue 1
#define gen_IOSTAT_QUERY_get_lvalue(n) ast_get_son_n(n,1)
#define gen_IOSTAT_QUERY_put_lvalue(n,v) ast_put_son_n(n,1,v)

#define FILE_SPECIFY_rvalue 1
#define gen_FILE_SPECIFY_get_rvalue(n) ast_get_son_n(n,1)
#define gen_FILE_SPECIFY_put_rvalue(n,v) ast_put_son_n(n,1,v)

#define FMT_SPECIFY_format_identifier 1
#define gen_FMT_SPECIFY_get_format_identifier(n) ast_get_son_n(n,1)
#define gen_FMT_SPECIFY_put_format_identifier(n,v) ast_put_son_n(n,1,v)

#define REC_SPECIFY_rvalue 1
#define gen_REC_SPECIFY_get_rvalue(n) ast_get_son_n(n,1)
#define gen_REC_SPECIFY_put_rvalue(n,v) ast_put_son_n(n,1,v)

#define END_SPECIFY_lbl_ref 1
#define gen_END_SPECIFY_get_lbl_ref(n) ast_get_son_n(n,1)
#define gen_END_SPECIFY_put_lbl_ref(n,v) ast_put_son_n(n,1,v)

#define STATUS_SPECIFY_rvalue 1
#define gen_STATUS_SPECIFY_get_rvalue(n) ast_get_son_n(n,1)
#define gen_STATUS_SPECIFY_put_rvalue(n,v) ast_put_son_n(n,1,v)

#define ACCESS_SPECIFY_rvalue 1
#define gen_ACCESS_SPECIFY_get_rvalue(n) ast_get_son_n(n,1)
#define gen_ACCESS_SPECIFY_put_rvalue(n,v) ast_put_son_n(n,1,v)

#define FORM_SPECIFY_rvalue 1
#define gen_FORM_SPECIFY_get_rvalue(n) ast_get_son_n(n,1)
#define gen_FORM_SPECIFY_put_rvalue(n,v) ast_put_son_n(n,1,v)

#define RECL_SPECIFY_rvalue 1
#define gen_RECL_SPECIFY_get_rvalue(n) ast_get_son_n(n,1)
#define gen_RECL_SPECIFY_put_rvalue(n,v) ast_put_son_n(n,1,v)

#define BLANK_SPECIFY_rvalue 1
#define gen_BLANK_SPECIFY_get_rvalue(n) ast_get_son_n(n,1)
#define gen_BLANK_SPECIFY_put_rvalue(n,v) ast_put_son_n(n,1,v)

#define UNIT_SPECIFY_unit_identifier 1
#define gen_UNIT_SPECIFY_get_unit_identifier(n) ast_get_son_n(n,1)
#define gen_UNIT_SPECIFY_put_unit_identifier(n,v) ast_put_son_n(n,1,v)

#define ERR_SPECIFY_lbl_ref 1
#define gen_ERR_SPECIFY_get_lbl_ref(n) ast_get_son_n(n,1)
#define gen_ERR_SPECIFY_put_lbl_ref(n,v) ast_put_son_n(n,1,v)

#define COMPLEX_CONSTANT_real_const 1
#define gen_COMPLEX_CONSTANT_get_real_const(n) ast_get_son_n(n,1)
#define gen_COMPLEX_CONSTANT_put_real_const(n,v) ast_put_son_n(n,1,v)

#define COMPLEX_CONSTANT_imag_const 2
#define gen_COMPLEX_CONSTANT_get_imag_const(n) ast_get_son_n(n,2)
#define gen_COMPLEX_CONSTANT_put_imag_const(n,v) ast_put_son_n(n,2,v)

#define RETURN_LABEL_lbl_ref 1
#define gen_RETURN_LABEL_get_lbl_ref(n) ast_get_son_n(n,1)
#define gen_RETURN_LABEL_put_lbl_ref(n,v) ast_put_son_n(n,1,v)

#define TYPE_LEN_type 1
#define gen_TYPE_LEN_get_type(n) ast_get_son_n(n,1)
#define gen_TYPE_LEN_put_type(n,v) ast_put_son_n(n,1,v)

#define TYPE_LEN_length 2
#define gen_TYPE_LEN_get_length(n) ast_get_son_n(n,2)
#define gen_TYPE_LEN_put_length(n,v) ast_put_son_n(n,2,v)

#define DIM_lower 1
#define gen_DIM_get_lower(n) ast_get_son_n(n,1)
#define gen_DIM_put_lower(n,v) ast_put_son_n(n,1,v)

#define DIM_upper 2
#define gen_DIM_get_upper(n) ast_get_son_n(n,2)
#define gen_DIM_put_upper(n,v) ast_put_son_n(n,2,v)

#define REPEAT_count 1
#define gen_REPEAT_get_count(n) ast_get_son_n(n,1)
#define gen_REPEAT_put_count(n,v) ast_put_son_n(n,1,v)

#define REPEAT_constant 2
#define gen_REPEAT_get_constant(n) ast_get_son_n(n,2)
#define gen_REPEAT_put_constant(n,v) ast_put_son_n(n,2,v)

#define DECL_type_len 1
#define gen_DECL_get_type_len(n) ast_get_son_n(n,1)
#define gen_DECL_put_type_len(n,v) ast_put_son_n(n,1,v)

#define DECL_list_LIST 2
#define gen_DECL_get_list_LIST(n) ast_get_son_n(n,2)
#define gen_DECL_put_list_LIST(n,v) ast_put_son_n(n,2,v)

#define DECL_value 3
#define gen_DECL_get_value(n) ast_get_son_n(n,3)
#define gen_DECL_put_value(n,v) ast_put_son_n(n,3,v)

#define PARALLELLOOP_lbl_def 1
#define gen_PARALLELLOOP_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_PARALLELLOOP_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define PARALLELLOOP_close_lbl_def 2
#define gen_PARALLELLOOP_get_close_lbl_def(n) ast_get_son_n(n,2)
#define gen_PARALLELLOOP_put_close_lbl_def(n,v) ast_put_son_n(n,2,v)

#define PARALLELLOOP_lbl_ref 3
#define gen_PARALLELLOOP_get_lbl_ref(n) ast_get_son_n(n,3)
#define gen_PARALLELLOOP_put_lbl_ref(n,v) ast_put_son_n(n,3,v)

#define PARALLELLOOP_control 4
#define gen_PARALLELLOOP_get_control(n) ast_get_son_n(n,4)
#define gen_PARALLELLOOP_put_control(n,v) ast_put_son_n(n,4,v)

#define PARALLELLOOP_stmt_LIST 5
#define gen_PARALLELLOOP_get_stmt_LIST(n) ast_get_son_n(n,5)
#define gen_PARALLELLOOP_put_stmt_LIST(n,v) ast_put_son_n(n,5,v)

#define PRIVATE_lbl_def 1
#define gen_PRIVATE_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_PRIVATE_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define PRIVATE_name_LIST 2
#define gen_PRIVATE_get_name_LIST(n) ast_get_son_n(n,2)
#define gen_PRIVATE_put_name_LIST(n,v) ast_put_son_n(n,2,v)

#define STOPLOOP_lbl_def 1
#define gen_STOPLOOP_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_STOPLOOP_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define STOPLOOP_lbl_ref 2
#define gen_STOPLOOP_get_lbl_ref(n) ast_get_son_n(n,2)
#define gen_STOPLOOP_put_lbl_ref(n,v) ast_put_son_n(n,2,v)

#define TRIPLET_lower 1
#define gen_TRIPLET_get_lower(n) ast_get_son_n(n,1)
#define gen_TRIPLET_put_lower(n,v) ast_put_son_n(n,1,v)

#define TRIPLET_upper 2
#define gen_TRIPLET_get_upper(n) ast_get_son_n(n,2)
#define gen_TRIPLET_put_upper(n,v) ast_put_son_n(n,2,v)

#define TRIPLET_step 3
#define gen_TRIPLET_get_step(n) ast_get_son_n(n,3)
#define gen_TRIPLET_put_step(n,v) ast_put_son_n(n,3,v)

#define ALLOCATABLE_lbl_def 1
#define gen_ALLOCATABLE_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_ALLOCATABLE_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define ALLOCATABLE_arrays_LIST 2
#define gen_ALLOCATABLE_get_arrays_LIST(n) ast_get_son_n(n,2)
#define gen_ALLOCATABLE_put_arrays_LIST(n,v) ast_put_son_n(n,2,v)

#define ALLOCATE_lbl_def 1
#define gen_ALLOCATE_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_ALLOCATE_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define ALLOCATE_object_LIST 2
#define gen_ALLOCATE_get_object_LIST(n) ast_get_son_n(n,2)
#define gen_ALLOCATE_put_object_LIST(n,v) ast_put_son_n(n,2,v)

#define DEALLOCATE_lbl_def 1
#define gen_DEALLOCATE_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_DEALLOCATE_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define DEALLOCATE_object_LIST 2
#define gen_DEALLOCATE_get_object_LIST(n) ast_get_son_n(n,2)
#define gen_DEALLOCATE_put_object_LIST(n,v) ast_put_son_n(n,2,v)

#define WHERE_BLOCK_lbl_def 1
#define gen_WHERE_BLOCK_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_WHERE_BLOCK_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define WHERE_BLOCK_close_lbl_def 2
#define gen_WHERE_BLOCK_get_close_lbl_def(n) ast_get_son_n(n,2)
#define gen_WHERE_BLOCK_put_close_lbl_def(n,v) ast_put_son_n(n,2,v)

#define WHERE_BLOCK_guard_LIST 3
#define gen_WHERE_BLOCK_get_guard_LIST(n) ast_get_son_n(n,3)
#define gen_WHERE_BLOCK_put_guard_LIST(n,v) ast_put_son_n(n,3,v)

#define WHERE_lbl_def 1
#define gen_WHERE_get_lbl_def(n) ast_get_son_n(n,1)
#define gen_WHERE_put_lbl_def(n,v) ast_put_son_n(n,1,v)

#define WHERE_rvalue 2
#define gen_WHERE_get_rvalue(n) ast_get_son_n(n,2)
#define gen_WHERE_put_rvalue(n,v) ast_put_son_n(n,2,v)

#define WHERE_stmt_LIST 3
#define gen_WHERE_get_stmt_LIST(n) ast_get_son_n(n,3)
#define gen_WHERE_put_stmt_LIST(n,v) ast_put_son_n(n,3,v)


#endif
