BEGIN {
	print "/* This include file is generated by a bogus awk script... */"
	print "/* Try regenerating it with 'awk -f fix.awk nodedef.def' */"
	print ""
      }
/struct/{
	next
	}
/"/{
        name = substr($1,2,length($1)-2)
	prefix = name
        count = 1
	next
      }
/\/\*/{
    	if ($2 == "NULL") next
        printf("#define %s_%s %d\n",prefix,$2,count)
	printf("#define gen_%s_get_%s(n) ast_get_son_n(n,%d)\n", \
			prefix,$2,count)
	printf("#define gen_%s_put_%s(n,v) ast_put_son_n(n,%d,v)\n\n", \
			prefix,$2,count)
        count++
	next
      }
/{/{
       next
      }
/}/{
       next
      }
END   {}
