# $Id: Makefile,v 1.1 1997/03/11 14:35:56 carr Exp $

HERE = libs/moduleAnalysis/dependence/edgeList

SRCS = \
	   el.ansi.c \
	   el_view.ansi.c 

ARCHIVE	= ../ModuleAnalysis-$(DSYSTEM_OS)-g.a

include Makeinclude
