# $Id: Makefile,v 1.1 1997/03/11 14:34:55 carr Exp $
 
HERE = libs/ipAnalysis/problems/alias
 
SRCS =	AliasSets.C AliasAnnot.C AliasDFProblem.C AliasAnnotMgrs.C
 
ARCHIVE = ../IPAnalysis-$(DSYSTEM_OS)-g.a
 
include Makeinclude
