# $Id: Makefile,v 1.6 1994/01/18 14:25:20 carr Exp $
ENV_FLAG := -g
HERE = libs/mc_lib/li
INCLUDEDIRS	= libs/mc_lib/include
ARCHIVE		= ../mc-$(RN_ARCH)$(ENV_FLAG).a
SRCS		= interchange.C stats.C

include Makeinclude
