# $Id: Makefile,v 1.14 1997/04/08 20:10:40 carr Exp $
HERE = libs/Memoria/li
INCLUDEDIRS	= libs/Memoria/include
ARCHIVE		= ../Memoria-$(RN_ARCH)$(ENV_FLAG).a
SRCS		= interchange.C stats.C MemoryOrder.C Reversal.C \
		  FDgraph.ansi.c

include Makeinclude
