# $Id: Makefile,v 1.13 1997/04/08 18:58:25 carr Exp $
HERE = libs/Memoria/li
INCLUDEDIRS	= libs/Memoria/include
ARCHIVE		= ../Memoria-$(RN_ARCH)$(ENV_FLAG).a
SRCS		= interchange.C stats.C MemoryOrder.C fusion.ansi.c  Reversal.C \
		  FDgraph.ansi.C

include Makeinclude
