# $Id: Makefile,v 1.1 1997/03/11 14:32:48 carr Exp $

HERE = libs/graphicInterface/framework

SRCS = \
	   Arrow.C \
	   CClipboard.C \
	   CCP.C \
	   CFortEditor.C \
	   CMenu.C \
	   CObject.C \
	   CPed.C \
	   CTextView.C \
	   CViewFilter.C \
	   ColumnEditor.C \
	   ColumnView.C \
	   Decoration.C \
	   DecorationSet.C \
	   DependenceArrow.C \
	   DBObject.C \
	   Editor.C \
	   EditorCP.C \
	   FilterDefSet.C \
	   FortArrow.C \
	   FortFilterDef.C \
	   FortView.C \
	   HeadingView.C \
	   LineEditor.C \
	   LineNumDecoration.C \
	   LineSelection.C \
	   LineView.C \
	   LoopIconDecoration.C \
	   MarginDecoration.C \
	   MenuBar.C \
	   NodeDecoration.C \
	   Scrap.C \
	   ScrollView.C \
	   Selection.C \
	   SplitEditor.C \
	   SplitView.C \
	   Text.C \
	   UserFilter.C \
	   UserFilterDef.C \
	   View.C

ARCHIVE	= Framework-$(DSYSTEM_OS)-g.a

include ../../../make.config

include $(DEPENDS)

# DO NOT DELETE THIS LINE -- make depend depends on it.