# $Id: Makefile,v 1.3 1997/04/09 19:56:37 carr Exp $

HERE = libs/frontEnd/prettyPrinter

SRCS = \
	   ft_export.C
#	   ft_export.C \
#	   options_std.C \
#	   options_adifor.C \
#	   options_drace.C \
#	   ptree_lib.C

ARCHIVE = FrontEnd-$(DSYSTEM_OS)-g.a

include Makeinclude
