# $Id: Makefile,v 1.1 1997/03/11 14:30:01 carr Exp $

HERE = libs/frontEnd/prettyPrinter

SRCS = \
	   ft_export.C
#	   ft_export.C \
#	   options_std.C \
#	   options_adifor.C \
#	   options_drace.C \
#	   ptree_lib.C

ARCHIVE = FrontEnd-$(DSYSTEM_OS)-g.a

include Makeinclude
