# $Id: Makefile,v 1.2 1997/06/25 15:18:28 carr Exp $

HERE = libs/support/patternMatch

SRCS = \
	   bmsearch.C \
	   regerror.C \
	   regexp.C \
	   regsub.C

ARCHIVE = ../Support-$(DSYSTEM_OS)-g.a

include Makeinclude
