# $Id: Makefile,v 1.1 1997/03/11 14:37:09 carr Exp $

HERE = libs/support/patternMatch

SRCS = \
	   bmsearch.ansi.c \
	   regerror.ansi.c \
	   regexp.ansi.c \
	   regsub.ansi.c

ARCHIVE = ../Support-$(DSYSTEM_OS)-g.a

include Makeinclude
