# $Id: Makefile,v 1.1 1997/03/11 14:33:02 carr Exp $

HERE = libs/graphicInterface/oldMonitor/dialogs/filer

SRCS = \
	   filer_dia.ansi.c \
	   table_item.ansi.c \
	   table_sm.ansi.c

ARCHIVE = ../dialogs-$(DSYSTEM_OS)-g.a

include Makeinclude
