# $Id: Makefile,v 1.2 1997/06/25 14:44:32 carr Exp $

HERE = libs/graphicInterface/oldMonitor/dialogs/filer

SRCS = \
	   filer_dia.C \
	   table_item.C \
	   table_sm.C

ARCHIVE = ../dialogs-$(DSYSTEM_OS)-g.a

include ../../../../../make.config

include $(DEPENDS)

# DO NOT DELETE THIS LINE -- make depend depends on it.