# $Id: Makefile,v 1.1 1997/03/11 14:29:15 carr Exp $

HERE = libs/frontEnd

DIRS = \
	   ast \
	   fortTextTree \
	   fortTree \
	   prettyPrinter \
	   textTree

ARCHIVE = FrontEnd-$(DSYSTEM_OS)-g.a

include Makeinclude
