# $Id: Makefile,v 1.2 1997/06/25 14:40:38 carr Exp $

HERE = libs/graphicInterface/cmdProcs/paraScopeEditor/el

SRCS = \
	   ped_el.C 

ARCHIVE	= ped-$(DSYSTEM_OS)-g.a

include ../../../../../make.config

include $(DEPENDS)

# DO NOT DELETE THIS LINE -- make depend depends on it.