# $Id: Makefile,v 1.2 1997/03/27 20:14:26 carr Exp $
HERE = execs/Memoria
SRCS	        = Memoria.C MemoriaOptions.C
ARCHIVE         = Memoria-$(DSYSTEM_OS)-g.a
EXEC	        = Memoria-$(DSYSTEM_OS)
DSYSTEM_LIBS    = $(NLIBS) 
LOCAL_LIBS      = -lm -ll

include Makeinclude

