# $Id: Makefile,v 1.1 1997/03/11 14:33:27 carr Exp $

HERE = libs/graphicInterface/oldMonitor/monitor/dialogs

VERSIONS = monX

SRCS = \
	   confirm.ansi.c \
	   find.ansi.c \
	   message_dia.ansi.c \
	   message_dia2.ansi.c \
	   prompt.ansi.c \
	   yes_no.ansi.c

ARCHIVE_monX = ../monX-$(DSYSTEM_OS)-g.a

include Makeinclude
