# $Id: Makefile,v 1.2 1997/06/25 14:47:38 carr Exp $

HERE = libs/graphicInterface/oldMonitor/monitor/dialogs

VERSIONS = monX

SRCS = \
	   confirm.C \
	   find.C \
	   message_dia.C \
	   message_dia2.C \
	   prompt.C \
	   yes_no.C

ARCHIVE_monX = ../monX-$(DSYSTEM_OS)-g.a

include Makeinclude
