# $Id: Makefile,v 1.2 1997/06/25 15:00:56 carr Exp $

HERE = libs/graphicInterface/oldMonitor/monitor/sms/gtd_sm
VERSIONS = monX
SRCS	= gtd_sm.C
ARCHIVE_monX = ../../monX-$(DSYSTEM_OS)-g.a

include Makeinclude
