# $Id: Makefile,v 1.1 1997/03/11 14:33:58 carr Exp $

HERE = libs/graphicInterface/oldMonitor/monitor/sms/gtd_sm
VERSIONS = monX
SRCS	= gtd_sm.ansi.c
ARCHIVE_monX = ../../monX-$(DSYSTEM_OS)-g.a

include Makeinclude
