# $Id: Makefile,v 1.1 1997/03/11 14:37:00 carr Exp $

HERE = libs/support/msgHandlers

SRCS = \
	   Changes.C \
	   DumpMsgHandler.C \
	   ErrorMsgHandler.C \
	   MsgHandler.C \
	   TraceMsgHandler.C \
	   interact.ansi.c \
	   log_msg.ansi.c \
	   log_msg_dlg.ansi.c

ARCHIVE = ../Support-$(DSYSTEM_OS)-g.a

include Makeinclude
