# $Id: Makefile,v 1.2 1997/06/25 15:17:31 carr Exp $

HERE = libs/support/msgHandlers

SRCS = \
	   Changes.C \
	   DumpMsgHandler.C \
	   ErrorMsgHandler.C \
	   MsgHandler.C \
	   TraceMsgHandler.C \
	   interact.C \
	   log_msg.C \
	   log_msg_dlg.C

ARCHIVE = ../Support-$(DSYSTEM_OS)-g.a

include Makeinclude
