# $Id: Makefile,v 1.2 1997/03/27 20:31:44 carr Exp $

HERE = libs/fileAttrMgmt/fortranModule

#	ScanFile.C 
SRCS = \
	AFormalModAttr.C \
	CollectLocalInfo.C \
	ComputeFortD.C \
	ComputeModRef.C \
	ComputeProcSummary.C \
	FortDModAttr.C \
	FortTextTreeModAttr.C \
	FortTreeModAttr.C  \
	FortranModule.C \
	FortranModuleAttributes.C \
	ModifyTimeModAttr.C \
	NeedProvFortModAttr.C \
	ParseErrorsModAttr.C \
	ProcSummariesFortModAttr.C \
	RefTextModAttr.C \
	ScalarModRefModAttr.C \
	StandardModuleAttributes.C

ARCHIVE = FileAttrMgmt-$(DSYSTEM_OS)-g.a

include Makeinclude
