# $Id: Makefile,v 1.1 1997/03/11 14:27:58 carr Exp $

HERE = libs/fileAttrMgmt/fortranModule

SRCS = \
	AFormalModAttr.C \
	CollectLocalInfo.C \
	ComputeFortD.C \
	ComputeModRef.C \
	ComputeProcSummary.C \
	FortDModAttr.C \
	FortTextTreeModAttr.C \
	FortTreeModAttr.C  \
	FortranModule.C \
	FortranModuleAttributes.C \
	ModifyTimeModAttr.C \
	NeedProvFortModAttr.C \
	ParseErrorsModAttr.C \
	ProcSummariesFortModAttr.C \
	RefTextModAttr.C \
	ScalarModRefModAttr.C \
	ScanFile.C \
	StandardModuleAttributes.C

ARCHIVE = FileAttrMgmt-$(DSYSTEM_OS)-g.a

include Makeinclude
