# $Id: Makefile,v 1.3 1997/03/27 21:11:15 carr Exp $

HERE = libs/fileAttrMgmt/fortranModule

SRCS = \
	AFormalModAttr.C \
	CollectLocalInfo.C \
	ComputeFortD.C \
	ComputeModRef.C \
	ComputeProcSummary.C \
	FortDModAttr.C \
	FortTextTreeModAttr.C \
	FortTreeModAttr.C  \
	FortranModule.C \
	FortranModuleAttributes.C \
	ModifyTimeModAttr.C \
	NeedProvFortModAttr.C \
	ParseErrorsModAttr.C \
	ProcSummariesFortModAttr.C \
	RefTextModAttr.C \
	ScalarModRefModAttr.C \
	ScanFile.C \
	StandardModuleAttributes.C

ARCHIVE = FileAttrMgmt-$(DSYSTEM_OS)-g.a


include ../../../make.config

include $(DEPENDS)

# DO NOT DELETE THIS LINE -- make depend depends on it.
