# $Id: Makefile,v 1.1 1997/03/11 14:30:29 carr Exp $

HERE = libs/graphicInterface/cmdProcs/help

SRCS = \
	   file_read.ansi.c \
	   help.ansi.c \
	   hybrid_disp.ansi.c \
	   tree.ansi.c

ARCHIVE	= HelpCP-$(DSYSTEM_OS)-g.a

LOCAL_LINT_FLAGS = -command_processor

include Makeinclude
