# $Id: Makefile,v 1.2 1997/06/24 17:56:30 carr Exp $

HERE = libs/graphicInterface/cmdProcs/help

SRCS = \
	   file_read.C \
	   help.C \
	   hybrid_disp.C \
	   tree.C

ARCHIVE	= HelpCP-$(DSYSTEM_OS)-g.a

LOCAL_LINT_FLAGS = -command_processor

include Makeinclude
