# $Id: Makefile,v 1.2 1997/06/25 15:01:17 carr Exp $

HERE = libs/graphicInterface/oldMonitor/monitor/sms/vanilla_sm
VERSIONS = monX
SRCS	= vanilla.C
ARCHIVE_monX = ../../monX-$(DSYSTEM_OS)-g.a

include Makeinclude
