# $Id: Makefile,v 1.1 1997/03/11 14:34:21 carr Exp $

HERE = libs/graphicInterface/oldMonitor/monitor/sms/vanilla_sm
VERSIONS = monX
SRCS	= vanilla.ansi.c
ARCHIVE_monX = ../../monX-$(DSYSTEM_OS)-g.a

include Makeinclude
