# $Id: Makefile,v 1.1 1997/03/11 14:35:10 carr Exp $

HERE = libs/ipAnalysis/problems/perfEst

SRCS = \
	   PerfAnnot.C  \
	   PerfEstDFProblem.C  \
	   PerfEstExpr.C \
	   SymExpr.C

ARCHIVE = ../IPAnalysis-$(DSYSTEM_OS)-g.a

include Makeinclude

