# $Id: Makefile,v 1.2 1997/06/25 14:52:22 carr Exp $

HERE = libs/graphicInterface/oldMonitor/monitor/mon/root

# command line version
SRCS = \
	    notify_mgr.ansi.c \
	    stand_alone.ansi.c

ARCHIVE = ../../monN-$(DSYSTEM_OS)-g.a

include ../../../../../../make.config

include $(DEPENDS)

# DO NOT DELETE THIS LINE -- make depend depends on it.