# $Id: Makefile,v 1.4 1997/06/25 15:20:20 carr Exp $

HERE = libs/support/strings

SRCS = \
	   OrderedSetOfStrings.C \
	   StringBuffer.C \
	   StringIO.C \
	   StringSet.C \
	   rn_string.C

ARCHIVE = ../Support-$(DSYSTEM_OS)-g.a

include Makeinclude
