# $Id: Makefile,v 1.1 1997/03/11 14:37:28 carr Exp $

HERE = libs/support/strings

SRCS = \
	   OrderedSetOfStrings.C \
	   StringBuffer.C \
	   StringIO.C \
	   StringSet.C \
	   rn_string.ansi.c

ARCHIVE = ../Support-$(DSYSTEM_OS)-g.a

include Makeinclude
