# $Id: Makefile,v 1.2 1997/03/27 20:52:29 carr Exp $

HERE = libs/support/strings
	   #StringBuffer.C \

SRCS = \
	   OrderedSetOfStrings.C \
	   StringIO.C \
	   StringSet.C \
	   rn_string.ansi.c

ARCHIVE = ../Support-$(DSYSTEM_OS)-g.a

include Makeinclude
