# $Id: Makefile,v 1.2 1997/06/25 13:51:02 carr Exp $

HERE = libs/graphicInterface/cmdProcs/newEditor

DIRS = \
	   clipboardCP \
	   fortAnnot \
	   fortEditor \
	   fortEditorCP

SRCS = \
	   NedScrap.C \
	   TextScrap.C \
	   TextView.C \
	   Utility.C \
	   ViewFilter.C

ARCHIVE = NewEditorCP-$(DSYSTEM_OS)-g.a

include Makeinclude
