# $Id: Makefile,v 1.1 1997/03/11 14:30:33 carr Exp $

HERE = libs/graphicInterface/cmdProcs/newEditor

DIRS = \
	   clipboardCP \
	   fortAnnot \
	   fortEditor \
	   fortEditorCP

SRCS = \
	   NedScrap.ansi.c \
	   TextScrap.ansi.c \
	   TextView.ansi.c \
	   Utility.ansi.c \
	   ViewFilter.ansi.c

ARCHIVE = NewEditorCP-$(DSYSTEM_OS)-g.a

include Makeinclude
