# $Id: Makefile,v 1.2 1997/06/25 14:51:46 carr Exp $

HERE = libs/graphicInterface/oldMonitor/monitor/mon/root/system_mgr

VERSIONS = monX

SRCS = system_mgr.C

LOCAL_LINT=lint_mgr lint_other

# X windows
ARCHIVE_monX = ../../../monX-$(DSYSTEM_OS)-g.a

include Makeinclude

