# $Id: Makefile,v 1.1 1997/03/11 14:34:35 carr Exp $

HERE = libs/ipAnalysis/callGraph

SRCS =	\
	    CallGraph.C \
	    CallGraphNodeSet.C \
	    ModuleInfoIterator.C \
	    CallGraphIterators.C \
	    CallGraphNodeEdge.C \
	    CallSiteParamBindings.C \
	    CallGraphFlowInsensitiveDFP.C \
	    CallGraphDFProblem.C


ARCHIVE = IPAnalysis-$(DSYSTEM_OS)-g.a

include ../../../make.config

include $(DEPENDS)

# DO NOT DELETE THIS LINE -- make depend depends on it.
