# $Id: Makefile,v 1.2 1997/06/25 13:43:34 carr Exp $

HERE = libs/graphicInterface/cmdProcs/newEditor/fortEditor

SRCS = \
	   EditorView.C \
	   Expander.C \
	   FortEditor.C \
	   FortEditorSave.C \
	   FortScrap.C \
	   FortVFilter.C \
	   Searcher.C

ARCHIVE = ../NewEditorCP-$(DSYSTEM_OS)-g.a

include Makeinclude
