# $Id: Makefile,v 1.1 1997/03/11 14:30:53 carr Exp $

HERE = libs/graphicInterface/cmdProcs/newEditor/fortEditor

SRCS = \
	   EditorView.ansi.c \
	   Expander.ansi.c \
	   FortEditor.C \
	   FortEditorSave.C \
	   FortScrap.ansi.c \
	   FortVFilter.ansi.c \
	   Searcher.ansi.c

ARCHIVE = ../NewEditorCP-$(DSYSTEM_OS)-g.a

include Makeinclude
