# $Id: Makefile,v 1.2 1997/06/25 14:49:10 carr Exp $

HERE = libs/graphicInterface/oldMonitor/monitor/keyboard

SRCS = \
	   kb.C \
	   keymap.C

ARCHIVE = ../monN-$(DSYSTEM_OS)-g.a

include ../../../../../make.config

include $(DEPENDS)

# DO NOT DELETE THIS LINE -- make depend depends on it.