# $Id: Makefile,v 1.1 1997/03/11 14:33:35 carr Exp $

HERE = libs/graphicInterface/oldMonitor/monitor/keyboard

VERSIONS = monX monN

SRCS = \
	   kb.ansi.c \
	   keymap.ansi.c

ARCHIVE_monX = ../monX-$(DSYSTEM_OS)-g.a

ARCHIVE_monN = ../monN-$(DSYSTEM_OS)-g.a

include Makeinclude
