# $Id: Makefile,v 1.2 1997/06/25 14:49:10 carr Exp $

HERE = libs/graphicInterface/oldMonitor/monitor/keyboard

VERSIONS = monX monN

SRCS = \
	   kb.C \
	   keymap.C

ARCHIVE_monX = ../monX-$(DSYSTEM_OS)-g.a

ARCHIVE_monN = ../monN-$(DSYSTEM_OS)-g.a

include Makeinclude
