# $Id: Makefile,v 1.1 1997/03/11 14:35:25 carr Exp $

HERE = libs/moduleAnalysis/cfg

SRCS = \
	   cfg_local_cd.ansi.c \
	   cfg_changes.ansi.c \
	   cfg_dump.ansi.c \
	   cfg_edges.ansi.c \
	   cfg_ids.ansi.c \
	   cfg_info.ansi.c \
	   cfg_labels.ansi.c \
	   cfg_open.ansi.c \
	   cfg_nodes.ansi.c \
	   cfg_tinker.ansi.c \
	   cfg_utils.ansi.c \
	   dtree.ansi.c	\
	   tarjan.ansi.c \
	   tree_util.ansi.c \
	   cfg_iter.C \
	   cfg_times.C

ARCHIVE	= ModuleAnalysis-$(DSYSTEM_OS)-g.a

include Makeinclude
