# $Id: Makefile,v 1.2 1997/06/25 15:03:56 carr Exp $

HERE = libs/moduleAnalysis/cfg

SRCS = \
	   cfg_local_cd.C \
	   cfg_changes.C \
	   cfg_dump.C \
	   cfg_edges.C \
	   cfg_ids.C \
	   cfg_info.C \
	   cfg_labels.C \
	   cfg_open.C \
	   cfg_nodes.C \
	   cfg_tinker.C \
	   cfg_utils.C \
	   dtree.C	\
	   tarjan.C \
	   tree_util.C \
	   cfg_iter.C \
	   cfg_times.C

ARCHIVE	= ModuleAnalysis-$(DSYSTEM_OS)-g.a

include ../../../make.config

include $(DEPENDS)

# DO NOT DELETE THIS LINE -- make depend depends on it.
