# $Id: Makefile,v 1.1 1997/03/11 14:33:56 carr Exp $

HERE = libs/graphicInterface/oldMonitor/monitor/sms/button_sm
VERSIONS = monX
SRCS	= button_sm.ansi.c
ARCHIVE_monX = ../../monX-$(DSYSTEM_OS)-g.a

include Makeinclude
