# $Id: Makefile,v 1.2 1997/06/25 14:56:44 carr Exp $

HERE = libs/graphicInterface/oldMonitor/monitor/sms/button_sm
VERSIONS = monX
SRCS	= button_sm.C
ARCHIVE_monX = ../../monX-$(DSYSTEM_OS)-g.a

include Makeinclude
