# $Id: Makefile,v 1.1 1997/03/11 14:30:59 carr Exp $

HERE = libs/graphicInterface/cmdProcs/paraScopeEditor

DIRS = \
	   include \
	   pt \
	   dp \
	   dg \
	   el \
	   dt \
	   perf \
	   pedCP \
	   stubs

#	   memory \

include Makeinclude
