# $Id: Makefile,v 1.1 1997/03/11 14:36:49 carr Exp $

HERE = libs/support/lists

SRCS = \
	   DoublyLinkedList.C \
	   IOSinglyLinkedList.C \
	   SinglyLinkedList.C \
	   list.ansi.c

ARCHIVE = ../Support-$(DSYSTEM_OS)-g.a

include Makeinclude
