# $Id: Makefile,v 1.2 1997/06/25 15:16:14 carr Exp $

HERE = libs/support/lists

SRCS = \
	   DoublyLinkedList.C \
	   IOSinglyLinkedList.C \
	   SinglyLinkedList.C \
	   list.C

ARCHIVE = ../Support-$(DSYSTEM_OS)-g.a

include ../../../make.config

include $(DEPENDS)

# DO NOT DELETE THIS LINE -- make depend depends on it.