# $Id: Makefile,v 1.5 1997/04/28 20:18:07 carr Exp $

HERE = libs/f2i
SRCS   = ai.C addr.C do.C goto.C map.C  runtime.C idfa.C memos.C \
	  static.C assign.C expr.C if.C params.C stmts.C assignment.C \
	  expr2.C initials.C  postmap.C string2.C calls.C expr3.C intrins.C \
	  prepass.C strings.C chars.C exps.C io.C procs.C sym.C common.C \
	  gen.C  label.C regs.C utility.C data.C get.C  routine.C \
	  mnemonics.C equiv.C directives.C AliasQuery.C

ARCHIVE	= F2i-$(DSYSTEM_OS)-g.a

include Makeinclude
