# $Id: Makefile,v 1.4 1997/04/24 14:11:33 carr Exp $

HERE = libs/f2i
SRCS   = ai.ansi.c addr.ansi.c do.ansi.c goto.ansi.c map.ansi.c  runtime.ansi.c idfa.ansi.c memos.ansi.c \
	  static.ansi.c assign.ansi.c expr.ansi.c if.ansi.c params.ansi.c stmts.ansi.c assignment.ansi.c \
	  expr2.ansi.c initials.ansi.c  postmap.ansi.c string2.ansi.c calls.ansi.c expr3.ansi.c intrins.ansi.c \
	  prepass.ansi.c strings.ansi.c chars.ansi.c exps.ansi.c io.ansi.c procs.ansi.c sym.ansi.c common.ansi.c \
	  gen.ansi.c  label.ansi.c regs.ansi.c utility.ansi.c data.ansi.c get.ansi.c  routine.ansi.c \
	  mnemonics.ansi.c equiv.ansi.c directives.ansi.c AliasQuery.C

ARCHIVE	= F2i-$(DSYSTEM_OS)-g.a

include Makeinclude
