# $Id: Makefile,v 1.1 1997/03/20 14:27:37 carr Exp $

HERE = libs/a2i_lib
SRCS   = addr.c do.c goto.c map.c  runtime.c ai.c idfa.c memos.c \
	  static.c assign.c expr.c if.c params.c stmts.c assignment.c \
	  expr2.c initials.c  postmap.c string2.c calls.c expr3.c intrins.c \
	  prepass.c strings.c chars.c exps.c io.c procs.c sym.c common.c \
	  gen.c  label.c regs.c utility.c data.c get.c  routine.c \
	  mnemonics.c equiv.c directives.c

INCLUDEDIRS = libs/ipanalysis/include libs/mc_lib/include libs/mc_lib/annotate
ARCHIVE	= a2i-$(RN_ARCH)$(ENV_FLAG).a

include Makeinclude
