/* $Id: runtime.C,v 1.1 1997/04/28 20:18:07 carr Exp $ */
/******************************************************************************/
/*        Copyright (c) 1990, 1991, 1992, 1993, 1994 Rice University          */
/*                           All Rights Reserved                              */
/******************************************************************************/

#include <libs/support/misc/general.h>
#include <libs/frontEnd/ast/ast.h>
#include <libs/f2i/ai.h>
#include <libs/f2i/sym.h>
#include <libs/f2i/f2i_label.h>
#include <libs/f2i/mnemonics.h>


/* The code in this file is never invoked.  It is not clear that it would work anyway.  */



/* generate a runtime error message */
void aiRunTimeError( char *message, int number )
  // char *message;
  // int  number;
{
  char buffer[128];
  int  len, label, labelReg;

  (void) sprintf(buffer, "MC error %d - %s", number, message);
  len = Align(strlen(buffer));
  label = LABEL_NEW;

  generate(label, bDATA, (int) buffer, 1, DATA_CHARACTER, "Error message");
  generate(0,     iDATA, (int) "0",    1, DATA_INTEGER, NOCOMMENT);

  labelReg = StrTempReg("L", label, TYPE_INTEGER);
  generate(0, iLDI, label, labelReg, GEN_LABEL, "String");

  aiPause(labelReg, getConstantInRegFromInt(len));
} /* aiRunTimeError */




/* generate code for a pause generated by a2i*/
void aiPause(int message, int length)
  // int message, length;
{
  char list[32];
  char refs[64];
  char *code;

  /* set the names for the data and code labels */
  if (aiSparc > 0)
    code = "_s_paus";
  else if (aiRt > 0)
    code = "_.s_paus";
  else
    code = "s_paus";

  /* create the parameter list and refs list */
  (void) sprintf(refs, "@%s @%s",
		 fst_my_GetFieldByIndex(ft_SymTable, message, SYMTAB_NAME),
		 fst_my_GetFieldByIndex(ft_SymTable, length, SYMTAB_NAME));
  message = fst_my_GetFieldByIndex(ft_SymTable, message, SYMTAB_REG);
  length = fst_my_GetFieldByIndex(ft_SymTable, length, SYMTAB_REG);
  (void) sprintf(list, "r%d r%d", message, length);

  /* declare the name */
  generate(0, NAME, (int) code, 0, 0, NOCOMMENT);

  /* generate the subroutine call to s_paus */
  generate_long(0, JSRl, (int) code, aiStackBase(), (int) list, 
		(int) /*refs*/ "?", (int) "", 0, GEN_STRING, NOCOMMENT);
} /* aiPause */

