# $Id: Makefile,v 1.1 1997/03/11 14:36:02 carr Exp $

HERE = libs/moduleAnalysis/dependence/utilities

SRCS = \
	   read_util.ansi.c \
	   side_info.ansi.c \
	   strong.ansi.c

ARCHIVE	= ../ModuleAnalysis-$(DSYSTEM_OS)-g.a

include Makeinclude
