# $Id: Makefile,v 1.2 1997/06/25 15:10:07 carr Exp $

HERE = libs/moduleAnalysis/dependence/utilities

SRCS = \
	   read_util.C \
	   side_info.C \
	   strong.C

ARCHIVE	= ../ModuleAnalysis-$(DSYSTEM_OS)-g.a

include Makeinclude
