HERE		= ped_cp/memory/uj
INCLUDEDIRS	= ped_cp/memory/include ped_cp/ped_include ned_cp
ARCHIVE		= ../ped-$(RN_ARCH)$(ENV_FLAG).a
SRCS		= ujam.C compute_uj.C balance.C do_unroll.C log.C do_dist.C

include Makeinclude

