# $Id: Makefile,v 1.5 1994/01/18 14:26:27 carr Exp $
ENV_FLAG := -g
HERE = libs/mc_lib/uj
INCLUDEDIRS	= libs/mc_lib/include
ARCHIVE		= ../mc-$(RN_ARCH)$(ENV_FLAG).a
SRCS		= ujam.C compute_uj.C balance.C do_unroll.C log.C do_dist.C

include Makeinclude

