# $Id: Makefile,v 1.3 1992/10/03 15:49:43 rn Exp $
HERE		= ped_cp/memory/uj
INCLUDEDIRS	= ped_cp/memory/include ped_cp/ped_include
ARCHIVE		= ../ped-$(RN_ARCH)$(ENV_FLAG).a
SRCS		= ujam.C compute_uj.C balance.C do_unroll.C log.C do_dist.C

include Makeinclude

