# $Id: Makefile,v 1.1 1997/03/11 14:36:05 carr Exp $

HERE = libs/moduleAnalysis/expnSimplifier

SRCS = \
	   normal.c \
	   simple.ansi.c

ARCHIVE = ExpnSimplifier-$(DSYSTEM_OS)-g.a

include Makeinclude
