# $Id: Makefile,v 1.1 1997/03/11 14:30:39 carr Exp $

HERE = libs/graphicInterface/cmdProcs/newEditor/clipboardCP

SRCS = \
	   ClipboardCP.ansi.c

ARCHIVE = ../NewEditorCP-$(DSYSTEM_OS)-g.a

include Makeinclude
