# $Id: Makefile,v 1.2 1997/06/24 21:23:29 carr Exp $

HERE = libs/graphicInterface/cmdProcs/newEditor/clipboardCP

SRCS = \
	   ClipboardCP.C

ARCHIVE = ../NewEditorCP-$(DSYSTEM_OS)-g.a

include Makeinclude
