# $Id: Makefile,v 1.4 1997/06/25 15:20:35 carr Exp $

HERE = libs/support/tables

DIRS = \
	   namedObject \
	   wordObject


SRCS = \
	   HashTable.C \
	   cNameValueTable.C \
	   IntegerHashTable.C \
	   NameValueTable.C \
	   PointerMap.C \
	   StringHashTable.C \
	   symtable.C

ARCHIVE = ../Support-$(DSYSTEM_OS)-g.a

include Makeinclude
