# $Id: Makefile,v 1.1 1997/03/11 14:37:34 carr Exp $

HERE = libs/support/tables

DIRS = \
	   namedObject \
	   wordObject

SRCS = \
	   HashTable.C \
	   IntegerHashTable.C \
	   NameValueTable.C \
	   PointerMap.C \
	   StringHashTable.C \
	   cNameValueTable.C \
	   symtable.ansi.c

ARCHIVE = ../Support-$(DSYSTEM_OS)-g.a

include Makeinclude
