# $Id: Makefile,v 1.19 2001/09/14 17:03:05 carr Exp $
HERE = libs/Memoria/ut
ARCHIVE		= ../Memoria-$(DSYSTEM_OS)-g.a
SRCS		= analyze.C bound.C label.C mark.C mem_util.C \
                  set.C shape.C UniformlyGeneratedSets.C \
		  RefGroups.C IntegerList.C la.C Analysis.C Estimate.C \
		  GenericList.C Recurrence.C ASTToIntMap.C ASTToDDGNodeMap.C \
		  MinDist.C DDG.C SPRegisters.C ScalarReplaceMap.C
		  

include Makeinclude
