# $Id: Makefile,v 1.15 1997/07/01 17:47:44 carr Exp $
HERE = libs/Memoria/ut
ARCHIVE		= ../Memoria-$(DSYSTEM_OS)-g.a
SRCS		= analyze.C bound.C label.C mark.C mem_util.C \
                  set.C shape.C UniformlyGeneratedSets.C \
		  RefGroups.C IntegerList.C la.C Analysis.C Estimate.C 
		  

include Makeinclude
