# $Id: Makefile,v 1.8 1994/04/13 14:28:11 carr Exp $
HERE = libs/mc_lib/ut
INCLUDEDIRS	= libs/mc_lib/include 
ARCHIVE		= ../mc-$(RN_ARCH)$(ENV_FLAG).a
SRCS		= analyze.C bound.C label.C mark.C mem_util.C \
                  set.C shape.C pt_util.ansi.c

include Makeinclude
