# $Id: Makefile,v 1.1 1997/03/11 14:27:36 carr Exp $

HERE = libs

DIRS = \
	   config \
	   fileAttrMgmt \
	   fortD \
	   frontEnd \
	   graphicInterface \
	   ipAnalysis \
	   moduleAnalysis \
	   perfAnalysis \
	   support

include Makeinclude
