# $Id: Makefile,v 1.1 1997/03/11 14:36:08 carr Exp $

HERE = libs/moduleAnalysis/ssa

SRCS = \
	   areas.ansi.c \
	   gstack.ansi.c \
	   idfa.ansi.c \
	   ssa_dump.ansi.c \
	   ssa_gated.ansi.c \
	   ssa_ip_refs.ansi.c \
	   ssa_node.ansi.c \
	   ssa_open.ansi.c \
	   ssa_phi.ansi.c \
	   ssa_util.ansi.c \
	   ssa_ids.C \
	   ssa_times.C

ARCHIVE = ModuleAnalysis-$(DSYSTEM_OS)-g.a

include Makeinclude
