# $Id: Makefile,v 1.2 1997/06/25 15:10:55 carr Exp $

HERE = libs/moduleAnalysis/ssa

SRCS = \
	   areas.C \
	   gstack.C \
	   idfa.C \
	   ssa_dump.C \
	   ssa_gated.C \
	   ssa_ip_refs.C \
	   ssa_node.C \
	   ssa_open.C \
	   ssa_phi.C \
	   ssa_util.C \
	   ssa_ids.C \
	   ssa_times.C

ARCHIVE = ModuleAnalysis-$(DSYSTEM_OS)-g.a


include ../../../make.config

include $(DEPENDS)

# DO NOT DELETE THIS LINE -- make depend depends on it.
