# $Id: Makefile,v 1.2 1997/03/27 20:32:26 carr Exp $

HERE = libs/fortD/codeGen

#FortDInterface.C 
SRCS	= \
	  bc.ansi.c \
	  bounds.ansi.c \
	  boundary_msgs.ansi.c \
	  coll_comm.ansi.c \
	  coll_msgs.ansi.c \
	  dc.ansi.c \
	  dc_loops.ansi.c \
	  dc_trans.ansi.c \
	  decomp.ansi.c \
	  m2.ansi.c \
	  msg.ansi.c \
	  msg2.ansi.c \
	  rout.ansi.c \
	  rsd_sec.ansi.c \
	  FortDInterfaceStr.C \
	  FortDInterfaceTest.C

ARCHIVE	= FortD-$(DSYSTEM_OS)-g.a

include Makeinclude
