# $Id: Makefile,v 1.1 1997/03/11 14:37:39 carr Exp $

HERE = libs/support/tables/namedObject

SRCS = \
	   NamedObject.C \
	   NamedObjectTable.C

ARCHIVE = ../../Support-$(DSYSTEM_OS)-g.a

include Makeinclude