# $Id: Makefile,v 1.2 1997/06/25 15:19:03 carr Exp $

HERE = libs/support/sets

SRCS = \
	   DataFlowSet.C \
	   Set.C \
	   Sparse_Set.C \
	   VectorSet.C \
	   WordSet.C \
	   ex_sets.C \
	   set.C \
	   tuple.C

ARCHIVE = ../Support-$(DSYSTEM_OS)-g.a

include ../../../make.config

include $(DEPENDS)

# DO NOT DELETE THIS LINE -- make depend depends on it.