# $Id: Makefile,v 1.1 1997/03/11 14:37:18 carr Exp $

HERE = libs/support/sets

SRCS = \
	   DataFlowSet.C \
	   Set.C \
	   Sparse_Set.C \
	   VectorSet.C \
	   WordSet.C \
	   ex_sets.ansi.c \
	   set.ansi.c \
	   tuple.ansi.c

ARCHIVE = ../Support-$(DSYSTEM_OS)-g.a

include Makeinclude
