# $Id: Makefile,v 1.2 1997/06/25 15:17:54 carr Exp $

HERE = libs/support/numerical

SRCS = \
	   ExtendedGCD.C \
	   NumericalRecipeUtils.C

ARCHIVE = ../Support-$(DSYSTEM_OS)-g.a

include ../../../make.config

include $(DEPENDS)

# DO NOT DELETE THIS LINE -- make depend depends on it.