# $Id: Makefile,v 1.1 1997/03/11 14:37:05 carr Exp $

HERE = libs/support/numerical

SRCS = \
	   ExtendedGCD.ansi.c \
	   NumericalRecipeUtils.ansi.c

ARCHIVE = ../Support-$(DSYSTEM_OS)-g.a

include Makeinclude
