# $Id: Makefile,v 1.1 1997/03/11 14:33:00 carr Exp $

HERE = libs/graphicInterface/oldMonitor/dialogs

DIRS = filer

# opt_dialog.c needs rewrite to C++ -- JMC
#SRCS	= opt_dialog.c -- 

ARCHIVE = dialogs-$(DSYSTEM_OS)-g.a

archive: subarchive

include Makeinclude
