# $Id: Makefile,v 1.1 1997/03/11 14:35:18 carr Exp $

HERE = libs/ipAnalysis/problems/symbolic

SRCS = \
	   SymConAnnot.C \
	   SymConstraints.C \
	   SymForwarding.C \
	   SymTest.C \
	   SymTranslate.C \
	   SymValAnnot.C

ARCHIVE = ../IPAnalysis-$(DSYSTEM_OS)-g.a

include Makeinclude
