# $Id: Makefile,v 1.2 1997/06/25 13:47:08 carr Exp $

HERE = libs/graphicInterface/cmdProcs/newEditor/fortEditorCP

SRCS = \
	   AnnotDialog.C \
	   FortEditorCP.C \
	   FortEditorCP_opt.C \
	   SearchDialog.C \
	   ViewDialog.C

ARCHIVE = ../NewEditorCP-$(DSYSTEM_OS)-g.a

include Makeinclude
