# $Id: Makefile,v 1.1 1997/03/11 14:30:57 carr Exp $

HERE = libs/graphicInterface/cmdProcs/newEditor/fortEditorCP

SRCS = \
	   AnnotDialog.ansi.c \
	   FortEditorCP.C \
	   FortEditorCP_opt.C \
	   SearchDialog.ansi.c \
	   ViewDialog.ansi.c

ARCHIVE = ../NewEditorCP-$(DSYSTEM_OS)-g.a

include Makeinclude
