# $Id: Makefile,v 1.1 1997/03/11 14:35:16 carr Exp $

HERE = libs/ipAnalysis/problems/rsd

SRCS = \
	   AFormalAnnot.C  \
	   AFormalAnnotMgr.C \
	   AFormalDFProblem.C  \
	   AFormalQuery.C

ARCHIVE = ../IPAnalysis-$(DSYSTEM_OS)-g.a

include Makeinclude
