# $Id: Makefile,v 1.1 1997/03/11 14:34:03 carr Exp $

HERE = libs/graphicInterface/oldMonitor/monitor/sms/optim_sm
VERSIONS = monX
SRCS	= \
	  optim.ansi.c \
	  optim_clear.ansi.c \
	  optim_get.ansi.c \
	  optim_put.ansi.c \
	  optim_update.ansi.c

ARCHIVE_monX = ../../monX-$(DSYSTEM_OS)-g.a

include Makeinclude
