# $Id: Makefile,v 1.2 1997/06/25 14:58:38 carr Exp $

HERE = libs/graphicInterface/oldMonitor/monitor/sms/optim_sm
VERSIONS = monX
SRCS	= \
	  optim.C \
	  optim_clear.C \
	  optim_get.C \
	  optim_put.C \
	  optim_update.C

ARCHIVE_monX = ../../monX-$(DSYSTEM_OS)-g.a

include Makeinclude
