# $Id: Makefile,v 1.7 1997/03/27 20:27:20 carr Exp $
HERE = libs/Memoria/sr
ARCHIVE		= ../Memoria-$(DSYSTEM_OS)-g.a
SRCS		= scalar.C block.C table.C dfavail.C pick.C dfantic.C \
		  prune.C insert.C check.C codegen.C name.C \
		  moderate.C gavail.C dfrgen.C profit.C 

include Makeinclude
