# $Id: Makefile,v 1.6 1994/01/25 15:11:42 carr Exp $
HERE = libs/mc_lib/sr
INCLUDEDIRS	= libs/mc_lib/include
ARCHIVE		= ../mc-$(RN_ARCH)$(ENV_FLAG).a
SRCS		= scalar.C block.C table.C dfavail.C pick.C dfantic.C \
		  prune.C insert.C check.C codegen.C name.C \
		  moderate.C gavail.C dfrgen.C profit.C 

include Makeinclude
