HERE		= ped_cp/memory/sr
INCLUDEDIRS	= ped_cp/memory/include ped_cp/ped_include ned_cp 
ARCHIVE		= ../ped-$(RN_ARCH)$(ENV_FLAG).a
SRCS		= scalar.C block.C table.C dfavail.C pick.C dfantic.C \
		  prune.C insert.C check.C codegen.C name.C \
		  moderate.C gavail.C dfrgen.C profit.C 

include Makeinclude
