# $Id: Makefile,v 1.3 1997/03/27 21:09:27 carr Exp $

HERE = libs/support/graphs/directedGraph

SRCS = \
	DirectedGraph.C \
	DirectedGraphIterators.C \
	DirectedGraphNodeSet.C \
	DGNodePointerVector.C \
	DirectedGraphDFPIterative.C

ARCHIVE = ../../Support-$(DSYSTEM_OS)-g.a

include ../../../../make.config

include $(DEPENDS)

# DO NOT DELETE THIS LINE -- make depend depends on it.