# $Id: Makefile,v 1.1 1997/03/11 14:36:44 carr Exp $

HERE = libs/support/graphs/directedGraph

SRCS = \
	DirectedGraph.C \
	DirectedGraphIterators.C \
	DirectedGraphNodeSet.C \
	DGNodePointerVector.C \
	DirectedGraphDFPIterative.C

ARCHIVE = ../../Support-$(DSYSTEM_OS)-g.a

include Makeinclude
