# $Id: Makefile,v 1.2 1997/03/27 20:49:29 carr Exp $

HERE = libs/support/graphs/directedGraph

	#DirectedGraph.C 
SRCS = \
	DirectedGraphIterators.C \
	DirectedGraphNodeSet.C \
	DGNodePointerVector.C \
	DirectedGraphDFPIterative.C

ARCHIVE = ../../Support-$(DSYSTEM_OS)-g.a

include Makeinclude
