# $Id: Makefile,v 1.1 1997/03/11 14:30:06 carr Exp $

HERE = libs/graphicInterface/cmdProcs

DIRS = paraScopeEditor

.SILENT:

dirs: 
	for dir in $(DIRS); do \
	  echo "Making directory " $$dir; \
	  make -C $$dir; \
	done

