# $Id: Makefile,v 1.2 1997/06/25 14:57:28 carr Exp $

HERE = libs/graphicInterface/oldMonitor/monitor/sms/levelset_sm
VERSIONS = monX
SRCS	= levelset_sm.C
ARCHIVE_monX = ../../monX-$(DSYSTEM_OS)-g.a

include Makeinclude
