# $Id: Makefile,v 1.1 1997/03/11 14:35:42 carr Exp $

HERE = libs/moduleAnalysis/dependence/controlDependence

SRCS = \
	   cdg_cd.ansi.c \
	   cfg_dgcd.ansi.c \
	   control.ansi.c

ARCHIVE	= ../ModuleAnalysis-$(DSYSTEM_OS)-g.a

include Makeinclude
