# $Id: Makefile,v 1.2 1997/06/25 15:05:47 carr Exp $

HERE = libs/moduleAnalysis/dependence/controlDependence

SRCS = \
	   cdg_cd.C \
	   cfg_dgcd.C \
	   control.C

ARCHIVE	= ../ModuleAnalysis-$(DSYSTEM_OS)-g.a

include ../../../../make.config

include $(DEPENDS)

# DO NOT DELETE THIS LINE -- make depend depends on it.
