# $Id: Makefile,v 1.1 1997/03/11 14:34:02 carr Exp $

HERE = libs/graphicInterface/oldMonitor/monitor/sms/message_sm
VERSIONS= monX
SRCS	= message.ansi.c
ARCHIVE_monX = ../../monX-$(DSYSTEM_OS)-g.a

include Makeinclude
