# $Id: Makefile,v 1.2 1997/06/25 14:58:15 carr Exp $

HERE = libs/graphicInterface/oldMonitor/monitor/sms/message_sm
VERSIONS= monX
SRCS	= message.C
ARCHIVE_monX = ../../monX-$(DSYSTEM_OS)-g.a

include Makeinclude
