# $Id: Makefile,v 1.1 1997/03/11 14:37:41 carr Exp $

HERE = libs/support/tables/wordObject

SRCS = \
	   WordObject.C \
	   WordObjectTable.C

ARCHIVE = ../../Support-$(DSYSTEM_OS)-g.a

include ../../../../make.config

include $(DEPENDS)

# DO NOT DELETE THIS LINE -- make depend depends on it.