# $Id: Makefile,v 1.1 1997/03/11 14:30:10 carr Exp $

HERE = libs/graphicInterface/cmdProcs/dEditor

DIRS = \
	   comm \
	   dep \
	   dist \
	   nav \
	   src

SRCS = \
	   DedCP.C \
	   DedCP_opt.C \
	   DedDocument.C \
	   DedEditor.C

ARCHIVE = DEditorCP-$(DSYSTEM_OS)-g.a

include Makeinclude