# $Id: Makefile,v 1.1 1997/03/11 14:35:36 carr Exp $

HERE = libs/moduleAnalysis/cfgValNum

SRCS = \
	   cfgval_build.C \
	   cfgval_interface.C \
	   cfgval_dep.C \
	   cfgval_lookup.C \
	   cfgval_ops.C \
	   cfgval_open.C \
	   constraints.C \
	   jumptrans.C 

ARCHIVE	= ModuleAnalysis-$(DSYSTEM_OS)-g.a

include ../../../make.config

include $(DEPENDS)

# DO NOT DELETE THIS LINE -- make depend depends on it.
