# $Id: Makefile,v 1.1 1997/03/11 14:36:38 carr Exp $

HERE = libs/support/file

SRCS = \
	   Cookie.C \
	   File.C \
	   FileName.ansi.c \
	   FileUtilities.C \
	   FormattedFile.C \
	   ScanDir.C \
	   UnixFile.ansi.c


ARCHIVE = ../Support-$(DSYSTEM_OS)-g.a

include Makeinclude
