# $Id: Makefile,v 1.1 1997/03/11 14:28:20 carr Exp $

HERE = libs/fortD/driver

SRCS = \
	   FortDTest.C \
	   driver.C \
	   interface.C \
	   local_decomp.C \
	   local_decomp2.C

ARCHIVE	= FortD-$(DSYSTEM_OS)-g.a

include Makeinclude
