# $Id: Makefile,v 1.2 1997/03/27 20:32:40 carr Exp $

HERE = libs/fortD/driver

#	   FortDTest.C 
#	   driver.C
#	   interface.C
#	   local_decomp.C 
SRCS = \
	   local_decomp2.C

ARCHIVE	= FortD-$(DSYSTEM_OS)-g.a

include Makeinclude
