# $Id: Makefile,v 1.1 1997/03/11 14:33:55 carr Exp $

HERE = libs/graphicInterface/oldMonitor/monitor/sms
VERSIONS= monX
SRCS	= 
DIRS_monX = button_sm function_sm levelset_sm list_sm message_sm \
	  optim_sm scroll_sm ted_sm text_sm gtd_sm vanilla_sm  

# X windows
ARCHIVE_monX = ../monX-$(DSYSTEM_OS)-g.a


include Makeinclude

