# $Id: Makefile,v 1.1 1997/03/11 14:35:44 carr Exp $

HERE = libs/moduleAnalysis/dependence/dependenceGraph

SRCS = \
	   dg_all.ansi.c \
	   dg_instance.ansi.c \
	   dg_read.ansi.c \
	   edges_dg.ansi.c \
	   ref_dg.ansi.c \
       save_dg.ansi.c \
	   util_dg.ansi.c \
	   vector_dg.ansi.c \
	   walk_dg.ansi.c 

ARCHIVE	= ../ModuleAnalysis-$(DSYSTEM_OS)-g.a

include Makeinclude
