# $Id: Makefile,v 1.2 1997/06/25 15:06:11 carr Exp $

HERE = libs/moduleAnalysis/dependence/dependenceGraph

SRCS = \
	   dg_all.C \
	   dg_instance.C \
	   dg_read.C \
	   edges_dg.C \
	   ref_dg.C \
       save_dg.C \
	   util_dg.C \
	   vector_dg.C \
	   walk_dg.C 

ARCHIVE	= ../ModuleAnalysis-$(DSYSTEM_OS)-g.a

include Makeinclude
