# $Id: Makefile,v 1.1 1997/03/11 14:27:50 carr Exp $

HERE = libs/fileAttrMgmt/composition

SRCS =  \
	Composition.C \
	CompositionIterators.C \
	CompositionSuffixRegistry.C \
	ErrorsCompAttr.C \
	NeedProvCompAttr.C \
	ProcModuleMap.C


ARCHIVE = FileAttrMgmt-$(DSYSTEM_OS)-g.a

include Makeinclude
