# $Id: Makefile,v 1.1 1997/03/11 14:30:24 carr Exp $

HERE = libs/graphicInterface/cmdProcs/dEditor/src

SRCS = \
	   DedDependenceArrow.C \
	   RefDecoration.C \
	   SrcEditor.C \
	   SrcFilterDef.C \
	   SrcView.C \
	   StatDecoration.C

ARCHIVE = ../DEditorCP-$(DSYSTEM_OS)-g.a

include Makeinclude