# $Id: Makefile,v 1.1 1997/03/11 14:27:46 carr Exp $

HERE = libs/fileAttrMgmt/attributedFile

SRCS = \
	Attribute.C \
	AttributeTable.C \
	AttributedFile.C \
	AttributedFileSet.C \
	FileSuffixRegistry.C \
	FileTimeStamp.C \
	RepositoryContext.C

ARCHIVE = FileAttrMgmt-$(DSYSTEM_OS)-g.a

include Makeinclude
