# $Id: Makefile,v 1.2 1997/06/25 14:59:44 carr Exp $

HERE = libs/graphicInterface/oldMonitor/monitor/sms/ted_sm
VERSIONS = monX
SRCS	= \
	  bind.C \
	  buffers.C \
	  ctype.C \
	  delete.C \
	  display.C \
	  dot.C \
	  iflex.C \
	  insert.C \
	  menu.C \
	  misc.C \
	  mode.C \
	  move.C \
	  scroll.C \
	  search.C \
	  sm_ted.C \
	  undo.C \
	  undo_dialog.C \
	  win.C \
	  window.C

ARCHIVE_monX = ../../monX-$(DSYSTEM_OS)-g.a

include Makeinclude
