# $Id: Makefile,v 1.1 1997/03/11 14:34:08 carr Exp $

HERE = libs/graphicInterface/oldMonitor/monitor/sms/ted_sm
VERSIONS = monX
SRCS	= \
	  bind.ansi.c \
	  buffers.ansi.c \
	  ctype.ansi.c \
	  delete.ansi.c \
	  display.ansi.c \
	  dot.ansi.c \
	  iflex.ansi.c \
	  insert.ansi.c \
	  menu.ansi.c \
	  misc.ansi.c \
	  mode.ansi.c \
	  move.ansi.c \
	  scroll.ansi.c \
	  search.ansi.c \
	  sm_ted.ansi.c \
	  undo.ansi.c \
	  undo_dialog.ansi.c \
	  win.ansi.c \
	  window.ansi.c

ARCHIVE_monX = ../../monX-$(DSYSTEM_OS)-g.a

include Makeinclude
