# $Id: Makefile,v 1.1 1997/03/11 14:32:13 carr Exp $

HERE = libs/graphicInterface/cmdProcs/paraScopeEditor/pt

SRCS = \
	   align.ansi.c \
	   distrib.ansi.c  \
	   divide.ansi.c \
	   events.ansi.c \
	   fusion.ansi.c \
	   loop.ansi.c \
	   peel.ansi.c \
	   pt_util.ansi.c \
	   ptrans.ansi.c \
	   renaming.ansi.c \
	   sexpand.ansi.c \
	   skew.ansi.c \
	   split.ansi.c \
	   sreplace.ansi.c \
	   statement.ansi.c \
	   strip.ansi.c \
	   switch.ansi.c \
	   trans.ansi.c \
	   unroll.ansi.c 

ARCHIVE	= ped-$(DSYSTEM_OS)-g.a

include Makeinclude
