# $Id: Makefile,v 1.4 1997/06/25 13:52:57 carr Exp $

HERE = libs/graphicInterface/cmdProcs/paraScopeEditor/pt

SRCS = \
	   align.C \
	   distrib.C  \
	   divide.C \
	   events.C \
	   fusion.C \
	   loop.C \
	   peel.C \
	   pt_util.C \
	   ptrans.C \
	   renaming.C \
	   sexpand.C \
	   skew.C \
	   split.C \
	   sreplace.C \
	   statement.C \
	   strip.C \
	   switch.C \
	   trans.C \
	   unroll.C 

ARCHIVE	= ped-$(DSYSTEM_OS)-g.a

include Makeinclude
