# $Id: Makefile,v 1.1 1998/01/07 14:43:06 carr Exp $

HERE = execs/cfg

SRCS = \
	   Cfg.C \
	   CfgOptions.C

ARCHIVE = Cfg-$(DSYSTEM_OS)-g.a

EXEC = cfg-$(DSYSTEM_OS)-g

DSYSTEM_LIBS = $(NLIBS) 

LOCAL_LIBS = -lm  -ll

include Makeinclude
