# $Id: Makefile,v 1.1 1997/03/11 14:35:41 carr Exp $

HERE = libs/moduleAnalysis/dependence

DIRS = \
	   controlDependence \
	   dependenceGraph \
	   dependenceTest \
	   edgeList \
	   interface \
	   loopInfo \
	   utilities

ARCHIVE	= ModuleAnalysis-$(DSYSTEM_OS)-g.a

include Makeinclude
