# $Id: Makefile,v 1.1 1997/03/11 14:30:20 carr Exp $

HERE = libs/graphicInterface/cmdProcs/dEditor/nav

SRCS = \
	   CostBarDecoration.C \
	   LoopDecoration.C \
	   NavEditor.C \
	   NavFilterDef.C \
	   NavView.C \
	   SubprogDecoration.C

ARCHIVE = ../DEditorCP-$(DSYSTEM_OS)-g.a

include Makeinclude