# $Id: Makefile,v 1.1 1997/03/11 14:33:50 carr Exp $

HERE = libs/graphicInterface/oldMonitor/monitor/mon/root/desk_sm

VERSIONS= monX

SRCS	= desk_sm.ansi.c title_sm.ansi.c

# X windows
ARCHIVE_monX = ../../../monX-$(DSYSTEM_OS)-g.a

include Makeinclude
