# $Id: Makefile,v 1.2 1997/06/25 14:49:52 carr Exp $

HERE = libs/graphicInterface/oldMonitor/monitor/mon/root/desk_sm

VERSIONS= monX

SRCS	= desk_sm.ansi.c title_sm.C

# X windows
ARCHIVE_monX = ../../../monX-$(DSYSTEM_OS)-g.a

include Makeinclude
