# $Id: Makefile,v 1.1 1997/03/11 14:37:06 carr Exp $

HERE = libs/support/optParsing

SRCS = \
	   Options.C \
	   invoke_main.ansi.c \
	   opt_parse.C

ARCHIVE = ../Support-$(DSYSTEM_OS)-g.a

include Makeinclude
