# $Id: Makefile,v 1.1 1997/03/11 14:28:51 carr Exp $

HERE = libs/fortD/performance/instr

SRCS	 = \
	  InstrumentSPMD.C \
	  PabloLib.C \
	  OldPabloLib.C

ARCHIVE	= ../../FortD-$(DSYSTEM_OS)-g.a

include ../../../../make.config

include $(DEPENDS)

# DO NOT DELETE THIS LINE -- make depend depends on it.
