# $Id: Makefile,v 1.1 1997/03/11 14:32:02 carr Exp $

HERE = libs/graphicInterface/cmdProcs/paraScopeEditor/pedCP

SRCS = \
	   change.ansi.c \
	   dia.ansi.c \
	   depdisp.ansi.c \
	   PEditorCP.C \
	   PEditorCP_opt.C

ARCHIVE	= PedCP-$(DSYSTEM_OS)-g.a

#LOCAL_LINT_FLAGS = -command_processor 

include Makeinclude
