# $Id: Makefile,v 1.2 1997/06/25 14:42:34 carr Exp $

HERE = libs/graphicInterface/cmdProcs/paraScopeEditor/pedCP

SRCS = \
	   change.C \
	   dia.C \
	   depdisp.C \
	   PEditorCP.C \
	   PEditorCP_opt.C

ARCHIVE	= PedCP-$(DSYSTEM_OS)-g.a

#LOCAL_LINT_FLAGS = -command_processor 

include Makeinclude
