# $Id: Makefile,v 1.2 1997/06/25 14:41:40 carr Exp $

HERE = libs/graphicInterface/cmdProcs/paraScopeEditor/perf

SRCS = \
	   fit.C \
	   perf.C \
	   perf_init.C \
	   ped_ipperf.C \
	   PEDInterface.C \
	   symtab.C 

ARCHIVE	= ped-$(DSYSTEM_OS)-g.a

include ../../../../../make.config

include $(DEPENDS)

# DO NOT DELETE THIS LINE -- make depend depends on it.