# $Id: Makefile,v 1.1 1997/03/11 14:32:06 carr Exp $

HERE = libs/graphicInterface/cmdProcs/paraScopeEditor/perf

SRCS = \
	   fit.ansi.c \
	   perf.ansi.c \
	   perf_init.ansi.c \
	   ped_ipperf.C \
	   PEDInterface.ansi.c \
	   symtab.ansi.c 

ARCHIVE	= ped-$(DSYSTEM_OS)-g.a

include Makeinclude

