# $Id: Makefile,v 1.7 1997/03/27 20:27:20 carr Exp $
HERE = libs/Memoria/vec
ARCHIVE		= ../Memoria-$(DSYSTEM_OS)-g.a
SRCS		= depGraph.cpp piDepGraph.cpp regionNode.cpp vectorize.cpp scc.cpp

include ../../../make.config

include $(DEPENDS)

# DO NOT DELETE THIS LINE -- make depend depends on it.

