# $Id: Makefile,v 1.1 1993/06/15 13:57:18 carr Exp $
HERE = libs/ped_cp/memory/sp
INCLUDEDIRS	= libs/ped_cp/memory/include libs/ped_cp/ped_include
ARCHIVE		= ../ped-$(RN_ARCH)$(ENV_FLAG).a
SRCS		= prefetch.C

include Makeinclude
