# $Id: Makefile,v 1.2 1997/06/24 17:54:06 carr Exp $

HERE = libs/frontEnd/textTree

SRCS = \
	   TextTree.C \
	   LineArray.C

ARCHIVE	= ../FrontEnd-$(DSYSTEM_OS)-g.a

include ../../../make.config

include $(DEPENDS)

# DO NOT DELETE THIS LINE -- make depend depends on it.