#line 2 "MemoriaConfig.c"

#line 4 "MemoriaConfig.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define Memoria_const const

#if defined(__GNUC__) && __GNUC__ >= 3
#define Memoria_noreturn __attribute__((__noreturn__))
#else
#define Memoria_noreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (Memoria__start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((Memoria__start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE Memoria_restart( Memoria_in  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(Memoria__state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct Memoria__buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t Memoria__size_t;
#endif

extern int Memoria_leng;

extern FILE *Memoria_in, *Memoria_out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define Memoria_less(n) \
	do \
		{ \
		/* Undo effects of setting up Memoria_text. */ \
        int Memoria_less_macro_arg = (n); \
        YY_LESS_LINENO(Memoria_less_macro_arg);\
		*Memoria__cp = (Memoria__hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(Memoria__c_buf_p) = Memoria__cp = Memoria__bp + Memoria_less_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up Memoria_text again */ \
		} \
	while ( 0 )
#define unput(c) Memoria_unput( c, (Memoria_text_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct Memoria__buffer_state
	{
	FILE *Memoria__input_file;

	char *Memoria__ch_buf;		/* input buffer */
	char *Memoria__buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int Memoria__buf_size;

	/* Number of characters read into Memoria__ch_buf, not including EOB
	 * characters.
	 */
	int Memoria__n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int Memoria__is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int Memoria__is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int Memoria__at_bol;

    int Memoria__bs_lineno; /**< The line count. */
    int Memoria__bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int Memoria__fill_buffer;

	int Memoria__buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via Memoria_restart()), so that the user can continue scanning by
	 * just pointing Memoria_in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t Memoria__buffer_stack_top = 0; /**< index of top of stack. */
static size_t Memoria__buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * Memoria__buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (Memoria__buffer_stack) \
                          ? (Memoria__buffer_stack)[(Memoria__buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (Memoria__buffer_stack)[(Memoria__buffer_stack_top)]

/* Memoria__hold_char holds the character lost when Memoria_text is formed. */
static char Memoria__hold_char;
static int Memoria__n_chars;		/* number of characters read into Memoria__ch_buf */
int Memoria_leng;

/* Points to current character in buffer. */
static char *Memoria__c_buf_p = NULL;
static int Memoria__init = 0;		/* whether we need to initialize */
static int Memoria__start = 0;	/* start state number */

/* Flag which is used to allow Memoria_wrap()'s to do buffer switches
 * instead of setting up a fresh Memoria_in.  A bit of a hack ...
 */
static int Memoria__did_buffer_switch_on_eof;

void Memoria_restart ( FILE *input_file  );
void Memoria__switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE Memoria__create_buffer ( FILE *file, int size  );
void Memoria__delete_buffer ( YY_BUFFER_STATE b  );
void Memoria__flush_buffer ( YY_BUFFER_STATE b  );
void Memoria_push_buffer_state ( YY_BUFFER_STATE new_buffer  );
void Memoria_pop_buffer_state ( void );

static void Memoria_ensure_buffer_stack ( void );
static void Memoria__load_buffer_state ( void );
static void Memoria__init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER Memoria__flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE Memoria__scan_buffer ( char *base, Memoria__size_t size  );
YY_BUFFER_STATE Memoria__scan_string ( const char *Memoria__str  );
YY_BUFFER_STATE Memoria__scan_bytes ( const char *bytes, int len  );

void *Memoria_alloc ( Memoria__size_t  );
void *Memoria_realloc ( void *, Memoria__size_t  );
void Memoria_free ( void *  );

#define Memoria__new_buffer Memoria__create_buffer
#define Memoria__set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        Memoria_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            Memoria__create_buffer( Memoria_in, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->Memoria__is_interactive = is_interactive; \
	}
#define Memoria__set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        Memoria_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            Memoria__create_buffer( Memoria_in, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->Memoria__at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->Memoria__at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *Memoria_in = NULL, *Memoria_out = NULL;

typedef int Memoria__state_type;

extern int Memoria_lineno;
int Memoria_lineno = 1;

extern char *Memoria_text;
#ifdef Memoria_text_ptr
#undef Memoria_text_ptr
#endif
#define Memoria_text_ptr Memoria_text

static Memoria__state_type Memoria__get_previous_state ( void );
static Memoria__state_type Memoria__try_NUL_trans ( Memoria__state_type current_state  );
static int Memoria__get_next_buffer ( void );
static void Memoria_noreturn Memoria__fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up Memoria_text.
 */
#define YY_DO_BEFORE_ACTION \
	(Memoria_text_ptr) = Memoria__bp; \
	Memoria_leng = (int) (Memoria__cp - Memoria__bp); \
	(Memoria__hold_char) = *Memoria__cp; \
	*Memoria__cp = '\0'; \
	(Memoria__c_buf_p) = Memoria__cp;
#define YY_NUM_RULES 32
#define YY_END_OF_BUFFER 33
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct Memoria__trans_info
	{
	flex_int32_t Memoria__verify;
	flex_int32_t Memoria__nxt;
	};
static const flex_int16_t Memoria__accept[343] =
    {   0,
        0,    0,   33,   31,   30,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   20,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   18,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   21,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    4,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   19,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   13,    0,    0,

        0,    2,    0,    0,    0,   22,    0,    1,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    5,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   12,    0,    0,
        0,    0,    0,    0,    0,   15,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   23,    0,    0,
        0,    0,    9,    0,    0,    0,    0,    0,   16,    0,
        0,    0,    3,    0,    0,    0,   24,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   10,    0,    0,    0,    0,    0,   14,    0,    0,

        0,    0,    0,    0,    0,    8,    0,    0,    0,    0,
        0,    0,    0,    0,   26,    0,    0,    0,    0,   11,
        0,    0,    7,    0,   25,    0,    0,   17,    0,    0,
        0,    6,    0,    0,    0,   28,    0,    0,    0,   29,
       27,    0
    } ;

static const YY_CHAR Memoria__ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    5,    1,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    7,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    8,    1,    9,   10,   11,   12,

       13,   14,   15,   16,   17,    1,   18,   19,   20,   21,
       22,   23,    1,   24,   25,   26,   27,   28,   29,   30,
       31,   32,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR Memoria__meta[33] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1
    } ;

static const flex_int16_t Memoria__base[343] =
    {   0,
        0,    0,  491,  492,  492,  474,   21,  476,   17,   18,
      471,  466,   18,   33,  464,  462,   27,  472,  459,  460,
      469,  465,  453,  452,  449,  449,  453,  465,  469,  446,
       20,  450,  455,  439,  443,  448,  445,  439,  441,  450,
      445,  444,  431,  455,  434,  435,  447,  438,  444,  444,
       45,  425,  447,  424,   39,  436,  433,  443,  421,  419,
      440,  435,  429,  427,  412,  413,   51,  427,  424,  432,
      427,  422,  414,  406,   52,  410,  419,  405,  404,  412,
      422,  408,  400,  419,  405,  411,  401,  415,  405,   55,
      404,   59,  385,  390,  397,  393,  399,  398,  406,  492,

      392,  377,  380,  393,  392,  379,  382,  389,  390,  377,
      380,  381,  378,  370,   60,  391,  492,  383,  368,  371,
       63,  387,  386,  366,  362,  376,  375,  370,  360,  366,
      367,  366,  349,  360,  356,   68,  364,  365,  492,   65,
      356,  357,  362,   80,  366,   71,  360,   64,  353,  344,
      349,  341,  341,  361,  332,   85,  338,  351,  330,  349,
       90,  338,  342,  338,  347,  342,  326,  329,  346,  320,
      337,  336,  325,   91,  334,  329,   94,   76,  332,  102,
      103,  325,  339,  324,  492,  326,  336,  320,  327,  312,
      323,  322,  323,  307,  317,  318,  106,  324,  304,  306,

      111,  321,  309,  304,  112,  492,  118,  318,  310,  311,
      304,  294,  109,  297,  300,  123,  128,  297,  297,  304,
      289,  309,  132,  291,  288,  293,  133,  303,  283,  276,
      285,  289,  277,  294,  291,  138,  139,  295,  142,  287,
      286,  282,  145,  278,  146,  290,  291,  281,  267,  151,
      281,  276,  152,  276,  263,  279,  157,  492,  266,  261,
      272,  158,  278,  270,  257,  277,  255,  163,  273,  259,
      273,  164,  270,  261,  261,  247,  492,  246,  170,  246,
      249,  251,  248,  173,  253,  254,  251,  242,  249,  178,
      179,  255,  185,  245,  226,  244,  188,  250,  230,  245,

      229,  241,  182,  191,  194,  245,  224,  236,  227,  195,
      235,  200,  213,  203,  492,  216,  207,  205,  212,  197,
      155,  213,  125,  219,  492,  206,  224,  120,   76,   88,
      225,   73,  231,   55,  234,   60,  237,  238,  241,  492,
       52,  492
    } ;

static const flex_int16_t Memoria__def[343] =
    {   0,
      342,    1,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,

      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,

      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,

      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,    0
    } ;

static const flex_int16_t Memoria__nxt[525] =
    {   0,
        4,    4,    5,    4,    4,    4,    6,    4,    7,    8,
        4,    9,    4,   10,    4,   11,   12,    4,   13,   14,
       15,   16,   17,    4,   18,    4,    4,    4,   19,    4,
        4,    4,   21,   25,   32,   22,   27,   28,   26,   33,
       29,   34,   79,   39,   54,   55,   75,   23,   75,   35,
       40,   80,   92,   75,   92,   75,  115,  341,  115,   36,
       92,  115,   92,  115,  144,  336,  144,  145,  146,  161,
      337,  161,  100,  164,  165,  145,  146,  171,  332,  117,
      139,  144,  100,  144,  145,  146,  180,  172,  180,  117,
      139,  161,  197,  161,  197,  201,  198,  201,  203,  202,

      335,  334,  204,  180,  207,  180,  207,  197,  208,  197,
      185,  198,  201,  227,  201,  227,  202,  228,  233,  207,
      185,  207,  206,  208,  237,  328,  237,  234,  238,  239,
      323,  239,  206,  245,  227,  245,  227,  246,  228,  257,
      237,  257,  237,  239,  238,  239,  262,  245,  262,  245,
      263,  246,  268,  272,  268,  272,  269,  273,  257,  262,
      257,  262,  258,  263,  268,  272,  268,  272,  269,  273,
      330,  291,  258,  291,  297,  292,  297,  277,  298,  304,
      291,  304,  291,  314,  292,  314,  305,  277,  305,  297,
      306,  297,  304,  298,  304,  305,  319,  305,  319,  306,

      320,  322,  320,  322,  314,  323,  314,  333,  327,  333,
      327,  315,  328,  319,  322,  319,  322,  320,  323,  329,
      331,  315,  331,  325,  332,  327,  331,  327,  331,  328,
      332,  326,  333,  325,  333,  338,  336,  338,  339,  338,
      339,  338,  339,  324,  339,  321,  341,  318,  317,  316,
      306,  313,  312,  311,  310,  298,  309,  308,  340,  307,
      292,  303,  302,  301,  300,  299,  296,  295,  340,  294,
      293,  290,  289,  288,  287,  273,  286,  285,  269,  284,
      283,  282,  281,  263,  280,  279,  278,  276,  275,  274,
      271,  270,  267,  266,  265,  246,  264,  261,  260,  259,

      238,  256,  255,  254,  253,  252,  251,  250,  228,  249,
      248,  247,  244,  243,  242,  241,  240,  236,  235,  232,
      231,  230,  229,  208,  226,  225,  202,  224,  223,  198,
      222,  221,  220,  219,  218,  217,  216,  215,  214,  213,
      212,  211,  210,  209,  205,  200,  199,  196,  195,  194,
      193,  169,  192,  191,  190,  189,  188,  187,  186,  184,
      183,  182,  181,  179,  178,  177,  176,  175,  174,  173,
      170,  169,  168,  167,  166,  163,  162,  160,  159,  158,
      157,  156,  155,  154,  153,  152,  151,  150,  149,  148,
      147,  143,  142,  141,  140,  138,  137,  136,  135,  134,

      133,  132,  131,  130,  129,  128,  127,  126,  125,  124,
      123,  122,  121,  120,  119,  118,  116,  114,  113,  112,
      111,  110,  109,  108,  107,  106,  105,  104,  103,  102,
      101,   99,   98,   97,   96,   95,   94,   93,   91,   90,
       89,   88,   87,   86,   85,   84,   83,   82,   81,   78,
       77,   76,   74,   73,   72,   71,   70,   69,   68,   67,
       66,   65,   64,   63,   62,   61,   60,   59,   58,   57,
       56,   53,   52,   51,   50,   49,   48,   47,   46,   45,
       44,   43,   42,   41,   38,   37,   31,   30,   24,   20,
      342,    3,  342,  342,  342,  342,  342,  342,  342,  342,

      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342
    } ;

static const flex_int16_t Memoria__chk[525] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    7,    9,   13,    7,   10,   10,    9,   13,
       10,   14,   55,   17,   31,   31,   51,    7,   51,   14,
       17,   55,   67,   75,   67,   75,   90,  341,   90,   14,
       92,  115,   92,  115,  121,  336,  121,  121,  121,  136,
      334,  136,   75,  140,  140,  146,  146,  148,  332,   92,
      115,  144,   75,  144,  144,  144,  156,  148,  156,   92,
      115,  161,  174,  161,  174,  177,  174,  177,  178,  177,

      330,  329,  178,  180,  181,  180,  181,  197,  181,  197,
      161,  197,  201,  205,  201,  205,  201,  205,  213,  207,
      161,  207,  180,  207,  216,  328,  216,  213,  216,  217,
      323,  217,  180,  223,  227,  223,  227,  223,  227,  236,
      237,  236,  237,  239,  237,  239,  243,  245,  243,  245,
      243,  245,  250,  253,  250,  253,  250,  253,  257,  262,
      257,  262,  239,  262,  268,  272,  268,  272,  268,  272,
      321,  279,  239,  279,  284,  279,  284,  257,  284,  290,
      291,  290,  291,  303,  291,  303,  293,  257,  293,  297,
      293,  297,  304,  297,  304,  305,  310,  305,  310,  305,

      310,  312,  320,  312,  314,  312,  314,  326,  317,  326,
      317,  304,  317,  319,  322,  319,  322,  319,  322,  318,
      324,  304,  324,  314,  324,  327,  331,  327,  331,  327,
      331,  316,  333,  314,  333,  335,  333,  335,  337,  338,
      337,  338,  339,  313,  339,  311,  339,  309,  308,  307,
      306,  302,  301,  300,  299,  298,  296,  295,  338,  294,
      292,  289,  288,  287,  286,  285,  283,  282,  338,  281,
      280,  278,  276,  275,  274,  273,  271,  270,  269,  267,
      266,  265,  264,  263,  261,  260,  259,  256,  255,  254,
      252,  251,  249,  248,  247,  246,  244,  242,  241,  240,

      238,  235,  234,  233,  232,  231,  230,  229,  228,  226,
      225,  224,  222,  221,  220,  219,  218,  215,  214,  212,
      211,  210,  209,  208,  204,  203,  202,  200,  199,  198,
      196,  195,  194,  193,  192,  191,  190,  189,  188,  187,
      186,  184,  183,  182,  179,  176,  175,  173,  172,  171,
      170,  169,  168,  167,  166,  165,  164,  163,  162,  160,
      159,  158,  157,  155,  154,  153,  152,  151,  150,  149,
      147,  145,  143,  142,  141,  138,  137,  135,  134,  133,
      132,  131,  130,  129,  128,  127,  126,  125,  124,  123,
      122,  120,  119,  118,  116,  114,  113,  112,  111,  110,

      109,  108,  107,  106,  105,  104,  103,  102,  101,   99,
       98,   97,   96,   95,   94,   93,   91,   89,   88,   87,
       86,   85,   84,   83,   82,   81,   80,   79,   78,   77,
       76,   74,   73,   72,   71,   70,   69,   68,   66,   65,
       64,   63,   62,   61,   60,   59,   58,   57,   56,   54,
       53,   52,   50,   49,   48,   47,   46,   45,   44,   43,
       42,   41,   40,   39,   38,   37,   36,   35,   34,   33,
       32,   30,   29,   28,   27,   26,   25,   24,   23,   22,
       21,   20,   19,   18,   16,   15,   12,   11,    8,    6,
        3,  342,  342,  342,  342,  342,  342,  342,  342,  342,

      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342
    } ;

static Memoria__state_type Memoria__last_accepting_state;
static char *Memoria__last_accepting_cpos;

extern int Memoria__flex_debug;
int Memoria__flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define Memoria_more() Memoria_more_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *Memoria_text;
#line 1 "MemoriaConfig.l"
#line 2 "MemoriaConfig.l"
/* $Id: MemoriaConfig.l,v 1.5 2001/09/14 16:58:59 carr Exp $ */

/*****************************************************************/
/*                                                               */
/*   File:   mh_config.l                                         */
/*                                                               */
/*   Description: Lex definition to read in the memory           */
/*                hierarchy configuration file                   */
/*                                                               */
/*****************************************************************/

#include <libs/support/misc/general.h>
#include <libs/Memoria/include/mh_config.h>

static config_type *config;
static char ctemp;

#line 688 "MemoriaConfig.c"
#line 689 "MemoriaConfig.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int Memoria__init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int Memoria_lex_destroy ( void );

int Memoria_get_debug ( void );

void Memoria_set_debug ( int debug_flag  );

YY_EXTRA_TYPE Memoria_get_extra ( void );

void Memoria_set_extra ( YY_EXTRA_TYPE user_defined  );

FILE *Memoria_get_in ( void );

void Memoria_set_in  ( FILE * _in_str  );

FILE *Memoria_get_out ( void );

void Memoria_set_out  ( FILE * _out_str  );

			int Memoria_get_leng ( void );

char *Memoria_get_text ( void );

int Memoria_get_lineno ( void );

void Memoria_set_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int Memoria_wrap ( void );
#else
extern int Memoria_wrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void Memoria_unput ( int c, char *buf_ptr  );
    
#endif

#ifndef Memoria_text_ptr
static void Memoria__flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int Memoria__flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int Memoria_input ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( Memoria_text, (size_t) Memoria_leng, 1, Memoria_out )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->Memoria__is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( Memoria_in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( Memoria_in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (Memoria__size_t) max_size, Memoria_in)) == 0 && ferror(Memoria_in)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(Memoria_in); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "Memoria_terminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef Memoria_terminate
#define Memoria_terminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) Memoria__fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int Memoria_lex (void);

#define YY_DECL int Memoria_lex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after Memoria_text and Memoria_leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	Memoria__state_type Memoria__current_state;
	char *Memoria__cp, *Memoria__bp;
	int Memoria__act;
    
	if ( !(Memoria__init) )
		{
		(Memoria__init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (Memoria__start) )
			(Memoria__start) = 1;	/* first start state */

		if ( ! Memoria_in )
			Memoria_in = stdin;

		if ( ! Memoria_out )
			Memoria_out = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			Memoria_ensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				Memoria__create_buffer( Memoria_in, YY_BUF_SIZE );
		}

		Memoria__load_buffer_state(  );
		}

	{
#line 21 "MemoriaConfig.l"


#line 909 "MemoriaConfig.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		Memoria__cp = (Memoria__c_buf_p);

		/* Support of Memoria_text. */
		*Memoria__cp = (Memoria__hold_char);

		/* Memoria__bp points to the position in Memoria__ch_buf of the start of
		 * the current run.
		 */
		Memoria__bp = Memoria__cp;

		Memoria__current_state = (Memoria__start);
Memoria__match:
		do
			{
			YY_CHAR Memoria__c = Memoria__ec[YY_SC_TO_UI(*Memoria__cp)] ;
			if ( Memoria__accept[Memoria__current_state] )
				{
				(Memoria__last_accepting_state) = Memoria__current_state;
				(Memoria__last_accepting_cpos) = Memoria__cp;
				}
			while ( Memoria__chk[Memoria__base[Memoria__current_state] + Memoria__c] != Memoria__current_state )
				{
				Memoria__current_state = (int) Memoria__def[Memoria__current_state];
				if ( Memoria__current_state >= 343 )
					Memoria__c = Memoria__meta[Memoria__c];
				}
			Memoria__current_state = Memoria__nxt[Memoria__base[Memoria__current_state] + Memoria__c];
			++Memoria__cp;
			}
		while ( Memoria__base[Memoria__current_state] != 492 );

Memoria__find_action:
		Memoria__act = Memoria__accept[Memoria__current_state];
		if ( Memoria__act == 0 )
			{ /* have to back up */
			Memoria__cp = (Memoria__last_accepting_cpos);
			Memoria__current_state = (Memoria__last_accepting_state);
			Memoria__act = Memoria__accept[Memoria__current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( Memoria__act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*Memoria__cp = (Memoria__hold_char);
			Memoria__cp = (Memoria__last_accepting_cpos);
			Memoria__current_state = (Memoria__last_accepting_state);
			goto Memoria__find_action;

case 1:
YY_RULE_SETUP
#line 23 "MemoriaConfig.l"
sscanf(&Memoria_text[9],"%d",&config->max_regs);
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 25 "MemoriaConfig.l"
sscanf(&Memoria_text[9],"%d",&config->int_regs);
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 27 "MemoriaConfig.l"
sscanf(&Memoria_text[12],"%d",&config->pipe_length);
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 29 "MemoriaConfig.l"
sscanf(&Memoria_text[7],"%f",&config->beta_m);
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 31 "MemoriaConfig.l"
sscanf(&Memoria_text[10],"%d",&config->line);
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 33 "MemoriaConfig.l"
sscanf(&Memoria_text[17],"%d",&config->prefetch_latency);
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 35 "MemoriaConfig.l"
sscanf(&Memoria_text[16],"%d",&config->prefetch_buffer);
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 37 "MemoriaConfig.l"
sscanf(&Memoria_text[15],"%d",&config->double_fetches);
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 39 "MemoriaConfig.l"
sscanf(&Memoria_text[12],"%d",&config->double_regs);
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 41 "MemoriaConfig.l"
sscanf(&Memoria_text[14],"%d",&config->div_cycles);
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 43 "MemoriaConfig.l"
sscanf(&Memoria_text[16],"%d",&config->mul_cycles);
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 45 "MemoriaConfig.l"
sscanf(&Memoria_text[11],"%d",&config->add_cycles);
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 47 "MemoriaConfig.l"
sscanf(&Memoria_text[9],"%d",&config->FPUnits);
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 49 "MemoriaConfig.l"
sscanf(&Memoria_text[14],"%d",&config->IntegerUnits);
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 51 "MemoriaConfig.l"
sscanf(&Memoria_text[11],"%d",&config->hit_cycles);
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 53 "MemoriaConfig.l"
sscanf(&Memoria_text[12],"%d",&config->miss_cycles);
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 55 "MemoriaConfig.l"
sscanf(&Memoria_text[17],"%d",&config->instruction_size);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 57 "MemoriaConfig.l"
{
				  sscanf(&Memoria_text[5],"%s",&ctemp);
				  config->chow_alloc = (ctemp == 'y');
				 }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 62 "MemoriaConfig.l"
{
				  sscanf(&Memoria_text[7],"%s",&ctemp);
				  config->opt_li_alloc = (ctemp == 'y');
				 }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 67 "MemoriaConfig.l"
{
				  sscanf(&Memoria_text[4],"%c",&ctemp);
				  config->mult_accum = (ctemp == 'y');
				 }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 72 "MemoriaConfig.l"
{
				  sscanf(&Memoria_text[5],"%c",&ctemp);
				  config->soft_div= (ctemp == 'y');
				 }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 77 "MemoriaConfig.l"
{
                                  sscanf(&Memoria_text[8],"%c",&ctemp);
				  config->logging = (ctemp == 'y');
				 }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 82 "MemoriaConfig.l"
{
				  sscanf(&Memoria_text[11],"%c",&ctemp);
				  config->aggressive = (ctemp == 'y');
				 }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 86 "MemoriaConfig.l"
{
				  sscanf(&Memoria_text[11],"%c",&ctemp);
				  config->write_back = (ctemp == 'y');
				 }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 90 "MemoriaConfig.l"
{
				  sscanf(&Memoria_text[15],"%c",&ctemp);
				  config->write_allocate=(ctemp == 'y');
				 }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 95 "MemoriaConfig.l"
{
				  sscanf(&Memoria_text[15],"%c",&ctemp);
				  config->AutoIncrement=(ctemp == 'y');
				 }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 100 "MemoriaConfig.l"
{
                                 sscanf(&Memoria_text[20],"%d",
					&config->IntegerPipeLength);
				}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 105 "MemoriaConfig.l"
{
                                 sscanf(&Memoria_text[18],"%d",
					&config->FloatPipeLength);
				}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 110 "MemoriaConfig.l"
{
				  sscanf(&Memoria_text[19],"%c",&ctemp);
				  config->NonBlockingCache=(ctemp == 'y');
				 }
	YY_BREAK
case 30:
/* rule 30 can match eol */
#line 116 "MemoriaConfig.l"
case 31:
/* rule 31 can match eol */
YY_RULE_SETUP
#line 116 "MemoriaConfig.l"
;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 118 "MemoriaConfig.l"
ECHO;
	YY_BREAK
#line 1161 "MemoriaConfig.c"
case YY_STATE_EOF(INITIAL):
	Memoria_terminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int Memoria__amount_of_matched_text = (int) (Memoria__cp - (Memoria_text_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*Memoria__cp = (Memoria__hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->Memoria__buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed Memoria_in at a new source and called
			 * Memoria_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(Memoria__n_chars) = YY_CURRENT_BUFFER_LVALUE->Memoria__n_chars;
			YY_CURRENT_BUFFER_LVALUE->Memoria__input_file = Memoria_in;
			YY_CURRENT_BUFFER_LVALUE->Memoria__buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for Memoria__c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since Memoria__c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (Memoria__c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->Memoria__ch_buf[(Memoria__n_chars)] )
			{ /* This was really a NUL. */
			Memoria__state_type Memoria__next_state;

			(Memoria__c_buf_p) = (Memoria_text_ptr) + Memoria__amount_of_matched_text;

			Memoria__current_state = Memoria__get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * Memoria__get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			Memoria__next_state = Memoria__try_NUL_trans( Memoria__current_state );

			Memoria__bp = (Memoria_text_ptr) + YY_MORE_ADJ;

			if ( Memoria__next_state )
				{
				/* Consume the NUL. */
				Memoria__cp = ++(Memoria__c_buf_p);
				Memoria__current_state = Memoria__next_state;
				goto Memoria__match;
				}

			else
				{
				Memoria__cp = (Memoria__c_buf_p);
				goto Memoria__find_action;
				}
			}

		else switch ( Memoria__get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(Memoria__did_buffer_switch_on_eof) = 0;

				if ( Memoria_wrap(  ) )
					{
					/* Note: because we've taken care in
					 * Memoria__get_next_buffer() to have set up
					 * Memoria_text, we can now set up
					 * Memoria__c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(Memoria__c_buf_p) = (Memoria_text_ptr) + YY_MORE_ADJ;

					Memoria__act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (Memoria__did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(Memoria__c_buf_p) =
					(Memoria_text_ptr) + Memoria__amount_of_matched_text;

				Memoria__current_state = Memoria__get_previous_state(  );

				Memoria__cp = (Memoria__c_buf_p);
				Memoria__bp = (Memoria_text_ptr) + YY_MORE_ADJ;
				goto Memoria__match;

			case EOB_ACT_LAST_MATCH:
				(Memoria__c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->Memoria__ch_buf[(Memoria__n_chars)];

				Memoria__current_state = Memoria__get_previous_state(  );

				Memoria__cp = (Memoria__c_buf_p);
				Memoria__bp = (Memoria_text_ptr) + YY_MORE_ADJ;
				goto Memoria__find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of Memoria_lex */

/* Memoria__get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int Memoria__get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->Memoria__ch_buf;
	char *source = (Memoria_text_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (Memoria__c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->Memoria__ch_buf[(Memoria__n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->Memoria__fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (Memoria__c_buf_p) - (Memoria_text_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((Memoria__c_buf_p) - (Memoria_text_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->Memoria__buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->Memoria__n_chars = (Memoria__n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->Memoria__buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int Memoria__c_buf_p_offset =
				(int) ((Memoria__c_buf_p) - b->Memoria__ch_buf);

			if ( b->Memoria__is_our_buffer )
				{
				int new_size = b->Memoria__buf_size * 2;

				if ( new_size <= 0 )
					b->Memoria__buf_size += b->Memoria__buf_size / 8;
				else
					b->Memoria__buf_size *= 2;

				b->Memoria__ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					Memoria_realloc( (void *) b->Memoria__ch_buf,
							 (Memoria__size_t) (b->Memoria__buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->Memoria__ch_buf = NULL;

			if ( ! b->Memoria__ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(Memoria__c_buf_p) = &b->Memoria__ch_buf[Memoria__c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->Memoria__buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->Memoria__ch_buf[number_to_move]),
			(Memoria__n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->Memoria__n_chars = (Memoria__n_chars);
		}

	if ( (Memoria__n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			Memoria_restart( Memoria_in  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->Memoria__buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((Memoria__n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->Memoria__buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (Memoria__n_chars) + number_to_move + ((Memoria__n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->Memoria__ch_buf = (char *) Memoria_realloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->Memoria__ch_buf, (Memoria__size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->Memoria__ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in Memoria__get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->Memoria__buf_size = (int) (new_size - 2);
	}

	(Memoria__n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->Memoria__ch_buf[(Memoria__n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->Memoria__ch_buf[(Memoria__n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(Memoria_text_ptr) = &YY_CURRENT_BUFFER_LVALUE->Memoria__ch_buf[0];

	return ret_val;
}

/* Memoria__get_previous_state - get the state just before the EOB char was reached */

    static Memoria__state_type Memoria__get_previous_state (void)
{
	Memoria__state_type Memoria__current_state;
	char *Memoria__cp;
    
	Memoria__current_state = (Memoria__start);

	for ( Memoria__cp = (Memoria_text_ptr) + YY_MORE_ADJ; Memoria__cp < (Memoria__c_buf_p); ++Memoria__cp )
		{
		YY_CHAR Memoria__c = (*Memoria__cp ? Memoria__ec[YY_SC_TO_UI(*Memoria__cp)] : 1);
		if ( Memoria__accept[Memoria__current_state] )
			{
			(Memoria__last_accepting_state) = Memoria__current_state;
			(Memoria__last_accepting_cpos) = Memoria__cp;
			}
		while ( Memoria__chk[Memoria__base[Memoria__current_state] + Memoria__c] != Memoria__current_state )
			{
			Memoria__current_state = (int) Memoria__def[Memoria__current_state];
			if ( Memoria__current_state >= 343 )
				Memoria__c = Memoria__meta[Memoria__c];
			}
		Memoria__current_state = Memoria__nxt[Memoria__base[Memoria__current_state] + Memoria__c];
		}

	return Memoria__current_state;
}

/* Memoria__try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = Memoria__try_NUL_trans( current_state );
 */
    static Memoria__state_type Memoria__try_NUL_trans  (Memoria__state_type Memoria__current_state )
{
	int Memoria__is_jam;
    	char *Memoria__cp = (Memoria__c_buf_p);

	YY_CHAR Memoria__c = 1;
	if ( Memoria__accept[Memoria__current_state] )
		{
		(Memoria__last_accepting_state) = Memoria__current_state;
		(Memoria__last_accepting_cpos) = Memoria__cp;
		}
	while ( Memoria__chk[Memoria__base[Memoria__current_state] + Memoria__c] != Memoria__current_state )
		{
		Memoria__current_state = (int) Memoria__def[Memoria__current_state];
		if ( Memoria__current_state >= 343 )
			Memoria__c = Memoria__meta[Memoria__c];
		}
	Memoria__current_state = Memoria__nxt[Memoria__base[Memoria__current_state] + Memoria__c];
	Memoria__is_jam = (Memoria__current_state == 342);

		return Memoria__is_jam ? 0 : Memoria__current_state;
}

#ifndef YY_NO_UNPUT

    static void Memoria_unput (int c, char * Memoria__bp )
{
	char *Memoria__cp;
    
    Memoria__cp = (Memoria__c_buf_p);

	/* undo effects of setting up Memoria_text */
	*Memoria__cp = (Memoria__hold_char);

	if ( Memoria__cp < YY_CURRENT_BUFFER_LVALUE->Memoria__ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (Memoria__n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->Memoria__ch_buf[
					YY_CURRENT_BUFFER_LVALUE->Memoria__buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->Memoria__ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->Memoria__ch_buf )
			*--dest = *--source;

		Memoria__cp += (int) (dest - source);
		Memoria__bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->Memoria__n_chars =
			(Memoria__n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->Memoria__buf_size;

		if ( Memoria__cp < YY_CURRENT_BUFFER_LVALUE->Memoria__ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--Memoria__cp = (char) c;

	(Memoria_text_ptr) = Memoria__bp;
	(Memoria__hold_char) = *Memoria__cp;
	(Memoria__c_buf_p) = Memoria__cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int Memoria_input (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(Memoria__c_buf_p) = (Memoria__hold_char);

	if ( *(Memoria__c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* Memoria__c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (Memoria__c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->Memoria__ch_buf[(Memoria__n_chars)] )
			/* This was really a NUL. */
			*(Memoria__c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((Memoria__c_buf_p) - (Memoria_text_ptr));
			++(Memoria__c_buf_p);

			switch ( Memoria__get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because Memoria__g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					Memoria_restart( Memoria_in );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( Memoria_wrap(  ) )
						return 0;

					if ( ! (Memoria__did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return Memoria_input();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(Memoria__c_buf_p) = (Memoria_text_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (Memoria__c_buf_p);	/* cast for 8-bit char's */
	*(Memoria__c_buf_p) = '\0';	/* preserve Memoria_text */
	(Memoria__hold_char) = *++(Memoria__c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void Memoria_restart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        Memoria_ensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            Memoria__create_buffer( Memoria_in, YY_BUF_SIZE );
	}

	Memoria__init_buffer( YY_CURRENT_BUFFER, input_file );
	Memoria__load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void Memoria__switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		Memoria_pop_buffer_state();
	 *		Memoria_push_buffer_state(new_buffer);
     */
	Memoria_ensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(Memoria__c_buf_p) = (Memoria__hold_char);
		YY_CURRENT_BUFFER_LVALUE->Memoria__buf_pos = (Memoria__c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->Memoria__n_chars = (Memoria__n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	Memoria__load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (Memoria_wrap()) processing, but the only time this flag
	 * is looked at is after Memoria_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(Memoria__did_buffer_switch_on_eof) = 1;
}

static void Memoria__load_buffer_state  (void)
{
    	(Memoria__n_chars) = YY_CURRENT_BUFFER_LVALUE->Memoria__n_chars;
	(Memoria_text_ptr) = (Memoria__c_buf_p) = YY_CURRENT_BUFFER_LVALUE->Memoria__buf_pos;
	Memoria_in = YY_CURRENT_BUFFER_LVALUE->Memoria__input_file;
	(Memoria__hold_char) = *(Memoria__c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE Memoria__create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) Memoria_alloc( sizeof( struct Memoria__buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in Memoria__create_buffer()" );

	b->Memoria__buf_size = size;

	/* Memoria__ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->Memoria__ch_buf = (char *) Memoria_alloc( (Memoria__size_t) (b->Memoria__buf_size + 2)  );
	if ( ! b->Memoria__ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in Memoria__create_buffer()" );

	b->Memoria__is_our_buffer = 1;

	Memoria__init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with Memoria__create_buffer()
 * 
 */
    void Memoria__delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->Memoria__is_our_buffer )
		Memoria_free( (void *) b->Memoria__ch_buf  );

	Memoria_free( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a Memoria_restart() or at EOF.
 */
    static void Memoria__init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	Memoria__flush_buffer( b );

	b->Memoria__input_file = file;
	b->Memoria__fill_buffer = 1;

    /* If b is the current buffer, then Memoria__init_buffer was _probably_
     * called from Memoria_restart() or through Memoria__get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->Memoria__bs_lineno = 1;
        b->Memoria__bs_column = 0;
    }

        b->Memoria__is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void Memoria__flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->Memoria__n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->Memoria__ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->Memoria__ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->Memoria__buf_pos = &b->Memoria__ch_buf[0];

	b->Memoria__at_bol = 1;
	b->Memoria__buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		Memoria__load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void Memoria_push_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	Memoria_ensure_buffer_stack();

	/* This block is copied from Memoria__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(Memoria__c_buf_p) = (Memoria__hold_char);
		YY_CURRENT_BUFFER_LVALUE->Memoria__buf_pos = (Memoria__c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->Memoria__n_chars = (Memoria__n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(Memoria__buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from Memoria__switch_to_buffer. */
	Memoria__load_buffer_state(  );
	(Memoria__did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void Memoria_pop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	Memoria__delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((Memoria__buffer_stack_top) > 0)
		--(Memoria__buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		Memoria__load_buffer_state(  );
		(Memoria__did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void Memoria_ensure_buffer_stack (void)
{
	Memoria__size_t num_to_alloc;
    
	if (!(Memoria__buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(Memoria__buffer_stack) = (struct Memoria__buffer_state**)Memoria_alloc
								(num_to_alloc * sizeof(struct Memoria__buffer_state*)
								);
		if ( ! (Memoria__buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in Memoria_ensure_buffer_stack()" );

		memset((Memoria__buffer_stack), 0, num_to_alloc * sizeof(struct Memoria__buffer_state*));

		(Memoria__buffer_stack_max) = num_to_alloc;
		(Memoria__buffer_stack_top) = 0;
		return;
	}

	if ((Memoria__buffer_stack_top) >= ((Memoria__buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		Memoria__size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (Memoria__buffer_stack_max) + grow_size;
		(Memoria__buffer_stack) = (struct Memoria__buffer_state**)Memoria_realloc
								((Memoria__buffer_stack),
								num_to_alloc * sizeof(struct Memoria__buffer_state*)
								);
		if ( ! (Memoria__buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in Memoria_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((Memoria__buffer_stack) + (Memoria__buffer_stack_max), 0, grow_size * sizeof(struct Memoria__buffer_state*));
		(Memoria__buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE Memoria__scan_buffer  (char * base, Memoria__size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) Memoria_alloc( sizeof( struct Memoria__buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in Memoria__scan_buffer()" );

	b->Memoria__buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->Memoria__buf_pos = b->Memoria__ch_buf = base;
	b->Memoria__is_our_buffer = 0;
	b->Memoria__input_file = NULL;
	b->Memoria__n_chars = b->Memoria__buf_size;
	b->Memoria__is_interactive = 0;
	b->Memoria__at_bol = 1;
	b->Memoria__fill_buffer = 0;
	b->Memoria__buffer_status = YY_BUFFER_NEW;

	Memoria__switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to Memoria_lex() will
 * scan from a @e copy of @a str.
 * @param Memoria_str a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       Memoria__scan_bytes() instead.
 */
YY_BUFFER_STATE Memoria__scan_string (const char * Memoria_str )
{
    
	return Memoria__scan_bytes( Memoria_str, (int) strlen(Memoria_str) );
}

/** Setup the input buffer state to scan the given bytes. The next call to Memoria_lex() will
 * scan from a @e copy of @a bytes.
 * @param Memoria_bytes the byte buffer to scan
 * @param _Memoria_bytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE Memoria__scan_bytes  (const char * Memoria_bytes, int  _Memoria_bytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	Memoria__size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (Memoria__size_t) (_Memoria_bytes_len + 2);
	buf = (char *) Memoria_alloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in Memoria__scan_bytes()" );

	for ( i = 0; i < _Memoria_bytes_len; ++i )
		buf[i] = Memoria_bytes[i];

	buf[_Memoria_bytes_len] = buf[_Memoria_bytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = Memoria__scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in Memoria__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->Memoria__is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void Memoria_noreturn Memoria__fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine Memoria_less() so it works in section 3 code. */

#undef Memoria_less
#define Memoria_less(n) \
	do \
		{ \
		/* Undo effects of setting up Memoria_text. */ \
        int Memoria_less_macro_arg = (n); \
        YY_LESS_LINENO(Memoria_less_macro_arg);\
		Memoria_text[Memoria_leng] = (Memoria__hold_char); \
		(Memoria__c_buf_p) = Memoria_text + Memoria_less_macro_arg; \
		(Memoria__hold_char) = *(Memoria__c_buf_p); \
		*(Memoria__c_buf_p) = '\0'; \
		Memoria_leng = Memoria_less_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int Memoria_get_lineno  (void)
{
    
    return Memoria_lineno;
}

/** Get the input stream.
 * 
 */
FILE *Memoria_get_in  (void)
{
        return Memoria_in;
}

/** Get the output stream.
 * 
 */
FILE *Memoria_get_out  (void)
{
        return Memoria_out;
}

/** Get the length of the current token.
 * 
 */
int Memoria_get_leng  (void)
{
        return Memoria_leng;
}

/** Get the current token.
 * 
 */

char *Memoria_get_text  (void)
{
        return Memoria_text;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void Memoria_set_lineno (int  _line_number )
{
    
    Memoria_lineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see Memoria__switch_to_buffer
 */
void Memoria_set_in (FILE *  _in_str )
{
        Memoria_in = _in_str ;
}

void Memoria_set_out (FILE *  _out_str )
{
        Memoria_out = _out_str ;
}

int Memoria_get_debug  (void)
{
        return Memoria__flex_debug;
}

void Memoria_set_debug (int  _bdebug )
{
        Memoria__flex_debug = _bdebug ;
}

static int Memoria__init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from Memoria_lex_destroy(), so don't allocate here.
     */

    (Memoria__buffer_stack) = NULL;
    (Memoria__buffer_stack_top) = 0;
    (Memoria__buffer_stack_max) = 0;
    (Memoria__c_buf_p) = NULL;
    (Memoria__init) = 0;
    (Memoria__start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    Memoria_in = stdin;
    Memoria_out = stdout;
#else
    Memoria_in = NULL;
    Memoria_out = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * Memoria_lex_init()
     */
    return 0;
}

/* Memoria_lex_destroy is for both reentrant and non-reentrant scanners. */
int Memoria_lex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		Memoria__delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		Memoria_pop_buffer_state();
	}

	/* Destroy the stack itself. */
	Memoria_free((Memoria__buffer_stack) );
	(Memoria__buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * Memoria_lex() is called, initialization will occur. */
    Memoria__init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef Memoria_text_ptr
static void Memoria__flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int Memoria__flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *Memoria_alloc (Memoria__size_t  size )
{
			return malloc(size);
}

void *Memoria_realloc  (void * ptr, Memoria__size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void Memoria_free (void * ptr )
{
			free( (char *) ptr );	/* see Memoria_realloc() for (char *) cast */
}

#define YYTABLES_NAME "Memoria_tables"

#line 118 "MemoriaConfig.l"


int Memoria_wrap()
{
  return 1;
}

void mh_get_config(NewConfig,filename)

  config_type *NewConfig;
  char        *filename;

  {
   FILE *temp,*fd;
   char fn[80];
   int  ret;
	
              /* default settings */

     NewConfig->max_regs = 8;
     NewConfig->int_regs = 8;
     NewConfig->pipe_length = 0;
     NewConfig->beta_m = 1.0;
     NewConfig->prefetch_latency = 0.0;
     NewConfig->prefetch_buffer = 0.0;
     NewConfig->double_fetches = 2;
     NewConfig->double_regs = 2;
     NewConfig->chow_alloc = 0;
     NewConfig->opt_li_alloc = 0;
     NewConfig->line = 64;
     NewConfig->mult_accum = 0;
     NewConfig->soft_div = 0;
     NewConfig->aggressive = 0;
     NewConfig->logging = 0;
     NewConfig->logfile = NULL;
     NewConfig->div_cycles = 10;
     NewConfig->mul_cycles = 1;
     NewConfig->add_cycles = 1;
     NewConfig->FPUnits = 1;
     NewConfig->IntegerUnits = 1;
     NewConfig->min_flop_cycles = 1;
     NewConfig->hit_cycles = 1;
     NewConfig->miss_cycles = 1;
     NewConfig->write_back= 1;
     NewConfig->write_allocate= 0;
     NewConfig->AutoIncrement= 0;
     NewConfig->IntegerPipeLength= 0;
     NewConfig->FloatPipeLength= 0;
     NewConfig->NonBlockingCache= 0;
     NewConfig->instruction_size = 100;

           /* get configuration file */
     if (filename != NULL)
       if ((fd = fopen(filename,"r")) == NULL)
         return;
       else;
     else
       {
        sprintf(fn,"%s/.Memoriarc",getenv("HOME"));
        if ((fd = fopen(fn,"r")) == NULL)
          {
           sprintf(fn,"%s/.mh_config",getenv("DSYSTEM"));
           if ((fd = fopen(fn,"r")) == NULL)
             return;
          }
       }

         /* read in configuration */
     temp = Memoria_in;
     Memoria_in = fd;
     config = NewConfig;
     ret = Memoria_lex();
     Memoria_in = temp;
     NewConfig->min_flop_cycles = NewConfig->mul_cycles < NewConfig->add_cycles ?
                                 (NewConfig->mul_cycles < NewConfig->div_cycles ?
                                  NewConfig->mul_cycles :
                                  NewConfig->div_cycles):
                                 (NewConfig->add_cycles < NewConfig->div_cycles ?
                                  NewConfig->add_cycles :
                                  NewConfig->div_cycles); 
     fclose(fd);
  }
	

