# $Id: Makefile,v 1.1 1997/03/11 14:34:19 carr Exp $

HERE = libs/graphicInterface/oldMonitor/monitor/sms/text_sm
VERSIONS = monX
SRCS	= \
	  text.ansi.c \
	  text_blt.ansi.c \
	  text_size.ansi.c \
	  text_touch.ansi.c

ARCHIVE_monX = ../../monX-$(DSYSTEM_OS)-g.a

include Makeinclude
