# $Id: Makefile,v 1.2 1997/06/25 15:00:25 carr Exp $

HERE = libs/graphicInterface/oldMonitor/monitor/sms/text_sm
VERSIONS = monX
SRCS	= \
	  text.C \
	  text_blt.C \
	  text_size.C \
	  text_touch.C

ARCHIVE_monX = ../../monX-$(DSYSTEM_OS)-g.a

include Makeinclude
