# $Id: Makefile,v 1.1 1997/03/11 14:36:28 carr Exp $

HERE = libs/support/annotation

SRCS = \
	   AnnotatedObject.C \
	   Annotation.C \
	   AnnotationSet.C

ARCHIVE = ../Support-$(DSYSTEM_OS)-g.a

include Makeinclude
