# $Id: Makefile,v 1.1 1997/03/11 14:35:50 carr Exp $

HERE = libs/moduleAnalysis/dependence/dependenceTest

SRCS = \
	   dt.ansi.c \
	   dt_analyze.ansi.c \
	   dt_build.ansi.c \
	   dt_info.ansi.c \
	   rsd.ansi.c \
	   dt_build2.C

ARCHIVE	= ../ModuleAnalysis-$(DSYSTEM_OS)-g.a

include Makeinclude
