# $Id: Makefile,v 1.2 1997/06/25 15:08:54 carr Exp $

HERE = libs/moduleAnalysis/dependence/dependenceTest

SRCS = \
	   dt.C \
	   dt_analyze.C \
	   dt_build.C \
	   dt_info.C \
	   rsd.C \
	   dt_build2.C

ARCHIVE	= ../ModuleAnalysis-$(DSYSTEM_OS)-g.a

include Makeinclude
