# $Id: Makefile,v 1.1 1997/03/11 14:37:16 carr Exp $

HERE = libs/support/registry

SRCS = \
	   ClassInstanceRegistry.C \
	   ConstructorRegistry.C \
	   RegistryObject.C

ARCHIVE = ../Support-$(DSYSTEM_OS)-g.a

include Makeinclude