# $Id: Makefile,v 1.3 1997/04/07 16:22:38 carr Exp $

HERE = execs

ifeq "$(DSYSTEM_OS)" "OSF1"
DIRS = f2i Memoria checker 
else
DIRS = 	f2i \
	Memoria \
	checker \
   	fortDCompiler \
	fortDEditor
endif


include Makeinclude
