# $Id: Makefile,v 1.2 1997/03/27 20:16:30 carr Exp $

HERE = execs

ifeq "$(DSYSTEM_OS)" "OSF1"
DIRS = f2i Memoria checker 
else
DIRS = 	f2i \
	Memoria 
	checker 
   	fortDCompiler \
	fortDEditor
endif


include Makeinclude
