# $Id: Makefile,v 1.1 1997/03/11 14:36:33 carr Exp $

HERE = libs/support/database

SRCS = \
	   DataBase.C

ARCHIVE = ../Support-$(DSYSTEM_OS)-g.a

include ../../../make.config

include $(DEPENDS)

# DO NOT DELETE THIS LINE -- make depend depends on it.