# $Id: Makefile,v 1.1 1997/03/11 14:27:27 carr Exp $

HERE = execs/checker

SRCS = \
	   Checker.C \
	   CheckerOptions.C

ARCHIVE = Checker-$(DSYSTEM_OS)-g.a

EXEC = checker-$(DSYSTEM_OS)-g

DSYSTEM_LIBS = $(NLIBS) 

LOCAL_LIBS = -lm  -ll

include Makeinclude
